# Generated by ratchet/scripts/build_slice_rungs.py — do not edit, regenerate.
# boot stubs: difftest/tiers/tier0/rspec_harvest.py (SORBET_REQUIRE, BLANK_STUB,
#             PATHNAME_STEM_STUB, OUTPUT_STUB) + require "forwardable"
#             + BLANK_NIL_STUB (extend/blank/{nil_class,false_class}.rb)
# library:    1 file(s) linked from vulns/semver.rb; 0 external, 0 cycles
# driver:     ratchet/slice/drivers/semver.rb
require "sorbet-runtime"
class Module
  include T::Sig
end
require "pathname"
require "uri"
require "forwardable"

class Object
  sig { returns(T::Boolean) }
  def blank?
    respond_to?(:empty?) ? !!empty? : false
  end

  sig { returns(T::Boolean) }
  def present? = !blank?

  sig { returns(T.nilable(T.self_type)) }
  def presence = present? ? self : nil
end

class NilClass
  sig { returns(TrueClass) }
  def blank? = true

  sig { returns(FalseClass) }
  def present? = false
end

class FalseClass
  sig { returns(TrueClass) }
  def blank? = true

  sig { returns(FalseClass) }
  def present? = false
end

class Pathname
  sig { returns(String) }
  def stem
    File.basename(self, extname)
  end
end

module Utils
  module Output
    module Mixin
      # See difftest/implementation-notes.md N36: upstream `odebug` returns
      # early unless debug is enabled and otherwise writes to stderr, neither of
      # which is observable here.
      # The sig is upstream's, verbatim (`utils/output.rb:32`) — see N48: a stub
      # without one is a `missing-sig` row in `--fragment` for a method that *is*
      # annotated upstream, i.e. our bug rather than the slice's.
      sig { params(title: T.any(String, Exception), sput: T.anything, always_display: T::Boolean).void }
      def odebug(title, *sput, always_display: false)
        nil
      end
    end
  end
end
# Linked by ruby/linker. Do not edit — regenerate.
# platform: generic
# entries: vulns/semver.rb
# files: 1 (1 spliced, 0 thunked)
# >>> linked: vulns/semver.rb
# typed: strict
# frozen_string_literal: true

module Homebrew
  module Vulns
    # SemVer 2.0 comparison for OSV `SEMVER` ranges (https://semver.org/#spec-item-11).
    # Kept separate from `::Version`, whose ordering differs for prerelease and
    # build metadata. Minor/patch may be omitted; other spec violations return `nil`.
    module Semver
      CORE_SEGMENT = "(0|[1-9]\\d*)"
      private_constant :CORE_SEGMENT

      # A numeric identifier without a leading zero, or an alphanumeric
      # identifier (which may start with any digit).
      PRERELEASE_IDENTIFIER = "(?:0|[1-9]\\d*|\\d*[A-Za-z-][0-9A-Za-z-]*)"
      private_constant :PRERELEASE_IDENTIFIER

      BUILD_IDENTIFIER = "[0-9A-Za-z-]+"
      private_constant :BUILD_IDENTIFIER

      SEMVER_REGEX = /
        \A
        #{CORE_SEGMENT}(?:\.#{CORE_SEGMENT})?(?:\.#{CORE_SEGMENT})?
        (?:-(#{PRERELEASE_IDENTIFIER}(?:\.#{PRERELEASE_IDENTIFIER})*))?
        (?:\+#{BUILD_IDENTIFIER}(?:\.#{BUILD_IDENTIFIER})*)?
        \z
      /x
      private_constant :SEMVER_REGEX

      NUMERIC_IDENTIFIER = /\A\d+\z/
      private_constant :NUMERIC_IDENTIFIER

      sig { params(left: String, right: String).returns(T.nilable(Integer)) }
      def self.compare(left, right)
        a = parse(left)
        b = parse(right)
        return if a.nil? || b.nil?

        core = a.fetch(:core) <=> b.fetch(:core)
        return core unless core.zero?

        compare_prerelease(a.fetch(:prerelease), b.fetch(:prerelease))
      end

      sig { params(version: String).returns(T.nilable({ core: [Integer, Integer, Integer], prerelease: T::Array[String] })) }
      private_class_method def self.parse(version)
        match = version.strip.delete_prefix("v").delete_prefix("V").match(SEMVER_REGEX)
        return if match.nil?

        {
          core:       [match[1].to_i, match[2].to_i, match[3].to_i],
          prerelease: match[4]&.split(".") || [],
        }
      end

      sig { params(left: T::Array[String], right: T::Array[String]).returns(Integer) }
      private_class_method def self.compare_prerelease(left, right)
        return 0 if left.empty? && right.empty?
        return 1 if left.empty?
        return -1 if right.empty?

        left.zip(right) do |lhs, rhs|
          return 1 if rhs.nil?

          cmp = compare_identifier(lhs, rhs)
          return cmp unless cmp.zero?
        end
        (left.length == right.length) ? 0 : -1
      end

      sig { params(lhs: String, rhs: String).returns(Integer) }
      private_class_method def self.compare_identifier(lhs, rhs)
        lhs_numeric = lhs.match?(NUMERIC_IDENTIFIER)
        rhs_numeric = rhs.match?(NUMERIC_IDENTIFIER)

        # spec 11.4.3: numeric identifiers sort below alphanumeric
        return -1 if lhs_numeric && !rhs_numeric
        return 1 if !lhs_numeric && rhs_numeric

        if lhs_numeric
          lhs.to_i <=> rhs.to_i
        else
          T.must(lhs <=> rhs)
        end
      end
    end
  end
end

# <<< end: vulns/semver.rb

# Driver for `vulns/semver.rb` — SemVer 2.0 §11 comparison, exercised as the
# advisory pipeline exercises it: one `Semver.compare(a, b)` per pair.
#
# Real calls only; nothing here reimplements the file. Output discipline (N38):
# every line is process-independent — no addresses, no hashes, no iteration over
# an unordered structure.

def show(label)
  puts("#{label} => #{yield.inspect}")
rescue StandardError => e
  puts("#{label} => #{e.class}: #{e.message}")
end

S = Homebrew::Vulns::Semver

puts("== the ordering, pair by pair")
[
  ["1.0.0", "1.0.0"],            # equal
  ["1.0.1", "1.0.0"],            # patch
  ["1.1.0", "1.0.9"],            # minor beats patch
  ["2.0.0", "1.99.99"],          # major beats everything
  ["1.0", "1.0.0"],              # minor/patch may be omitted
  ["1", "1.0.0"],
  ["v1.2.3", "1.2.3"],           # a `v` prefix is stripped
  ["V1.2.3", "1.2.3"],
  ["  1.2.3  ", "1.2.3"],        # and surrounding space
  ["1.0.0-rc1", "1.0.0"],        # §11.3: a prerelease sorts below its release
  ["1.0.0-alpha", "1.0.0-alpha.1"],
  ["1.0.0-alpha.1", "1.0.0-alpha.beta"],
  ["1.0.0-alpha.beta", "1.0.0-beta"],
  ["1.0.0-beta.2", "1.0.0-beta.11"],   # §11.4.1: numeric identifiers compare numerically
  ["1.0.0-1", "1.0.0-alpha"],          # §11.4.3: numeric sorts below alphanumeric
  ["1.0.0+build", "1.0.0"],            # §10: build metadata is ignored
  ["1.0.0+a", "1.0.0+b"],
  ["1.0.0-rc1+a", "1.0.0-rc1+b"],
].each { |a, b| show("  #{a} <=> #{b}") { S.compare(a, b) } }

puts
puts("== spec violations answer nil, so callers can fall through")
[
  ["01.0.0", "1.0.0"],           # leading zero in a core segment
  ["1.0.0-", "1.0.0"],           # empty prerelease
  ["1.0.0-01", "1.0.0"],         # leading zero in a numeric identifier
  ["1.2.3.4", "1.2.3"],          # four core segments
  ["not a version", "1.0.0"],
  ["", "1.0.0"],
  ["1.0.0", "garbage"],
].each { |a, b| show("  #{a} <=> #{b}") { S.compare(a, b) } }

puts
puts("== the ordering is a total order on what it accepts")
# Sorting through `compare` is the use the advisory ranges actually make of it.
vs = ["1.0.0", "1.0.0-rc1", "0.9.9", "1.0.0+build", "1.0.0-alpha", "2.0.0", "1.0.1"]
show("sorted") { vs.sort { |a, b| S.compare(a, b) || 0 } }
show("is 1.0.0-rc1 < 1.0.0 < 1.0.1?") do
  (S.compare("1.0.0-rc1", "1.0.0") == -1) && (S.compare("1.0.0", "1.0.1") == -1)
end
