# Generated by ratchet/scripts/build_slice_rungs.py — do not edit, regenerate.
# boot stubs: difftest/tiers/tier0/rspec_harvest.py (SORBET_REQUIRE, BLANK_STUB,
#             PATHNAME_STEM_STUB, OUTPUT_STUB) + require "forwardable"
#             + BLANK_NIL_STUB (extend/blank/{nil_class,false_class}.rb)
# library:    1 file(s) linked from version/parser.rb; 0 external, 0 cycles
# driver:     ratchet/slice/drivers/version-parser.rb
require "sorbet-runtime"
class Module
  include T::Sig
end
require "pathname"
require "uri"
require "forwardable"

class Object
  sig { returns(T::Boolean) }
  def blank?
    respond_to?(:empty?) ? !!empty? : false
  end

  sig { returns(T::Boolean) }
  def present? = !blank?

  sig { returns(T.nilable(T.self_type)) }
  def presence = present? ? self : nil
end

class NilClass
  sig { returns(TrueClass) }
  def blank? = true

  sig { returns(FalseClass) }
  def present? = false
end

class FalseClass
  sig { returns(TrueClass) }
  def blank? = true

  sig { returns(FalseClass) }
  def present? = false
end

class Pathname
  sig { returns(String) }
  def stem
    File.basename(self, extname)
  end
end

module Utils
  module Output
    module Mixin
      # See difftest/implementation-notes.md N36: upstream `odebug` returns
      # early unless debug is enabled and otherwise writes to stderr, neither of
      # which is observable here.
      # The sig is upstream's, verbatim (`utils/output.rb:32`) — see N48: a stub
      # without one is a `missing-sig` row in `--fragment` for a method that *is*
      # annotated upstream, i.e. our bug rather than the slice's.
      sig { params(title: T.any(String, Exception), sput: T.anything, always_display: T::Boolean).void }
      def odebug(title, *sput, always_display: false)
        nil
      end
    end
  end
end
# Linked by ruby/linker. Do not edit — regenerate.
# platform: generic
# entries: version/parser.rb
# files: 1 (1 spliced, 0 thunked)
# >>> linked: version/parser.rb
# typed: strict
# frozen_string_literal: true

class Version
  class Parser
    extend T::Helpers

    abstract!

    sig { abstract.params(spec: Pathname).returns(T.nilable(String)) }
    def parse(spec); end
  end

  class RegexParser < Parser
    extend T::Helpers

    abstract!

    sig { params(regex: Regexp, block: T.nilable(T.proc.params(arg0: String).returns(String))).void }
    def initialize(regex, &block)
      super()
      @regex = regex
      @block = block
    end

    sig { override.params(spec: Pathname).returns(T.nilable(String)) }
    def parse(spec)
      match = @regex.match(self.class.process_spec(spec))
      return if match.blank?

      version = match.captures.first
      return if version.blank?
      return @block.call(version) if @block.present?

      version
    end

    sig { params(spec: Pathname).returns(String) }
    def self.process_spec(spec)
      raise NotImplementedError, "#{name}.process_spec must be implemented for #{spec}"
    end
  end

  class UrlParser < RegexParser
    sig { override.params(spec: Pathname).returns(String) }
    def self.process_spec(spec)
      spec.to_s
    end
  end

  class StemParser < RegexParser
    SOURCEFORGE_DOWNLOAD_REGEX = %r{(?:sourceforge\.net|sf\.net)/.*/download$}
    NO_FILE_EXTENSION_REGEX = /\.[^a-zA-Z]+$/

    sig { override.params(spec: Pathname).returns(String) }
    def self.process_spec(spec)
      spec_s = spec.to_s
      return spec.dirname.stem if spec_s.match?(SOURCEFORGE_DOWNLOAD_REGEX)
      return spec.basename.to_s if spec_s.match?(NO_FILE_EXTENSION_REGEX)

      spec.stem
    end
  end
end

# <<< end: version/parser.rb

# Driver for `version/parser.rb` — the abstract `Version::Parser` hierarchy that
# `Version.parse` drives: a regex plus a rule for what part of the spec the
# regex runs against (the whole URL, or its stem).
#
# This file is the slice's one piece of *classical* OO — an `abstract!` base,
# two concrete `process_spec` overrides, an optional post-processing block — so
# the driver exercises the hierarchy directly rather than through `Version`.

def show(label)
  puts("#{label} => #{yield.inspect}")
rescue StandardError => e
  puts("#{label} => #{e.class}: #{e.message}")
end

TARBALL = "https://example.test/downloads/libexample-1.4.2.tar.gz"
TAGGED  = "https://github.com/example/libexample/archive/refs/tags/v1.4.2.tar.gz"
SFORGE  = "https://sourceforge.net/projects/example/files/libexample-2.0/download"
NOEXT   = "https://example.test/downloads/libexample-1.4.2"

puts("== UrlParser matches against the whole URL")
url_parser = Version::UrlParser.new(%r{/archive/refs/tags/v?(\d+(?:\.\d+)*)\.tar\.gz$})
[TARBALL, TAGGED].each { |u| show("  #{u}") { url_parser.parse(Pathname.new(u)) } }

puts
puts("== StemParser matches against the *stem*, and picks it three ways")
# `process_spec` is the whole content of the subclass: the SourceForge
# `/download` route takes the parent directory's stem, an extension-less path
# takes the basename, and everything else takes the stem.
show("  process_spec tarball")     { Version::StemParser.process_spec(Pathname.new(TARBALL)) }
show("  process_spec sourceforge") { Version::StemParser.process_spec(Pathname.new(SFORGE)) }
show("  process_spec no-extension"){ Version::StemParser.process_spec(Pathname.new(NOEXT)) }
show("  process_spec url")         { Version::UrlParser.process_spec(Pathname.new(TARBALL)) }

stem_parser = Version::StemParser.new(/[-_]v?(\d+(?:\.\d+)*)(?:\.tar)?$/)
[TARBALL, SFORGE, NOEXT].each { |u| show("  parse #{u}") { stem_parser.parse(Pathname.new(u)) } }

puts
puts("== the optional block post-processes the capture")
underscored = Version::StemParser.new(/[-_](v?[\d_]+)(?:\.tar)?$/) { |v| v.tr("_", ".") }
show("  1_4_2") { underscored.parse(Pathname.new("https://example.test/libexample-1_4_2.tar.gz")) }

puts
puts("== no match, and an empty capture, both answer nil")
never = Version::UrlParser.new(/(nothing-matches-this)/)
show("  no match")      { never.parse(Pathname.new(TARBALL)) }
show("  empty capture") { Version::UrlParser.new(/libexample(.*)-1/).parse(Pathname.new(TARBALL)) }

puts
puts("== the abstract base is abstract, and RegexParser has no process_spec")
show("Parser.new")        { Version::Parser.new.parse(Pathname.new(TARBALL)) }
show("RegexParser.parse") { Version::RegexParser.new(/(\d+)/).parse(Pathname.new(TARBALL)) }
