#!/usr/bin/env python3
"""One-shot port: `corpus-untyped/` (AST-embedded rungs) -> `corpus/` (typed rungs).

The new corpus's source of truth is the **annotated Ruby file**: the `.rb` is what a
person edits, and everything downstream (the sig manifest, the sig-stripped program, its
AST, the derivation) is generated by `scripts/build_rung.sh`. So the `program` field --
an AST embedded in the rung's JSON by the old `scripts/generate_corpus.py` -- is dropped
here: it is now derived, and a stored copy could disagree with the file.

This script only moves and reshapes. It adds the `# typed: true` sigil (Sorbet will not
look at a file without one) and nothing else; adding `sig`s is hand work, done in the
`.rb` files afterwards, and `expect_sorbet_sigs` records how many the rung is meant to
declare so that a silently-unannotated rung is visible.
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(HERE, "corpus-untyped")
DST = os.path.join(HERE, "corpus")

DEF = re.compile(r"^\s*def ", re.M)

def main() -> int:
    os.makedirs(DST, exist_ok=True)
    n = 0
    for name in sorted(os.listdir(SRC)):
        if not name.endswith(".json"):
            continue
        base = name[:-len(".json")]
        with open(os.path.join(SRC, name)) as fh:
            old = json.load(fh)
        with open(os.path.join(SRC, base + ".rb")) as fh:
            rb = fh.read()
        meta = {
            "id": old["id"],
            "tier": old["tier"],
            "description": old["description"],
            # Does `srb` typecheck the annotated source clean? Ported as "yes" for every
            # rung; the unsafe ones are where this is expected to become `false`, and
            # each disagreement the first pipeline run reports is a finding, not a bug.
            "expect_sorbet": True,
            "expect_validate": old["expect_validate"],
            "false_reason": old["false_reason"],
            # Set by hand as rungs are annotated: the number of `sig`s the file declares.
            # 0 means "no method definitions, nothing to annotate".
            "defs": len(DEF.findall(rb)),
            "annotated": False,
        }
        with open(os.path.join(DST, base + ".rb"), "w") as fh:
            fh.write("# typed: true\n" + rb)
        with open(os.path.join(DST, base + ".meta.json"), "w") as fh:
            json.dump(meta, fh, indent=2)
            fh.write("\n")
        n += 1
    print(f"ported {n} rungs to {DST}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
