/-
`lake exe genbootedheap > RubyCore/Generated/BootedHeap.lean`

Writes the state the prelude boot leaves behind — the heap, the globals and the
shared numeric literals — as Lean terms. It runs `Prelude.boot` and prints the
result, so the terms are the boot's output by construction. The file is a build
artifact, not a committed source: `make` rewrites it whenever the model has
changed, and `Books/Metatheory` proves it equal to the boot.

Why a literal: the boot is about a thousand transitions. Compiled code runs them
in a few milliseconds, but a proof that starts from the booted heap has the
kernel re-run them for every statement it checks. Against a literal it does not.
-/
import RubyCore.Boot

open RubyCore

/-- A `Float` is printed as its bit pattern: exact, and a term the kernel can
    compare. Decimal output is neither. -/
local instance (priority := high) : Repr Float where
  reprPrec x prec := Repr.addAppParen ("Float.ofBits " ++ repr x.toBits) prec

-- `Value` already derives `Repr`, against the decimal `Float` instance; this one
-- is derived here so that it picks up the instance above.
local instance (priority := high) valueRepr : Repr Value where
  reprPrec v prec := match v with
    | .ref o => Repr.addAppParen ("RubyCore.Value.ref " ++ repr o) prec
    | .int n => Repr.addAppParen ("RubyCore.Value.int " ++ reprArg n) prec
    | .flt x => Repr.addAppParen ("RubyCore.Value.flt " ++ reprArg x) prec
    | .sym s => Repr.addAppParen ("RubyCore.Value.sym " ++ repr s) prec
    | .bool b => Repr.addAppParen ("RubyCore.Value.bool " ++ repr b) prec
    | .nil => "RubyCore.Value.nil"

deriving instance Repr for MT.State
deriving instance Repr for MethodDef, ClassPayload, Closure, EnumSize, EnumData
deriving instance Repr for Payload, HashDefault, Object

def term (name type : String) (body : Std.Format) : String :=
  s!"def {name} : {type} :=\n{(Std.Format.nest 2 ("  " ++ body)).pretty 100}\n\n"

def header : String :=
"/-
GENERATED by `lake exe genbootedheap` (GenBootedHeap.lean). A build artifact:
not committed, rewritten by `make`. Do not edit.

What the prelude boot (`Prelude.boot`) leaves behind, as terms: the heap, the
globals and the shared numeric literals. One definition per heap object.
-/
import RubyCore.Heap

namespace RubyCore.Booted
set_option maxRecDepth 100000

"

def main : IO UInt32 := do
  match Prelude.boot with
  | .error e =>
    IO.eprintln s!"the prelude does not boot: {e}"
    return 1
  | .ok m =>
    let mut out := header
    let mut i := 0
    for o in m.heap.objs do
      out := out ++ term s!"object_{i}" "Object" (repr o)
      i := i + 1
    let objs := ", ".intercalate ((List.range i).map fun k => s!"object_{k}")
    out := out ++ term "nameStrings" "List (String × Bool × ObjId)" (repr m.heap.nameStrings)
    out := out ++ s!"def heap : Heap :=\n  \{ objs := #[{objs}], nameStrings := nameStrings }\n\n"
    out := out ++ term "globals" "List (String × Value)" (repr m.globals)
    out := out ++ term "numericLiterals" "List (String × Value)" (repr m.numericLiterals)
    out := out ++ "end RubyCore.Booted\n"
    IO.print out
    return 0
