/-
`lake exe genprelude > RubyCore/Prelude.lean`

Writes the prelude as Lean *terms*. `RubyCore/PreludeJson.lean` holds it as the
JSON the desugarer exports; this decodes that with the model's own
`Decode.program` and prints the result, so the terms are the decoder's output by
construction.

Why terms: the decoder is `partial` and `Json.parse` does not reduce, so a
prelude that is *defined* as "decode this string" is opaque — nothing could be
proved about the booted heap, and no proof about a program could start from it.
A term the kernel can evaluate.
-/
import RubyCore.PreludeJson

open RubyCore

/-- A toplevel `seq` gets one definition per statement, which keeps every term
    small; anything else is printed whole. Either way `name` is exactly `e`. -/
def emitProgram (name : String) (e : Expr) : String := Id.run do
  let term (n : String) (e : Expr) : String :=
    s!"def {n} : Expr :=\n{(Std.Format.nest 2 ("  " ++ repr e)).pretty 100}\n\n"
  match e with
  | .seq stmts =>
    let mut out := ""
    let mut i := 0
    for s in stmts do
      out := out ++ term s!"{name}_{i}" s
      i := i + 1
    let parts := ", ".intercalate ((List.range i).map fun k => s!"{name}_{k}")
    return out ++ s!"def {name} : Expr := .seq [{parts}]\n\n"
  | e => return term name e

def header : String :=
"/-
GENERATED by `lake exe genprelude` (GenPrelude.lean) from RubyCore/PreludeJson.lean,
which scripts/gen_prelude.rb generates from prelude/prelude.rb and
prelude/features/*.rb. Do not edit; run `make gen`.

The prelude and the optional features as RubyCore terms. Core executes at boot;
feature bodies execute on require (L281).
-/
import RubyCore.Syntax

namespace RubyCore.Prelude
set_option maxRecDepth 100000

"

def main : IO UInt32 := do
  match PreludeJson.program, PreludeJson.features with
  | .ok core, .ok features =>
    let mut out := header ++ emitProgram "core" core
    let mut i := 0
    let mut entries : List String := []
    for (name, e) in features do
      out := out ++ emitProgram s!"feature{i}" e
      entries := entries ++ [s!"({name.quote}, feature{i})"]
      i := i + 1
    out := out ++ "def program : Except String Expr := .ok core\n\n"
    out := out ++ s!"def features : Except String (List (String × Expr)) :=\n  .ok [{", ".intercalate entries}]\n\n"
    out := out ++ "end RubyCore.Prelude\n"
    IO.print out
    return 0
  | .error e, _ | _, .error e =>
    IO.eprintln s!"prelude does not decode: {e}"
    return 1
