/-
`lake exe genvfs > RubyCore/Generated/VfsFixture.lean`

Writes the require/require_relative library fixture as Lean *terms*.
`RubyCore/Generated/VfsFixtureJson.lean` holds the bodies as the JSON the
desugarer exports; this decodes them with the model's own `Decode.program` and
prints the result, so the terms are the decoder's output by construction. The
raw files (bytes + pre-split path components) are passed through unchanged.

Why terms: the decoder is `partial` and `Json.parse` does not reduce, so a body
*defined* as "decode this string" is opaque — `boot_ok` (and anything about the
booted heap) could not evaluate it. A term the kernel can evaluate.
-/
import RubyCore.Generated.VfsFixtureJson

open RubyCore

def header : String :=
"/-
GENERATED by `lake exe genvfs` (GenVfs.lean) from RubyCore/Generated/VfsFixtureJson.lean,
which scripts/gen_vfs.rb generates from prelude/vfs/**/*.rb. Do not edit; run `make gen`.

The require/require_relative library fixture as RubyCore terms. `bodies` are the
file bodies that `require_relative` runs; `rawFiles` are mounted into the VFS at
boot so `File.read` sees the same bytes. Boot pairs them by position.
-/
import RubyCore.Syntax

namespace RubyCore.VfsFixture
set_option maxRecDepth 100000

"

def main : IO UInt32 := do
  match VfsFixtureJson.bodies with
  | .ok bodies =>
    let mut out := header
    let mut i := 0
    let mut names : List String := []
    for e in bodies do
      out := out ++ s!"def body{i} : Expr :=\n{(Std.Format.nest 2 ("  " ++ repr e)).pretty 100}\n\n"
      names := names ++ [s!"body{i}"]
      i := i + 1
    out := out ++ s!"def bodies : List Expr := [{", ".intercalate names}]\n\n"
    out := out ++ "/-- Each file as `(canonical path, path components, bytes)`, same order as `bodies`. -/\n"
    out := out ++ s!"def rawFiles : List (String × List String × String) :=\n{(Std.Format.nest 2 ("  " ++ repr VfsFixtureJson.rawFiles)).pretty 100}\n\n"
    out := out ++ "end RubyCore.VfsFixture\n"
    IO.print out
    return 0
  | .error e =>
    IO.eprintln s!"vfs fixture does not decode: {e}"
    return 1
