/-! Instance selector projection of RubyCore/CRubyNames.lean (Ruby 4.0.5).
Denote/Sem/NativePrefix.lean kernel-checks coverage of every modeled native selector.
The checker imports only this data, never the interpreter. -/
namespace Ratchet

def nativeInstanceNames : List String := [
  "!", "!=", "!~", "%", "&", "*", "**",
  "+", "+@", "-", "-@", "/", "<", "<<",
  "<=", "<=>", "==", "===", "=~", ">", ">=",
  ">>", "Array", "Complex", "Float", "Hash", "Integer", "Pathname",
  "Rational", "String", "[]", "[]=", "^", "__callee__", "__dir__",
  "__id__", "__method__", "__send__", "`", "abort", "abs", "abs2",
  "alias_method", "all?", "allbits?", "allocate", "ancestors", "angle", "any?",
  "anybits?", "append", "append_as_bytes", "append_features", "arg", "args", "arity",
  "ascii_only?", "assoc", "at", "at_exit", "attached_object", "attr", "attr_accessor",
  "attr_reader", "attr_writer", "autoload", "autoload?", "b", "backtrace", "backtrace_locations",
  "begin", "between?", "binding", "bit_length", "block_given?", "bsearch", "bsearch_index",
  "byteindex", "byterindex", "bytes", "bytesize", "byteslice", "bytesplice", "call",
  "caller", "caller_locations", "capitalize", "capitalize!", "casecmp", "casecmp?", "catch",
  "cause", "ceil", "ceildiv", "center", "chain", "chars", "chomp",
  "chomp!", "chop", "chop!", "chr", "chunk", "chunk_while", "clamp",
  "class", "class_eval", "class_exec", "class_variable_defined?", "class_variable_get", "class_variable_set", "class_variables",
  "clear", "clone", "codepoints", "coerce", "collect", "collect!", "collect_concat",
  "combination", "compact", "compact!", "compare_by_identity", "compare_by_identity?", "concat", "conj",
  "conjugate", "const_added", "const_defined?", "const_get", "const_missing", "const_set", "const_source_location",
  "constants", "count", "cover?", "crypt", "curry", "cycle", "deconstruct",
  "deconstruct_keys", "dedup", "default", "default=", "default_proc", "default_proc=", "define_method",
  "define_singleton_method", "delete", "delete!", "delete_at", "delete_if", "delete_prefix", "delete_prefix!",
  "delete_suffix", "delete_suffix!", "denominator", "deprecate_constant", "detailed_message", "detect", "difference",
  "dig", "digits", "display", "div", "divmod", "downcase", "downcase!",
  "downto", "drop", "drop_while", "dump", "dup", "each", "each_byte",
  "each_char", "each_codepoint", "each_cons", "each_entry", "each_grapheme_cluster", "each_index", "each_key",
  "each_line", "each_pair", "each_slice", "each_value", "each_with_index", "each_with_object", "empty?",
  "encode", "encode!", "encoding", "end", "end_with?", "entries", "enum_for",
  "eql?", "equal?", "eval", "even?", "except", "exception", "exclude_end?",
  "exec", "exit", "exit!", "exit_value", "extend", "extend_object", "extended",
  "fail", "fdiv", "fetch", "fetch_values", "fill", "filter", "filter!",
  "filter_map", "find", "find_all", "find_index", "finite?", "first", "flat_map",
  "flatten", "flatten!", "floor", "force_encoding", "fork", "format", "freeze",
  "frozen?", "full_message", "gcd", "gcdlcm", "gem", "gem_original_require", "getbyte",
  "gets", "global_variables", "grapheme_clusters", "grep", "grep_v", "group_by", "gsub",
  "gsub!", "has_key?", "has_value?", "hash", "hex", "i", "id2name",
  "imag", "imaginary", "include", "include?", "included", "included_modules", "index",
  "infinite?", "inherited", "initialize", "initialize_clone", "initialize_copy", "initialize_dup", "inject",
  "insert", "inspect", "instance_eval", "instance_exec", "instance_method", "instance_methods", "instance_of?",
  "instance_variable_defined?", "instance_variable_get", "instance_variable_set", "instance_variables", "instance_variables_to_inspect", "integer?", "intern",
  "intersect?", "intersection", "invert", "is_a?", "iterator?", "itself", "join",
  "keep_if", "key", "key?", "keys", "kind_of?", "lambda", "lambda?",
  "last", "lazy", "lcm", "left", "length", "lines", "ljust",
  "load", "local_variables", "loop", "lstrip", "lstrip!", "magnitude", "map",
  "map!", "marshal_dump", "marshal_load", "match", "match?", "max", "max_by",
  "member?", "merge", "merge!", "message", "method", "method_added", "method_defined?",
  "method_missing", "method_removed", "method_undefined", "methods", "min", "min_by", "minmax",
  "minmax_by", "module_eval", "module_exec", "module_function", "modulo", "name", "nan?",
  "negative?", "new", "next", "next!", "next_float", "nil?", "nobits?",
  "none?", "nonzero?", "numerator", "object_id", "oct", "odd?", "one?",
  "open", "ord", "overlap?", "p", "pack", "parameters", "partition",
  "permutation", "phase", "polar", "pop", "positive?", "pow", "pp",
  "pred", "prepend", "prepend_features", "prepended", "prev_float", "print", "printf",
  "private", "private_call?", "private_class_method", "private_constant", "private_instance_methods", "private_method_defined?", "private_methods",
  "proc", "product", "protected", "protected_instance_methods", "protected_method_defined?", "protected_methods", "public",
  "public_class_method", "public_constant", "public_instance_method", "public_instance_methods", "public_method", "public_method_defined?", "public_methods",
  "public_send", "push", "putc", "puts", "quo", "raise", "rand",
  "rassoc", "rationalize", "readline", "readlines", "real", "real?", "reason",
  "receiver", "rect", "rectangular", "reduce", "refine", "refinements", "rehash",
  "reject", "reject!", "remainder", "remove_class_variable", "remove_const", "remove_instance_variable", "remove_method",
  "repeated_combination", "repeated_permutation", "replace", "require", "require_relative", "respond_to?", "respond_to_missing?",
  "result", "reverse", "reverse!", "reverse_each", "rfind", "rindex", "rjust",
  "rotate", "rotate!", "round", "rpartition", "rstrip", "rstrip!", "ruby2_keywords",
  "sample", "scan", "scrub", "scrub!", "select", "select!", "send",
  "set_backtrace", "set_temporary_name", "set_trace_func", "setbyte", "shift", "shuffle", "shuffle!",
  "singleton_class", "singleton_class?", "singleton_method", "singleton_method_added", "singleton_method_removed", "singleton_method_undefined", "singleton_methods",
  "size", "sleep", "slice", "slice!", "slice_after", "slice_before", "slice_when",
  "sort", "sort!", "sort_by", "sort_by!", "source_location", "spawn", "split",
  "sprintf", "squeeze", "squeeze!", "srand", "start_with?", "state", "step",
  "store", "strip", "strip!", "sub", "sub!", "subclasses", "succ",
  "succ!", "sum", "superclass", "swapcase", "swapcase!", "syscall", "system",
  "take", "take_while", "tally", "tap", "test", "then", "throw",
  "times", "to_a", "to_ary", "to_c", "to_enum", "to_f", "to_h",
  "to_hash", "to_i", "to_int", "to_proc", "to_r", "to_s", "to_set",
  "to_str", "to_sym", "tr", "tr!", "tr_s", "tr_s!", "trace_var",
  "transform_keys", "transform_keys!", "transform_values", "transform_values!", "transpose", "trap", "truncate",
  "undef_method", "undefined_instance_methods", "undump", "unicode_normalize", "unicode_normalize!", "unicode_normalized?", "union",
  "uniq", "uniq!", "unpack", "unpack1", "unshift", "untrace_var", "upcase",
  "upcase!", "update", "upto", "using", "valid_encoding?", "value?", "values",
  "values_at", "warn", "yield", "yield_self", "zero?", "zip", "|",
  "~"
]

/-- Sufficient for any inherited native prefix; own calls still use their empty prefix.
This deliberately declines inherited native selector names until a narrower prefix guard. -/
def nativeInstanceFreeB (name : String) : Bool := !nativeInstanceNames.contains name

end Ratchet
