# typed: true
# Generated by ratchet/scripts/build_slice_rungs.py — do not edit, regenerate.
# boot stubs: difftest/tiers/tier0/rspec_harvest.py (SORBET_REQUIRE, BLANK_STUB,
#             PATHNAME_STEM_STUB, OUTPUT_STUB) + require "forwardable"
#             + BLANK_NIL_STUB (extend/blank/{nil_class,false_class}.rb)
# library:    1 file(s) linked from vulns/purl.rb; 0 external, 0 cycles
# driver:     ratchet/slice/drivers/purl.rb
require "sorbet-runtime"
class Module
  include T::Sig
end
require "pathname"
require "uri"
require "forwardable"

class Object
  sig { returns(T::Boolean) }
  def blank?
    respond_to?(:empty?) ? !!empty? : false
  end

  sig { returns(T::Boolean) }
  def present? = !blank?

  sig { returns(T.nilable(T.self_type)) }
  def presence = present? ? self : nil
end

class NilClass
  sig { returns(TrueClass) }
  def blank? = true

  sig { returns(FalseClass) }
  def present? = false
end

class FalseClass
  sig { returns(TrueClass) }
  def blank? = true

  sig { returns(FalseClass) }
  def present? = false
end

class Pathname
  sig { returns(String) }
  def stem
    File.basename(self, extname)
  end
end

module Utils
  module Output
    module Mixin
      # See difftest/implementation-notes.md N36: upstream `odebug` returns
      # early unless debug is enabled and otherwise writes to stderr, neither of
      # which is observable here.
      # The sig is upstream's, verbatim (`utils/output.rb:32`) — see N48: a stub
      # without one is a `missing-sig` row in `--fragment` for a method that *is*
      # annotated upstream, i.e. our bug rather than the slice's.
      sig { params(title: T.any(String, Exception), sput: T.anything, always_display: T::Boolean).void }
      def odebug(title, *sput, always_display: false)
        nil
      end
    end
  end
end
# Linked by ruby/linker. Do not edit — regenerate.
# platform: generic
# entries: vulns/purl.rb
# files: 1 (1 spliced, 0 thunked)
# >>> linked: vulns/purl.rb
# typed: strict
# frozen_string_literal: true

module Homebrew
  module Vulns
    # A package URL per https://github.com/package-url/purl-spec.
    #
    # Minimal builder for the registry types Homebrew derives from formula
    # source URLs. Applies the spec's per-type name normalisation and RFC 3986
    # percent-encoding when serialised. Parsing, qualifiers and subpath are
    # intentionally omitted.
    class Purl
      sig { returns(String) }
      attr_reader :type, :name

      sig { returns(T.nilable(String)) }
      attr_reader :namespace, :version

      sig {
        params(type: String, name: String, namespace: T.nilable(String), version: T.nilable(String)).void
      }
      def initialize(type:, name:, namespace: nil, version: nil)
        raise ArgumentError, "type is required" if type.empty?
        raise ArgumentError, "name is required" if name.empty?

        @type = T.let(type.downcase.freeze, String)
        namespace = nil if namespace && namespace.empty?
        namespace, name = self.class.normalize(@type, namespace, name)
        @namespace = T.let(namespace && -namespace, T.nilable(String))
        @name = T.let(-name, String)
        version = nil if version && version.empty?
        @version = T.let(version && -version, T.nilable(String))
      end

      sig { returns(String) }
      def to_s
        purl = "pkg:#{@type}/"
        if @namespace
          purl << @namespace.split("/").reject(&:empty?).map { |s| self.class.encode(s) }.join("/")
          purl << "/"
        end
        purl << self.class.encode(@name)
        purl << "@#{self.class.encode(@version)}" if @version
        purl.freeze
      end

      sig { params(other: T.anything).returns(T::Boolean) }
      def ==(other)
        case other
        when Purl
          type == other.type && namespace == other.namespace &&
            name == other.name && version == other.version
        else false
        end
      end
      alias eql? ==

      sig { returns(Integer) }
      def hash
        [type, namespace, name, version].hash
      end

      # Percent-encode a single purl component. The spec permits the RFC 3986
      # unreserved set plus `:` unencoded; `+` for space is forbidden so
      # `URI.encode_www_form_component` is unsuitable.
      sig { params(component: String).returns(String) }
      def self.encode(component)
        component.b.gsub(/[^A-Za-z0-9\-._~:]/n) { |c| format("%%%02X", c.ord) }
      end

      # Per-type normalisation from purl-spec PURL-TYPES.rst for the types we emit.
      sig {
        params(type: String, namespace: T.nilable(String), name: String)
          .returns([T.nilable(String), String])
      }
      def self.normalize(type, namespace, name)
        case type
        when "pypi"
          [namespace, name.downcase.tr("_", "-")]
        when "hex"
          [namespace&.downcase, name.downcase]
        when "cpan"
          [namespace&.upcase, name]
        else
          [namespace, name]
        end
      end
    end
  end
end

# <<< end: vulns/purl.rb

# Driver for `vulns/purl.rb` — a package URL builder, exercised through the two
# things the file actually promises: per-type name normalisation
# (purl-spec PURL-TYPES.rst) and RFC 3986 percent-encoding on serialisation.
#
# A `Purl`'s default `inspect` carries an address, so every observation below
# goes through `to_s` or a field reader (N38: process-independent output).

def show(label)
  puts("#{label} => #{yield.inspect}")
rescue StandardError => e
  puts("#{label} => #{e.class}: #{e.message}")
end

P = Homebrew::Vulns::Purl

puts("== construction and serialisation")
[
  { type: "brew", name: "libexample", version: "1.4.2" },
  { type: "gem", name: "nokogiri", version: "1.16.0" },
  { type: "npm", namespace: "@types", name: "node", version: "20.11.0" },
  { type: "maven", namespace: "org.apache.logging.log4j", name: "log4j-core", version: "2.14.1" },
  { type: "generic", name: "libexample" },                       # no version
  { type: "generic", namespace: "", name: "x", version: "" },     # empty ⇒ absent
].each { |kw| show("  #{kw}") { P.new(**kw).to_s } }

puts
puts("== per-type normalisation (the case rules the spec fixes)")
[
  { type: "PyPI", name: "Foo_Bar", version: "1.0" },              # downcase, _ ⇒ -
  { type: "hex", namespace: "Some_Org", name: "MyPkg", version: "1.0" },
  { type: "cpan", namespace: "mshelor", name: "Digest-SHA", version: "6.04" },
  { type: "brew", name: "MixedCase", version: "1.0" },            # no rule ⇒ unchanged
].each { |kw| show("  #{kw}") { p = P.new(**kw); [p.type, p.namespace, p.name, p.to_s] } }

puts
puts("== percent-encoding")
[
  "a b/c@d",
  "n@me",
  "1.0+x",
  "plain-name_1.0~x",   # the unreserved set, plus `:`, stays literal
  "a:b",
  "ü",                  # multi-byte: encoded per byte
].each { |c| show("  #{c}") { P.encode(c) } }

puts
puts("== a namespace is split on `/` and encoded segment by segment")
show("nested") { P.new(type: "generic", namespace: "a b/c/", name: "n@me", version: "1.0+x").to_s }

puts
puts("== equality is structural")
a = P.new(type: "brew", name: "x", version: "1")
b = P.new(type: "brew", name: "x", version: "1")
c = P.new(type: "brew", name: "x", version: "2")
show("a == b") { a == b }
show("a == c") { a == c }
show("a.eql?(b)") { a.eql?(b) }
show("a == a string") { a == "pkg:brew/x@1" }
# `Purl#hash` delegates to `Array#hash`, which the model does not implement — a
# demand on the semantics, not on the checker, so it is deliberately not called
# here (see AGENTS.md, the note on rungs the model cannot run).

puts
puts("== the constructor's own preconditions")
show("empty type") { P.new(type: "", name: "x").to_s }
show("empty name") { P.new(type: "brew", name: "").to_s }
