# typed: true
# Generated by ratchet/scripts/build_slice_rungs.py — do not edit, regenerate.
# boot stubs: difftest/tiers/tier0/rspec_harvest.py (SORBET_REQUIRE, BLANK_STUB,
#             PATHNAME_STEM_STUB, OUTPUT_STUB) + require "forwardable"
#             + BLANK_NIL_STUB (extend/blank/{nil_class,false_class}.rb)
# library:    8 file(s) linked from pkg_version.rb, vulns/vulnerability.rb, vulns/identify.rb; 0 external, 0 cycles
# driver:     ratchet/slice/drivers/slice-adversarial.rb
require "sorbet-runtime"
class Module
  include T::Sig
end
require "pathname"
require "uri"
require "forwardable"

class Object
  sig { returns(T::Boolean) }
  def blank?
    respond_to?(:empty?) ? !!empty? : false
  end

  sig { returns(T::Boolean) }
  def present? = !blank?

  sig { returns(T.nilable(T.self_type)) }
  def presence = present? ? self : nil
end

class NilClass
  sig { returns(TrueClass) }
  def blank? = true

  sig { returns(FalseClass) }
  def present? = false
end

class FalseClass
  sig { returns(TrueClass) }
  def blank? = true

  sig { returns(FalseClass) }
  def present? = false
end

class Pathname
  sig { returns(String) }
  def stem
    File.basename(self, extname)
  end
end

module Utils
  module Output
    module Mixin
      # See difftest/implementation-notes.md N36: upstream `odebug` returns
      # early unless debug is enabled and otherwise writes to stderr, neither of
      # which is observable here.
      # The sig is upstream's, verbatim (`utils/output.rb:32`) — see N48: a stub
      # without one is a `missing-sig` row in `--fragment` for a method that *is*
      # annotated upstream, i.e. our bug rather than the slice's.
      sig { params(title: T.any(String, Exception), sput: T.anything, always_display: T::Boolean).void }
      def odebug(title, *sput, always_display: false)
        nil
      end
    end
  end
end
# Linked by ruby/linker. Do not edit — regenerate.
# platform: generic
# entries: pkg_version.rb, vulns/vulnerability.rb, vulns/identify.rb
# files: 8 (8 spliced, 0 thunked)
# >>> linked: pkg_version.rb
# typed: strict
# frozen_string_literal: true


# >>> linked: version.rb
# typed: strict
# frozen_string_literal: true


# >>> linked: version/parser.rb
# typed: strict
# frozen_string_literal: true

class Version
  class Parser
    extend T::Helpers

    abstract!

    sig { abstract.params(spec: Pathname).returns(T.nilable(String)) }
    def parse(spec); end
  end

  class RegexParser < Parser
    extend T::Helpers

    abstract!

    sig { params(regex: Regexp, block: T.nilable(T.proc.params(arg0: String).returns(String))).void }
    def initialize(regex, &block)
      super()
      @regex = regex
      @block = block
    end

    sig { override.params(spec: Pathname).returns(T.nilable(String)) }
    def parse(spec)
      match = @regex.match(self.class.process_spec(spec))
      return if match.blank?

      version = match.captures.first
      return if version.blank?
      return @block.call(version) if @block.present?

      version
    end

    sig { params(spec: Pathname).returns(String) }
    def self.process_spec(spec)
      raise NotImplementedError, "#{name}.process_spec must be implemented for #{spec}"
    end
  end

  class UrlParser < RegexParser
    sig { override.params(spec: Pathname).returns(String) }
    def self.process_spec(spec)
      spec.to_s
    end
  end

  class StemParser < RegexParser
    SOURCEFORGE_DOWNLOAD_REGEX = %r{(?:sourceforge\.net|sf\.net)/.*/download$}
    NO_FILE_EXTENSION_REGEX = /\.[^a-zA-Z]+$/

    sig { override.params(spec: Pathname).returns(String) }
    def self.process_spec(spec)
      spec_s = spec.to_s
      return spec.dirname.stem if spec_s.match?(SOURCEFORGE_DOWNLOAD_REGEX)
      return spec.basename.to_s if spec_s.match?(NO_FILE_EXTENSION_REGEX)

      spec.stem
    end
  end
end

# <<< end: version/parser.rb



# A formula's version.
class Version
  include Comparable

  sig { params(name: T.any(String, Symbol), full: T::Boolean).returns(Regexp) }
  def self.formula_optionally_versioned_regex(name, full: true)
    /#{"^" if full}#{Regexp.escape(name)}(@\d[\d.]*)?#{"$" if full}/
  end

  # A part of a {Version}.
  class Token
    extend T::Helpers

    abstract!

    include Comparable

    sig { params(val: String).returns(Token) }
    def self.create(val)
      case val
      when /\A#{AlphaToken::PATTERN}\z/o   then AlphaToken
      when /\A#{BetaToken::PATTERN}\z/o    then BetaToken
      when /\A#{RCToken::PATTERN}\z/o      then RCToken
      when /\A#{PreToken::PATTERN}\z/o     then PreToken
      when /\A#{PatchToken::PATTERN}\z/o   then PatchToken
      when /\A#{PostToken::PATTERN}\z/o    then PostToken
      when /\A#{NumericToken::PATTERN}\z/o then NumericToken
      when /\A#{StringToken::PATTERN}\z/o  then StringToken
      else raise "Cannot find a matching token pattern"
      end.new(val)
    end

    sig { params(val: T.untyped).returns(T.nilable(Token)) }
    def self.from(val)
      return NULL_TOKEN if val.nil? || (val.respond_to?(:null?) && val.null?)

      case val
      when Token   then val
      when String  then Token.create(val)
      when Integer then Token.create(val.to_s)
      end
    end

    sig { returns(T.nilable(T.any(String, Integer))) }
    attr_reader :value

    sig { params(value: T.nilable(T.any(String, Integer))).void }
    def initialize(value)
      @value = T.let(value, T.untyped)
    end

    sig { abstract.params(other: T.untyped).returns(T.nilable(Integer)) }
    def <=>(other); end

    sig { returns(String) }
    def inspect
      "#<#{self.class.name} #{value.inspect}>"
    end

    sig { returns(Integer) }
    def hash
      value.hash
    end

    sig { returns(Float) }
    def to_f
      value.to_f
    end

    sig { returns(Integer) }
    def to_i
      value.to_i
    end

    sig { returns(String) }
    def to_str
      value.to_s
    end

    sig { returns(String) }
    def to_s = to_str

    sig { returns(T::Boolean) }
    def numeric?
      false
    end

    sig { returns(T::Boolean) }
    def null?
      false
    end

    sig { returns(T::Boolean) }
    def blank? = null?
  end

  # A pseudo-token representing the absence of a token.
  class NullToken < Token
    sig { override.returns(NilClass) }
    attr_reader :value

    sig { void }
    def initialize
      super(nil)
    end

    sig { override.params(other: T.untyped).returns(T.nilable(Integer)) }
    def <=>(other)
      return unless (other = Token.from(other))

      case other
      when NullToken
        0
      when NumericToken
        other.value.zero? ? 0 : -1
      when AlphaToken, BetaToken, PreToken, RCToken
        1
      else
        -1
      end
    end

    sig { override.returns(T::Boolean) }
    def null?
      true
    end

    sig { returns(T::Boolean) }
    def blank? = true

    sig { returns(String) }
    def inspect
      "#<#{self.class.name}>"
    end
  end
  private_constant :NullToken

  # Represents the absence of a token.
  NULL_TOKEN = NullToken.new.freeze

  # A token string.
  class StringToken < Token
    PATTERN = /[a-z]+/i

    sig { override.returns(String) }
    attr_reader :value

    sig { params(value: String).void }
    def initialize(value)
      super(value.to_s)
    end

    sig { override.params(other: T.untyped).returns(T.nilable(Integer)) }
    def <=>(other)
      return unless (other = Token.from(other))

      case other
      when StringToken
        value <=> other.value
      when NumericToken, NullToken
        -T.must(other <=> self)
      end
    end
  end

  # A token consisting of only numbers.
  class NumericToken < Token
    PATTERN = /[0-9]+/i

    sig { override.returns(Integer) }
    attr_reader :value

    sig { params(value: T.any(String, Integer)).void }
    def initialize(value)
      super(value.to_i)
    end

    sig { override.params(other: T.untyped).returns(T.nilable(Integer)) }
    def <=>(other)
      return unless (other = Token.from(other))

      case other
      when NumericToken
        value <=> other.value
      when StringToken
        1
      when NullToken
        -T.must(other <=> self)
      end
    end

    sig { override.returns(T::Boolean) }
    def numeric?
      true
    end
  end

  # A token consisting of an alphabetic and a numeric part.
  class CompositeToken < StringToken
    sig { returns(Integer) }
    def rev
      value[/[0-9]+/].to_i
    end
  end

  # A token representing the part of a version designating it as an alpha release.
  class AlphaToken < CompositeToken
    PATTERN = /alpha[0-9]*|a[0-9]+/i

    sig { override.params(other: T.untyped).returns(T.nilable(Integer)) }
    def <=>(other)
      return unless (other = Token.from(other))

      case other
      when AlphaToken
        rev <=> other.rev
      when BetaToken, RCToken, PreToken, PatchToken, PostToken
        -1
      else
        super
      end
    end
  end

  # A token representing the part of a version designating it as a beta release.
  class BetaToken < CompositeToken
    PATTERN = /beta[0-9]*|b[0-9]+/i

    sig { override.params(other: T.untyped).returns(T.nilable(Integer)) }
    def <=>(other)
      return unless (other = Token.from(other))

      case other
      when BetaToken
        rev <=> other.rev
      when AlphaToken
        1
      when PreToken, RCToken, PatchToken, PostToken
        -1
      else
        super
      end
    end
  end

  # A token representing the part of a version designating it as a pre-release.
  class PreToken < CompositeToken
    PATTERN = /pre[0-9]*/i

    sig { override.params(other: T.untyped).returns(T.nilable(Integer)) }
    def <=>(other)
      return unless (other = Token.from(other))

      case other
      when PreToken
        rev <=> other.rev
      when AlphaToken, BetaToken
        1
      when RCToken, PatchToken, PostToken
        -1
      else
        super
      end
    end
  end

  # A token representing the part of a version designating it as a release candidate.
  class RCToken < CompositeToken
    PATTERN = /rc[0-9]*/i

    sig { override.params(other: T.untyped).returns(T.nilable(Integer)) }
    def <=>(other)
      return unless (other = Token.from(other))

      case other
      when RCToken
        rev <=> other.rev
      when AlphaToken, BetaToken, PreToken
        1
      when PatchToken, PostToken
        -1
      else
        super
      end
    end
  end

  # A token representing the part of a version designating it as a patch release.
  class PatchToken < CompositeToken
    PATTERN = /p[0-9]*/i

    sig { override.params(other: T.untyped).returns(T.nilable(Integer)) }
    def <=>(other)
      return unless (other = Token.from(other))

      case other
      when PatchToken
        rev <=> other.rev
      when AlphaToken, BetaToken, RCToken, PreToken
        1
      else
        super
      end
    end
  end

  # A token representing the part of a version designating it as a post release.
  class PostToken < CompositeToken
    PATTERN = /.post[0-9]+/i

    sig { override.params(other: T.untyped).returns(T.nilable(Integer)) }
    def <=>(other)
      return unless (other = Token.from(other))

      case other
      when PostToken
        rev <=> other.rev
      when AlphaToken, BetaToken, RCToken, PreToken
        1
      else
        super
      end
    end
  end

  SCAN_PATTERN = T.let(Regexp.union(
    AlphaToken::PATTERN,
    BetaToken::PATTERN,
    PreToken::PATTERN,
    RCToken::PATTERN,
    PatchToken::PATTERN,
    PostToken::PATTERN,
    NumericToken::PATTERN,
    StringToken::PATTERN,
  ).freeze, Regexp)
  private_constant :SCAN_PATTERN

  sig { params(url: T.any(String, Pathname), specs: T.untyped).returns(Version) }
  def self.detect(url, **specs)
    parse(specs.fetch(:tag, url), detected_from_url: true)
  end

  sig { params(spec: T.any(String, Pathname), detected_from_url: T::Boolean).returns(Version) }
  def self.parse(spec, detected_from_url: false)
    # This type of full-URL decoding is not technically correct but we only need a rough decode for version parsing.
    spec = URI.decode_www_form_component(spec.to_s) if detected_from_url

    spec = Pathname(spec)

    VERSION_PARSERS.each do |parser|
      version = parser.parse(spec)
      return new(version, detected_from_url:) if version.present?
    end

    NULL
  end

  NUMERIC_WITH_OPTIONAL_DOTS = T.let(/(?:\d+(?:\.\d+)*)/.source.freeze, String)
  private_constant :NUMERIC_WITH_OPTIONAL_DOTS

  NUMERIC_WITH_DOTS = T.let(/(?:\d+(?:\.\d+)+)/.source.freeze, String)
  private_constant :NUMERIC_WITH_DOTS

  MINOR_OR_PATCH = T.let(/(?:\d+(?:\.\d+){1,2})/.source.freeze, String)
  private_constant :MINOR_OR_PATCH

  CONTENT_SUFFIX = T.let(/(?:[._-](?i:bin|dist|stable|src|sources?|final|full))/.source.freeze, String)
  private_constant :CONTENT_SUFFIX

  PRERELEASE_SUFFIX = T.let(/(?:[._-]?(?i:alpha|beta|pre|rc)\.?\d{,2})/.source.freeze, String)
  private_constant :PRERELEASE_SUFFIX

  VERSION_PARSERS = T.let([
    # date-based versioning
    # e.g. `2023-09-28.tar.gz`
    # e.g. `ltopers-v2017-04-14.tar.gz`
    StemParser.new(/(?:^|[._-]?)v?(\d{4}-\d{2}-\d{2})/),

    # GitHub tarballs
    # e.g. `https://github.com/foo/bar/tarball/v1.2.3`
    # e.g. `https://github.com/sam-github/libnet/tarball/libnet-1.1.4`
    # e.g. `https://github.com/isaacs/npm/tarball/v0.2.5-1`
    # e.g. `https://github.com/petdance/ack/tarball/1.93_02`
    UrlParser.new(%r{github\.com/.+/(?:zip|tar)ball/(?:v|\w+-)?((?:\d+[._-])+\d*)$}),

    # GitHub releases
    # e.g. `https://github.com/foo/bar/releases/download/v1.2/foo-1.2.0.tar.gz`
    UrlParser.new(%r{github\.com/.+/releases/download/(?:[rvV]_?)?(#{NUMERIC_WITH_DOTS})/}),

    # e.g. `https://github.com/erlang/otp/tarball/OTP_R15B01 (erlang style)`
    UrlParser.new(/[_-]([Rr]\d+[AaBb]\d*(?:-\d+)?)/),

    # e.g. `boost_1_39_0`
    StemParser.new(/((?:\d+_)+\d+)$/) { |s| s.tr("_", ".") },

    # e.g. `foobar-4.5.1-1`
    # e.g. `unrtf_0.20.4-1`
    # e.g. `ruby-1.9.1-p243`
    StemParser.new(/[_-](#{NUMERIC_WITH_DOTS}-(?:p|P|rc|RC)?\d+)#{CONTENT_SUFFIX}?$/),

    # Hyphenated versions without software-name prefix (e.g. brew-)
    # e.g. `v0.0.8-12.tar.gz`
    # e.g. `3.3.04-1.tar.gz`
    # e.g. `v2.1-20210510.tar.gz`
    # e.g. `2020.11.11-3.tar.gz`
    # e.g. `v3.6.6-0.2`
    StemParser.new(/^v?(#{NUMERIC_WITH_DOTS}(?:-#{NUMERIC_WITH_OPTIONAL_DOTS})+)/),

    # URL with no extension
    # e.g. `https://waf.io/waf-1.8.12`
    # e.g. `https://codeload.github.com/gsamokovarov/jump/tar.gz/v0.7.1`
    UrlParser.new(/[-v](#{NUMERIC_WITH_OPTIONAL_DOTS})$/),

    # e.g. `lame-398-1`
    StemParser.new(/-(\d+-\d+)/),

    # e.g. `foobar-4.5.1`
    StemParser.new(/-(#{NUMERIC_WITH_OPTIONAL_DOTS})$/),

    # e.g. `foobar-4.5.1.post1`
    StemParser.new(/-(#{NUMERIC_WITH_OPTIONAL_DOTS}(.post\d+)?)$/),

    # e.g. `foobar-4.5.1b`
    StemParser.new(/-(#{NUMERIC_WITH_OPTIONAL_DOTS}(?:[abc]|rc|RC)\d*)$/),

    # e.g. `foobar-4.5.0-alpha5, foobar-4.5.0-beta1, or foobar-4.50-beta`
    StemParser.new(/-(#{NUMERIC_WITH_OPTIONAL_DOTS}-(?:alpha|beta|rc)\d*)$/),

    # e.g. `https://ftpmirror.gnu.org/libidn/libidn-1.29-win64.zip`
    # e.g. `https://ftpmirror.gnu.org/libmicrohttpd/libmicrohttpd-0.9.17-w32.zip`
    StemParser.new(/-(#{MINOR_OR_PATCH})-w(?:in)?(?:32|64)$/),

    # Opam packages
    # e.g. `https://opam.ocaml.org/archives/sha.1.9+opam.tar.gz`
    # e.g. `https://opam.ocaml.org/archives/lablgtk.2.18.3+opam.tar.gz`
    # e.g. `https://opam.ocaml.org/archives/easy-format.1.0.2+opam.tar.gz`
    StemParser.new(/\.(#{MINOR_OR_PATCH})\+opam$/),

    # e.g. `https://ftpmirror.gnu.org/mtools/mtools-4.0.18-1.i686.rpm`
    # e.g. `https://ftpmirror.gnu.org/autogen/autogen-5.5.7-5.i386.rpm`
    # e.g. `https://ftpmirror.gnu.org/libtasn1/libtasn1-2.8-x86.zip`
    # e.g. `https://ftpmirror.gnu.org/libtasn1/libtasn1-2.8-x64.zip`
    # e.g. `https://ftpmirror.gnu.org/mtools/mtools_4.0.18_i386.deb`
    StemParser.new(/[_-](#{MINOR_OR_PATCH}(?:-\d+)?)[._-](?:i[36]86|x86|x64(?:[_-](?:32|64))?)$/),

    # e.g. `https://registry.npmjs.org/@angular/cli/-/cli-1.3.0-beta.1.tgz`
    # e.g. `https://github.com/dlang/dmd/archive/v2.074.0-beta1.tar.gz`
    # e.g. `https://github.com/dlang/dmd/archive/v2.074.0-rc1.tar.gz`
    # e.g. `https://github.com/premake/premake-core/releases/download/v5.0.0-alpha10/premake-5.0.0-alpha10-src.zip`
    StemParser.new(/[-.vV]?(#{NUMERIC_WITH_DOTS}#{PRERELEASE_SUFFIX})/),

    # e.g. `foobar4.5.1`
    StemParser.new(/(#{NUMERIC_WITH_OPTIONAL_DOTS})$/),

    # e.g. `foobar-4.5.0-bin`
    StemParser.new(/[-vV](#{NUMERIC_WITH_DOTS}[abc]?)#{CONTENT_SUFFIX}$/),

    # dash version style
    # e.g. `http://www.antlr.org/download/antlr-3.4-complete.jar`
    # e.g. `https://cdn.nuxeo.com/nuxeo-9.2/nuxeo-server-9.2-tomcat.zip`
    # e.g. `https://search.maven.org/remotecontent?filepath=com/facebook/presto/presto-cli/0.181/presto-cli-0.181-executable.jar`
    # e.g. `https://search.maven.org/remotecontent?filepath=org/fusesource/fuse-extra/fusemq-apollo-mqtt/1.3/fusemq-apollo-mqtt-1.3-uber.jar`
    # e.g. `https://search.maven.org/remotecontent?filepath=org/apache/orc/orc-tools/1.2.3/orc-tools-1.2.3-uber.jar`
    StemParser.new(/-(#{NUMERIC_WITH_DOTS})-/),

    # Debian style
    # e.g. `dash_0.5.5.1.orig.tar.gz`
    # e.g. `lcrack_20040914.orig.tar.gz`
    # e.g. `mkcue_1.orig.tar.gz`
    StemParser.new(/_(#{NUMERIC_WITH_OPTIONAL_DOTS}[abc]?)\.orig$/),

    # e.g. `https://www.openssl.org/source/openssl-0.9.8s.tar.gz`
    StemParser.new(/-v?(\d[^-]+)/),

    # e.g. `astyle_1.23_macosx.tar.gz`
    StemParser.new(/_v?(\d[^_]+)/),

    # e.g. `http://mirrors.jenkins-ci.org/war/1.486/jenkins.war`
    # e.g. `https://github.com/foo/bar/releases/download/0.10.11/bar.phar`
    # e.g. `https://github.com/clojure/clojurescript/releases/download/r1.9.293/cljs.jar`
    # e.g. `https://github.com/fibjs/fibjs/releases/download/v0.6.1/fullsrc.zip`
    # e.g. `https://wwwlehre.dhbw-stuttgart.de/~sschulz/WORK/E_DOWNLOAD/V_1.9/E.tgz`
    # e.g. `https://github.com/JustArchi/ArchiSteamFarm/releases/download/2.3.2.0/ASF.zip`
    # e.g. `https://people.gnome.org/~newren/eg/download/1.7.5.2/eg`
    UrlParser.new(%r{/(?:[rvV]_?)?(\d+\.\d+(?:\.\d+){,2})}),

    # e.g. `https://www.ijg.org/files/jpegsrc.v8d.tar.gz`
    StemParser.new(/\.v(\d+[a-z]?)/),

    # e.g. `https://secure.php.net/get/php-7.1.10.tar.bz2/from/this/mirror`
    UrlParser.new(/[-.vV]?(#{NUMERIC_WITH_DOTS}#{PRERELEASE_SUFFIX}?)/),
  ].freeze, T::Array[Version::Parser])
  private_constant :VERSION_PARSERS

  sig { params(val: T.any(String, Version), detected_from_url: T::Boolean).void }
  def initialize(val, detected_from_url: false)
    version = val.to_str
    raise ArgumentError, "Version must not be empty" if version.blank?

    @version = T.let(version, String)
    @detected_from_url = detected_from_url
  end

  sig { returns(T::Boolean) }
  def detected_from_url?
    @detected_from_url
  end

  HEAD_VERSION_REGEX = /\AHEAD(?:-(?<commit>.*))?\Z/
  private_constant :HEAD_VERSION_REGEX

  # Check if this is a HEAD version.
  #
  # @api public
  sig { returns(T::Boolean) }
  def head?
    version&.match?(HEAD_VERSION_REGEX) || false
  end

  # Return the commit for a HEAD version.
  #
  # @api public
  sig { returns(T.nilable(String)) }
  def commit
    version&.match(HEAD_VERSION_REGEX)&.[](:commit)
  end

  # Update the commit for a HEAD version.
  sig { params(commit: T.nilable(String)).void }
  def update_commit(commit)
    raise ArgumentError, "Cannot update commit for non-HEAD version." unless head?

    @version = if commit
      "HEAD-#{commit}"
    else
      "HEAD"
    end
  end

  sig { returns(T::Boolean) }
  def null?
    version.nil?
  end

  sig { params(comparator: String, other: Version).returns(T::Boolean) }
  def compare(comparator, other)
    case comparator
    when ">=" then self >= other
    when ">" then self > other
    when "<" then self < other
    when "<=" then self <= other
    when "==" then self == other
    when "!=" then self != other
    else raise ArgumentError, "Unknown comparator: #{comparator}"
    end
  end

  sig { params(other: T.untyped).returns(T.nilable(Integer)) }
  def <=>(other)
    other = case other
    when String
      if other.blank?
        # Cannot compare `NULL` to empty string.
        return if null?

        return 1
      end

      # Needed to retain API compatibility with older string comparisons for compiler versions, etc.
      Version.new(other)
    when Integer
      # Used by the `*_build_version` comparisons, which formerly returned an integer.
      Version.new(other.to_s)
    when Token
      if other.null?
        # Cannot compare `NULL` to `NULL`.
        return if null?

        return 1
      end

      Version.new(other.to_s)
    when Version
      if other.null?
        # Cannot compare `NULL` to `NULL`.
        return if null?

        return 1
      end

      other
    when nil
      return 1
    else
      return
    end

    # All `other.null?` cases are handled at this point.
    return -1 if null?

    return 0 if version == other.version
    return 1 if head? && !other.head?
    return -1 if !head? && other.head?
    return 0 if head? && other.head?

    ltokens = tokens
    rtokens = other.tokens
    max = max(ltokens.length, rtokens.length)
    l = r = 0

    while l < max
      a = ltokens[l] || NULL_TOKEN
      b = rtokens[r] || NULL_TOKEN

      if a == b
        l += 1
        r += 1
        next
      elsif a.numeric? && !b.numeric?
        return 1 if a > NULL_TOKEN

        l += 1
      elsif !a.numeric? && b.numeric?
        return -1 if b > NULL_TOKEN

        r += 1
      else
        return a <=> b
      end
    end

    0
  end

  sig { override.params(other: T.anything).returns(T::Boolean) }
  def ==(other)
    # Makes sure that the same instance of Version::NULL
    # will never equal itself; normally Comparable#==
    # will return true for this regardless of the return
    # value of #<=>
    return false if null?

    super
  end
  alias eql? ==

  # The major version.
  #
  # @api public
  sig { returns(T.nilable(Token)) }
  def major
    return NULL_TOKEN if null?

    tokens.first
  end

  # The minor version.
  #
  # @api public
  sig { returns(T.nilable(Token)) }
  def minor
    return NULL_TOKEN if null?

    tokens.second
  end

  # The patch version.
  #
  # @api public
  sig { returns(T.nilable(Token)) }
  def patch
    return NULL_TOKEN if null?

    tokens.third
  end

  # The major and minor version.
  #
  # @api public
  sig { returns(T.self_type) }
  def major_minor
    return self if null?

    major_minor = T.must(tokens[0..1])
    major_minor.empty? ? NULL : self.class.new(major_minor.join("."))
  end

  # The major, minor and patch version.
  #
  # @api public
  sig { returns(T.self_type) }
  def major_minor_patch
    return self if null?

    major_minor_patch = T.must(tokens[0..2])
    major_minor_patch.empty? ? NULL : self.class.new(major_minor_patch.join("."))
  end

  sig { returns(Integer) }
  def hash
    version.hash
  end

  # Convert the version to a floating-point number.
  #
  # @api public
  sig { returns(Float) }
  def to_f
    return Float::NAN if null?

    version.to_f
  end

  # Convert the version to an integer.
  #
  # @api public
  sig { returns(Integer) }
  def to_i
    version.to_i
  end

  # The implicit string conversion of this {Version}, for use where
  # a {String} is expected. Raises {NoMethodError} if this is a {NULL} version.
  #
  # @api public
  sig { returns(String) }
  def to_str
    raise NoMethodError, "undefined method `to_str` for #{self.class}:NULL" if null?

    T.must(version).to_str
  end

  # The string representation of this {Version}.
  #
  # @api public
  sig { returns(String) }
  def to_s = version.to_s

  sig { params(options: T.untyped).returns(String) }
  def to_json(*options) = version.to_json(*options)

  sig { params(method: T.any(Symbol, String), include_all: T::Boolean).returns(T::Boolean) }
  def respond_to?(method, include_all = false)
    return !null? if ["to_str", :to_str].include?(method)

    super
  end

  sig { returns(String) }
  def inspect
    return "#<Version::NULL>" if null?

    "#<Version #{self}>"
  end

  sig { returns(T.self_type) }
  def freeze
    tokens # Determine and store tokens before freezing
    super
  end

  protected

  sig { returns(T.nilable(String)) }
  attr_reader :version

  sig { returns(T::Array[Token]) }
  def tokens
    @tokens ||= T.let(
      version&.scan(SCAN_PATTERN)&.map { |token| Token.create(T.cast(token, String)) } || [],
      T.nilable(T::Array[Token]),
    )
  end

  # Represents the absence of a version.
  #
  # NOTE: Constructor needs to called with an arbitrary non-empty version which is then set to `nil`.
  NULL = T.let(Version.new("NULL").tap { |v| v.instance_variable_set(:@version, nil) }.freeze, Version)

  private

  sig { params(first: Integer, second: Integer).returns(Integer) }
  def max(first, second)
    [first, second].max
  end
end

# <<< end: version.rb



# Combination of a version and a revision.
class PkgVersion
  include Comparable
  extend Forwardable

  REGEX = /\A(.+?)(?:_(\d+))?\z/
  private_constant :REGEX

  sig { returns(Version) }
  attr_reader :version

  sig { returns(Integer) }
  attr_reader :revision

  delegate [:major, :minor, :patch, :major_minor, :major_minor_patch] => :version

  sig { params(path: String).returns(PkgVersion) }
  def self.parse(path)
    _, version, revision = *path.match(REGEX)
    version = Version.new(version.to_s)
    new(version, revision.to_i)
  end

  sig { params(version: Version, revision: Integer).void }
  def initialize(version, revision)
    @version = version
    @revision = revision
  end

  sig { returns(T::Boolean) }
  def head?
    version.head?
  end

  sig { returns(String) }
  def to_str
    if revision.positive?
      "#{version}_#{revision}"
    else
      version.to_s
    end
  end

  sig { returns(String) }
  def to_s = to_str

  sig { params(other: PkgVersion).returns(T.nilable(Integer)) }
  def <=>(other)
    version_comparison = (version <=> other.version)
    return if version_comparison.nil?

    version_comparison.nonzero? || revision <=> other.revision
  end
  alias eql? ==

  sig { returns(Integer) }
  def hash
    [version, revision].hash
  end
end

# <<< end: pkg_version.rb
# >>> linked: vulns/vulnerability.rb
# typed: strict
# frozen_string_literal: true


# >>> linked: vulns/cvss.rb
# typed: strict
# frozen_string_literal: true

module Homebrew
  module Vulns
    # CVSS v3.0/v3.1 base score and qualitative severity rating.
    # See https://www.first.org/cvss/v3-1/specification-document.
    # v2 and v4.0 vectors return `nil` so callers fall through to the next
    # available severity source.
    module CVSS
      AV = T.let({ "N" => 0.85, "A" => 0.62, "L" => 0.55, "P" => 0.2 }.freeze, T::Hash[String, Float])
      AC = T.let({ "L" => 0.77, "H" => 0.44 }.freeze, T::Hash[String, Float])
      UI = T.let({ "N" => 0.85, "R" => 0.62 }.freeze, T::Hash[String, Float])
      CIA = T.let({ "N" => 0.0, "L" => 0.22, "H" => 0.56 }.freeze, T::Hash[String, Float])
      PR_UNCHANGED = T.let({ "N" => 0.85, "L" => 0.62, "H" => 0.27 }.freeze, T::Hash[String, Float])
      PR_CHANGED = T.let({ "N" => 0.85, "L" => 0.68, "H" => 0.50 }.freeze, T::Hash[String, Float])
      private_constant :AV, :AC, :UI, :CIA, :PR_UNCHANGED, :PR_CHANGED

      BASE_METRICS = %w[AV AC PR UI S C I A].freeze
      private_constant :BASE_METRICS

      sig { params(vector: String).returns(T.nilable(Float)) }
      def self.base_score(vector)
        metrics = parse(vector)
        return if metrics.nil?

        scope_changed = metrics.fetch("S") == "C"
        pr_table = scope_changed ? PR_CHANGED : PR_UNCHANGED

        av  = AV.fetch(metrics.fetch("AV"))
        ac  = AC.fetch(metrics.fetch("AC"))
        pr  = pr_table.fetch(metrics.fetch("PR"))
        ui  = UI.fetch(metrics.fetch("UI"))
        c   = CIA.fetch(metrics.fetch("C"))
        i   = CIA.fetch(metrics.fetch("I"))
        a   = CIA.fetch(metrics.fetch("A"))

        iss = 1 - ((1 - c) * (1 - i) * (1 - a))
        impact = if scope_changed
          (7.52 * (iss - 0.029)) - (3.25 * ((iss - 0.02)**15))
        else
          6.42 * iss
        end
        return 0.0 if impact <= 0

        exploitability = 8.22 * av * ac * pr * ui
        raw = impact + exploitability
        raw *= 1.08 if scope_changed
        round_up([raw, 10.0].min)
      end

      sig { params(vector: String).returns(T.nilable(Symbol)) }
      def self.severity(vector)
        score = base_score(vector)
        return if score.nil?

        if score >= 9.0 then :critical
        elsif score >= 7.0 then :high
        elsif score >= 4.0 then :medium
        elsif score > 0.0 then :low
        end
      end

      SUPPORTED_PREFIXES = %w[CVSS:3.0 CVSS:3.1].freeze
      private_constant :SUPPORTED_PREFIXES

      sig { params(vector: String).returns(T.nilable(T::Hash[String, String])) }
      private_class_method def self.parse(vector)
        parts = vector.split("/")
        return unless SUPPORTED_PREFIXES.include?(parts.shift)

        metrics = parts.to_h do |part|
          pair = part.split(":", 2)
          [pair[0] || "", pair[1] || ""]
        end
        return unless BASE_METRICS.all? { |m| metrics.key?(m) }
        return unless valid_values?(metrics)

        metrics
      end

      sig { params(metrics: T::Hash[String, String]).returns(T::Boolean) }
      private_class_method def self.valid_values?(metrics)
        AV.key?(metrics.fetch("AV")) &&
          AC.key?(metrics.fetch("AC")) &&
          PR_UNCHANGED.key?(metrics.fetch("PR")) &&
          UI.key?(metrics.fetch("UI")) &&
          %w[U C].include?(metrics.fetch("S")) &&
          CIA.key?(metrics.fetch("C")) &&
          CIA.key?(metrics.fetch("I")) &&
          CIA.key?(metrics.fetch("A"))
      end

      # CVSS v3.x "Roundup" (spec Appendix A).
      sig { params(value: Float).returns(Float) }
      private_class_method def self.round_up(value)
        int = (value * 100_000).round
        return int / 100_000.0 if (int % 10_000).zero?

        ((int / 10_000) + 1) / 10.0
      end
    end
  end
end

# <<< end: vulns/cvss.rb



# >>> linked: vulns/semver.rb
# typed: strict
# frozen_string_literal: true

module Homebrew
  module Vulns
    # SemVer 2.0 comparison for OSV `SEMVER` ranges (https://semver.org/#spec-item-11).
    # Kept separate from `::Version`, whose ordering differs for prerelease and
    # build metadata. Minor/patch may be omitted; other spec violations return `nil`.
    module Semver
      CORE_SEGMENT = "(0|[1-9]\\d*)"
      private_constant :CORE_SEGMENT

      # A numeric identifier without a leading zero, or an alphanumeric
      # identifier (which may start with any digit).
      PRERELEASE_IDENTIFIER = "(?:0|[1-9]\\d*|\\d*[A-Za-z-][0-9A-Za-z-]*)"
      private_constant :PRERELEASE_IDENTIFIER

      BUILD_IDENTIFIER = "[0-9A-Za-z-]+"
      private_constant :BUILD_IDENTIFIER

      SEMVER_REGEX = /
        \A
        #{CORE_SEGMENT}(?:\.#{CORE_SEGMENT})?(?:\.#{CORE_SEGMENT})?
        (?:-(#{PRERELEASE_IDENTIFIER}(?:\.#{PRERELEASE_IDENTIFIER})*))?
        (?:\+#{BUILD_IDENTIFIER}(?:\.#{BUILD_IDENTIFIER})*)?
        \z
      /x
      private_constant :SEMVER_REGEX

      NUMERIC_IDENTIFIER = /\A\d+\z/
      private_constant :NUMERIC_IDENTIFIER

      sig { params(left: String, right: String).returns(T.nilable(Integer)) }
      def self.compare(left, right)
        a = parse(left)
        b = parse(right)
        return if a.nil? || b.nil?

        core = a.fetch(:core) <=> b.fetch(:core)
        return core unless core.zero?

        compare_prerelease(a.fetch(:prerelease), b.fetch(:prerelease))
      end

      sig { params(version: String).returns(T.nilable({ core: [Integer, Integer, Integer], prerelease: T::Array[String] })) }
      private_class_method def self.parse(version)
        match = version.strip.delete_prefix("v").delete_prefix("V").match(SEMVER_REGEX)
        return if match.nil?

        {
          core:       [match[1].to_i, match[2].to_i, match[3].to_i],
          prerelease: match[4]&.split(".") || [],
        }
      end

      sig { params(left: T::Array[String], right: T::Array[String]).returns(Integer) }
      private_class_method def self.compare_prerelease(left, right)
        return 0 if left.empty? && right.empty?
        return 1 if left.empty?
        return -1 if right.empty?

        left.zip(right) do |lhs, rhs|
          return 1 if rhs.nil?

          cmp = compare_identifier(lhs, rhs)
          return cmp unless cmp.zero?
        end
        (left.length == right.length) ? 0 : -1
      end

      sig { params(lhs: String, rhs: String).returns(Integer) }
      private_class_method def self.compare_identifier(lhs, rhs)
        lhs_numeric = lhs.match?(NUMERIC_IDENTIFIER)
        rhs_numeric = rhs.match?(NUMERIC_IDENTIFIER)

        # spec 11.4.3: numeric identifiers sort below alphanumeric
        return -1 if lhs_numeric && !rhs_numeric
        return 1 if !lhs_numeric && rhs_numeric

        if lhs_numeric
          lhs.to_i <=> rhs.to_i
        else
          T.must(lhs <=> rhs)
        end
      end
    end
  end
end

# <<< end: vulns/semver.rb



module Homebrew
  module Vulns
    # Wraps a single OSV vulnerability record.
    # See https://ossf.github.io/osv-schema/ for the field definitions.
    class Vulnerability
      include Utils::Output::Mixin

      class Interval < T::Struct
        const :lower, T.nilable(String)
        const :upper, T.nilable(String)
        const :upper_inclusive, T::Boolean
        const :fix, T.nilable(String)
      end

      CVSS_TYPE_PRIORITY = T.let(
        { "CVSS_V4" => 4, "CVSS_V3" => 3, "CVSS_V2" => 2 }.freeze,
        T::Hash[String, Integer],
      )
      private_constant :CVSS_TYPE_PRIORITY

      SEVERITY_LEVEL = T.let(
        { critical: 4, high: 3, medium: 2, low: 1 }.freeze,
        T::Hash[Symbol, Integer],
      )
      private_constant :SEVERITY_LEVEL

      sig { returns(String) }
      attr_reader :id

      sig { returns(T.nilable(String)) }
      attr_reader :summary, :details

      sig { returns(T.nilable(Symbol)) }
      attr_reader :severity

      sig { returns(T::Array[String]) }
      attr_reader :aliases, :upstream, :related

      sig { returns(T::Array[T::Hash[String, T.untyped]]) }
      attr_reader :references, :affected, :severity_entries

      sig { params(data: T::Hash[String, T.untyped]).void }
      def initialize(data)
        @id = T.let(data.fetch("id"), String)
        @summary = T.let(data["summary"], T.nilable(String))
        @details = T.let(data["details"], T.nilable(String))
        @aliases = T.let(Array(data["aliases"]), T::Array[String])
        @upstream = T.let(Array(data["upstream"]), T::Array[String])
        @related = T.let(Array(data["related"]), T::Array[String])
        @references = T.let(Array(data["references"]), T::Array[T::Hash[String, T.untyped]])
        @affected = T.let(Array(data["affected"]), T::Array[T::Hash[String, T.untyped]])
        @severity_entries = T.let(Array(data["severity"]), T::Array[T::Hash[String, T.untyped]])
        @severity = T.let(extract_severity(data), T.nilable(Symbol))
      end

      sig { params(list: T::Array[T::Hash[String, T.untyped]]).returns(T::Array[Vulnerability]) }
      def self.from_osv_list(list)
        list.map { |data| new(data) }
      end

      sig { returns(String) }
      def severity_display
        severity&.to_s&.upcase || "UNKNOWN"
      end

      sig { returns(Integer) }
      def severity_level
        sev = severity
        return 0 if sev.nil?

        SEVERITY_LEVEL.fetch(sev, 0)
      end

      # Only `id` and `aliases` name *this* vulnerability. `upstream` is a
      # directed reference (a distro advisory pointing at one-or-more source
      # CVEs) and `related` links to different vulnerabilities; neither is safe
      # to treat as an identity of this record. {Match} follows `upstream`
      # explicitly and re-attributes the hit to each CVE it names.
      sig { returns(T::Array[String]) }
      def identifiers
        [id, *aliases].uniq
      end

      sig { returns(T::Array[String]) }
      def cve_ids
        identifiers.select { |i| i.start_with?("CVE-") }
      end

      sig { returns(T.nilable(String)) }
      def advisory_url
        references.find { |r| r["type"] == "ADVISORY" }&.dig("url")
      end

      sig { returns(T::Array[String]) }
      def fix_urls
        references.select { |r| r["type"] == "FIX" }.filter_map { |r| r["url"] }
      end

      sig { returns(T::Array[String]) }
      def fixed_versions
        affected.flat_map do |aff|
          Array(aff["ranges"]).flat_map do |range|
            Array(range["events"]).filter_map { |e| e["fixed"] }
          end
        end.uniq
      end

      # `state` is `:affected` (in an interval), `:fixed` (past the closing
      # boundary of at least one interval), or `:not_applicable` (below the
      # `introduced` of every interval; the vulnerability never applied to this
      # version). `fixed_in` is the boundary that closed the containing
      # interval (`:affected`) or the highest boundary at-or-below the version
      # (`:fixed`).
      RangeStatus = Struct.new(:state, :fixed_in, keyword_init: true) do
        sig { returns(T::Boolean) }
        def affected? = state == :affected

        sig { returns(T::Boolean) }
        def fixed? = state == :fixed
      end

      # Evaluates `version` against every `affected[]` entry whose `package`
      # matches `{ecosystem, name}` (an advisory can carry several disjoint
      # entries for the same package, e.g. GHSA-jfh8-c2jp-5v3q's three
      # log4j-core ranges), honouring range `type`:
      #
      # - `SEMVER` ranges compare with {Semver}.
      # - `ECOSYSTEM` ranges compare with {Version} (best-effort; the record's
      #   own ecosystem defines the ordering, but callers only invoke this for
      #   ecosystems whose versions are broadly `Version`-comparable).
      # - `GIT` ranges are commit hashes and are skipped as uncomparable.
      #
      # Returns `nil` when no entry matches the package or no comparable range
      # exists in the matching entries, so callers can distinguish
      # `:not_applicable`/`:fixed` from "could not check".
      sig { params(ecosystem: String, name: String, version: String).returns(T.nilable(RangeStatus)) }
      def range_status(ecosystem, name, version)
        entries = affected_entries_for(ecosystem, name)
        return if entries.empty?

        target = normalize_version(version)
        checked = T.let(false, T::Boolean)
        past_fixes = T.let([], T::Array[String])

        entries.each do |entry|
          Array(entry["ranges"]).each do |range|
            type = range["type"]
            next if type == "GIT"

            cmp = comparator_for(type)
            intervals(Array(range["events"])).each do |interval|
              inside = in_interval?(target, interval.lower, interval.upper, interval.upper_inclusive, cmp)
              checked = true
              if inside
                fixed_in = interval.upper_inclusive ? nil : interval.upper
                return RangeStatus.new(state: :affected, fixed_in:).freeze
              end
              upper = interval.upper
              next unless upper

              rel = cmp.call(target, upper)
              past_fixes << upper if interval.upper_inclusive ? rel.positive? : rel >= 0
            rescue Uncomparable
              next
            end
          end

          versions = Array(entry["versions"])
          next if versions.empty?

          checked = true
          if versions.any? { |v| normalize_version(v.to_s) == target }
            return RangeStatus.new(state: :affected, fixed_in: nil).freeze
          end
        end

        return unless checked

        state = past_fixes.any? ? :fixed : :not_applicable
        RangeStatus.new(state:, fixed_in: past_fixes.max_by { |v| Version.new(v) }).freeze
      end

      sig { params(ecosystem: String, name: String).returns(T::Array[T::Hash[String, T.untyped]]) }
      def affected_entries_for(ecosystem, name)
        affected.select do |aff|
          pkg = aff["package"]
          pkg.is_a?(Hash) && pkg["ecosystem"] == ecosystem && pkg["name"] == name
        end
      end

      sig { params(range_type: T.nilable(String)).returns(T.proc.params(a: String, b: String).returns(Integer)) }
      def comparator_for(range_type)
        if range_type == "SEMVER"
          ->(a, b) { Semver.compare(a, b) || raise(Uncomparable) }
        else
          ->(a, b) { Version.new(a) <=> Version.new(b) || raise(Uncomparable) }
        end
      end

      sig {
        params(target: String, lower: T.nilable(String), upper: T.nilable(String),
               upper_inclusive: T::Boolean,
               cmp: T.proc.params(a: String, b: String).returns(Integer)).returns(T::Boolean)
      }
      def in_interval?(target, lower, upper, upper_inclusive, cmp)
        above = lower.nil? || cmp.call(target, lower) >= 0
        below = if upper.nil?
          true
        elsif upper_inclusive
          cmp.call(target, upper) <= 0
        else
          cmp.call(target, upper).negative?
        end
        above && below
      end

      # OSV has already matched this record against the queried version. This
      # method only overrides that with `false` when every affected entry can
      # be evaluated locally (explicit `versions` list or `SEMVER` range) and
      # none of them contains the target. Any uncheckable range or comparison
      # failure keeps the match.
      sig { params(version: String).returns(T::Boolean) }
      def affects_version?(version)
        return true if affected.empty?

        target = normalize_version(version)
        checkable = T.let(false, T::Boolean)

        affected.each do |aff|
          versions = Array(aff["versions"])
          if versions.any?
            checkable = true
            return true if versions.any? { |v| normalize_version(v.to_s) == target }
          end

          Array(aff["ranges"]).each do |range|
            return true if range["type"] != "SEMVER"

            checkable = true
            return true if in_semver_range?(target, Array(range["events"]))
          end
        end

        !checkable
      end

      sig { params(data: T::Hash[String, T.untyped]).returns(T.nilable(Symbol)) }
      def extract_severity(data)
        Array(data["severity"])
          .select { |s| CVSS_TYPE_PRIORITY.key?(s["type"]) }
          .sort_by { |s| -CVSS_TYPE_PRIORITY.fetch(s["type"]) }
          .each do |s|
            sev = CVSS.severity(s["score"].to_s)
            return sev if sev
          end

        top = normalize_severity(data.dig("database_specific", "severity"))
        return top if top

        affected.each do |aff|
          eco = normalize_severity(aff.dig("ecosystem_specific", "severity"))
          return eco if eco

          db = normalize_severity(aff.dig("database_specific", "severity"))
          return db if db
        end

        nil
      end

      sig { params(value: T.nilable(String)).returns(T.nilable(Symbol)) }
      def normalize_severity(value)
        case value&.downcase
        when "critical" then :critical
        when "high" then :high
        when "medium", "moderate" then :medium
        when "low" then :low
        end
      end

      sig { params(version: String).returns(String) }
      def normalize_version(version)
        version.sub(/\Av/i, "")
      end

      class Uncomparable < StandardError
      end

      sig { params(target: String, events: T::Array[T::Hash[String, T.untyped]]).returns(T::Boolean) }
      def in_semver_range?(target, events)
        return false if events.empty?

        intervals(events).any? { |interval| in_interval_permissive?(target, interval) }
      end

      sig { params(target: String, interval: Interval).returns(T.nilable(T::Boolean)) }
      def in_interval_strict?(target, interval)
        lower = interval.lower
        upper = interval.upper
        above = lower.nil? || semver_compare!(target, lower) >= 0
        below = if upper.nil?
          true
        elsif interval.upper_inclusive
          semver_compare!(target, upper) <= 0
        else
          semver_compare!(target, upper).negative?
        end
        above && below
      rescue Uncomparable
        nil
      end

      sig { params(target: String, interval: Interval).returns(T::Boolean) }
      def in_interval_permissive?(target, interval)
        in_interval_strict?(target, interval) != false
      rescue => e
        odebug "Failed to check #{target} against interval #{interval.inspect} for #{id}: #{e}"
        true
      end

      sig { params(left: String, right: String).returns(Integer) }
      def semver_compare!(left, right)
        Semver.compare(left, right) || raise(Uncomparable, "cannot compare #{left.inspect} with #{right.inspect}")
      end

      sig {
        params(events: T::Array[T::Hash[String, T.untyped]])
          .returns(T::Array[Interval])
      }
      def intervals(events)
        result = []
        lower = T.let(nil, T.nilable(String))

        events.each do |event|
          if (intro = event["introduced"])
            result << Interval.new(lower: lower, upper: nil, upper_inclusive: false, fix: nil) if lower
            intro = normalize_version(intro.to_s)
            lower = (intro == "0") ? nil : intro
          elsif (fixed = event["fixed"])
            fixed_norm = normalize_version(fixed.to_s)
            result << Interval.new(lower: lower, upper: fixed_norm, upper_inclusive: false, fix: fixed_norm)
            lower = nil
          elsif (last = event["last_affected"])
            last_norm = normalize_version(last.to_s)
            result << Interval.new(lower: lower, upper: last_norm, upper_inclusive: true, fix: nil)
            lower = nil
          elsif (limit = event["limit"])
            limit = limit.to_s
            upper = (limit == "*") ? nil : normalize_version(limit)
            result << Interval.new(lower: lower, upper: upper, upper_inclusive: false, fix: nil)
            lower = nil
          end
        end
        result << Interval.new(lower: lower, upper: nil, upper_inclusive: false, fix: nil) if lower || result.empty?
        result
      end

      sig { params(target: String, range: T::Hash[String, T.untyped]).returns(T::Boolean) }
      def non_semver_fix_available?(target, range)
        events = Array(range["events"])
        return false if events.empty?

        range_intervals = intervals(events)
        uncomparable_seen = T.let(false, T::Boolean)
        range_intervals.each do |interval|
          result = in_interval_strict?(target, interval)
          if result.nil?
            uncomparable_seen = true
            next
          end
          return interval.fix.present? if result
        end

        return false unless uncomparable_seen

        last_event = events.last
        return false if last_event.nil?

        last_event.key?("fixed")
      end

      sig { params(aff: T::Hash[String, T.untyped], repo_url: T.nilable(String)).returns(T::Boolean) }
      def affected_entry_relevant?(aff, repo_url)
        return true if repo_url.nil?
        return false if (ecosystem = aff.dig("package", "ecosystem")) && ecosystem != "GIT"

        git_ranges = Array(aff["ranges"]).select { |r| r["type"] == "GIT" }
        return true if git_ranges.empty?

        normalized_repo = repo_url.downcase.chomp("/").delete_suffix(".git").chomp("/")
        git_ranges.any? do |r|
          range_repo = r["repo"].to_s.downcase.chomp("/").delete_suffix(".git").chomp("/")
          range_repo.empty? || range_repo == normalized_repo
        end
      end

      sig { params(version: String, repo_url: T.nilable(String)).returns(T::Boolean) }
      def fix_available?(version, repo_url = nil)
        return false if affected.empty?

        target = normalize_version(version)

        affected.each do |aff|
          next unless affected_entry_relevant?(aff, repo_url)

          version_matched = false
          ranges = Array(aff["ranges"])
          semver_ranges, non_semver_ranges = ranges.partition { |r| r["type"] == "SEMVER" }

          versions = Array(aff["versions"])
          version_matched = true if versions.any? { |v| normalize_version(v.to_s) == target }

          version_matched = true if non_semver_ranges.any?

          matched_semver_range = T.let(false, T::Boolean)
          fix_found = T.let(false, T::Boolean)

          semver_ranges.each do |range|
            intervals(Array(range["events"])).each do |interval|
              result = in_interval_strict?(target, interval)
              next if result.nil?

              if result
                matched_semver_range = true
                fix_found = true if interval.fix.present?
              end
            end
          end

          version_matched ||= matched_semver_range

          next unless version_matched

          return true if fix_found

          non_semver_ranges.each do |range|
            return true if non_semver_fix_available?(target, range)
          end
        end

        false
      end
    end
  end
end

# <<< end: vulns/vulnerability.rb
# >>> linked: vulns/identify.rb
# typed: strict
# frozen_string_literal: true


# >>> linked: vulns/purl.rb
# typed: strict
# frozen_string_literal: true

module Homebrew
  module Vulns
    # A package URL per https://github.com/package-url/purl-spec.
    #
    # Minimal builder for the registry types Homebrew derives from formula
    # source URLs. Applies the spec's per-type name normalisation and RFC 3986
    # percent-encoding when serialised. Parsing, qualifiers and subpath are
    # intentionally omitted.
    class Purl
      sig { returns(String) }
      attr_reader :type, :name

      sig { returns(T.nilable(String)) }
      attr_reader :namespace, :version

      sig {
        params(type: String, name: String, namespace: T.nilable(String), version: T.nilable(String)).void
      }
      def initialize(type:, name:, namespace: nil, version: nil)
        raise ArgumentError, "type is required" if type.empty?
        raise ArgumentError, "name is required" if name.empty?

        @type = T.let(type.downcase.freeze, String)
        namespace = nil if namespace && namespace.empty?
        namespace, name = self.class.normalize(@type, namespace, name)
        @namespace = T.let(namespace && -namespace, T.nilable(String))
        @name = T.let(-name, String)
        version = nil if version && version.empty?
        @version = T.let(version && -version, T.nilable(String))
      end

      sig { returns(String) }
      def to_s
        purl = "pkg:#{@type}/"
        if @namespace
          purl << @namespace.split("/").reject(&:empty?).map { |s| self.class.encode(s) }.join("/")
          purl << "/"
        end
        purl << self.class.encode(@name)
        purl << "@#{self.class.encode(@version)}" if @version
        purl.freeze
      end

      sig { params(other: T.anything).returns(T::Boolean) }
      def ==(other)
        case other
        when Purl
          type == other.type && namespace == other.namespace &&
            name == other.name && version == other.version
        else false
        end
      end
      alias eql? ==

      sig { returns(Integer) }
      def hash
        [type, namespace, name, version].hash
      end

      # Percent-encode a single purl component. The spec permits the RFC 3986
      # unreserved set plus `:` unencoded; `+` for space is forbidden so
      # `URI.encode_www_form_component` is unsuitable.
      sig { params(component: String).returns(String) }
      def self.encode(component)
        component.b.gsub(/[^A-Za-z0-9\-._~:]/n) { |c| format("%%%02X", c.ord) }
      end

      # Per-type normalisation from purl-spec PURL-TYPES.rst for the types we emit.
      sig {
        params(type: String, namespace: T.nilable(String), name: String)
          .returns([T.nilable(String), String])
      }
      def self.normalize(type, namespace, name)
        case type
        when "pypi"
          [namespace, name.downcase.tr("_", "-")]
        when "hex"
          [namespace&.downcase, name.downcase]
        when "cpan"
          [namespace&.upcase, name]
        else
          [namespace, name]
        end
      end
    end
  end
end

# <<< end: vulns/purl.rb



module Homebrew
  module Vulns
    # Derives OSV.dev query keys (forge repo URL, release tag) from formula
    # source URLs. Shared between {Scanner} and the advisory-matching pipeline.
    module Identify
      TWO_SEGMENT_PATH = %r{/([^/]+/[^/]+)}
      private_constant :TWO_SEGMENT_PATH

      # GitLab supports nested subgroups (e.g. `xorg/lib/libx11`); the path is
      # bounded by `.git`, the `/-/` route marker, the legacy `/uploads/` and
      # `/wikis/` routes, or the end of the URL. Host-level `/-/` and `/api/`
      # routes are rejected via the leading negative lookahead.
      GITLAB_PATH = %r{/(?!-|api/)([^/]+(?:/[^/]+)+?)(?:\.git)?(?=/-/|/uploads/|/wikis/|/?\z)}
      private_constant :GITLAB_PATH

      FORGES = T.let(
        {
          "github.com"             => TWO_SEGMENT_PATH,
          "codeberg.org"           => TWO_SEGMENT_PATH,
          "gitlab.com"             => GITLAB_PATH,
          "gitlab.gnome.org"       => GITLAB_PATH,
          "gitlab.freedesktop.org" => GITLAB_PATH,
          "invent.kde.org"         => GITLAB_PATH,
        }.freeze,
        T::Hash[String, Regexp],
      )
      private_constant :FORGES

      TAG_PATTERNS = T.let(
        [
          %r{/archive/refs/tags/([^/]+)\.tar\.gz$},
          %r{/archive/refs/tags/([^/]+)\.zip$},
          %r{/archive/([^/]+)\.tar\.gz$},
          %r{/archive/([^/]+)\.zip$},
          %r{/releases/download/([^/]+)/},
          %r{/tarball/([^/]+)$},
        ].freeze,
        T::Array[Regexp],
      )
      private_constant :TAG_PATTERNS

      WAYBACK_PREFIX = %r{\Ahttps?://web\.archive\.org/web/\d+[a-z_*]*/}
      private_constant :WAYBACK_PREFIX

      # OSV.dev's GIT ecosystem indexes repository URLs case-sensitively but
      # normalises `github.com` paths to lowercase (GitHub itself is
      # case-insensitive). GitLab and Codeberg are case-sensitive so their
      # paths are preserved.
      LOWERCASE_PATH_HOSTS = ["github.com"].freeze
      private_constant :LOWERCASE_PATH_HOSTS

      sig { params(urls: T.nilable(String)).returns(T.nilable(String)) }
      def self.repo_url(*urls)
        urls.each do |url|
          next if url.nil?

          url = url.sub(WAYBACK_PREFIX, "")
          FORGES.each do |host, path_pattern|
            match = url.match(%r{\Ahttps?://#{Regexp.escape(host)}#{path_pattern}})
            next if match.nil?

            repo_path = T.must(match[1]).sub(/\.git$/, "")
            repo_path = repo_path.downcase if LOWERCASE_PATH_HOSTS.include?(host)
            return "https://#{host}/#{repo_path}"
          end
        end
        nil
      end

      sig { params(url: T.nilable(String)).returns(T.nilable(String)) }
      def self.tag(url)
        return if url.nil?

        TAG_PATTERNS.each do |pattern|
          match = url.match(pattern)
          return match[1] if match
        end
        nil
      end

      # `ecosystem` is the OSV.dev ecosystem identifier for `name`, or `"CPAN"`
      # for CPAN distributions (queried via CPANSA, not OSV).
      RegistryPackage = Struct.new(:ecosystem, :name, :version, :purl, keyword_init: true)

      ARCHIVE_EXTENSIONS = /\.(?:tar\.gz|tar\.bz2|tar\.xz|tgz|zip|gem|crate|tar|nupkg)\z/i
      private_constant :ARCHIVE_EXTENSIONS

      # Cabal package versions are dot-separated non-negative integers only.
      HACKAGE_PKGID = /\A(.+)-(\d+(?:\.\d+)*)\z/
      private_constant :HACKAGE_PKGID

      # Simplified from CPAN::DistnameInfo: greedy name, version is digits/
      # dots/underscores optionally `v`-prefixed. A -TRIAL suffix is stripped.
      # Does not handle the rare `_`-separated form (e.g. `libao-perl_0.03-1`);
      # no homebrew-core formula currently uses it.
      CPAN_DISTNAME = /\A(.+)-(v?\d[\d._]*)(?:-TRIAL\d*)?\z/
      private_constant :CPAN_DISTNAME

      # Recognise a `Gem::Platform` suffix by its OS token; the CPU token is
      # open-ended (riscv64, s390x, ppc64le, ...) so is matched generically.
      GEM_PLATFORM_SUFFIX = /
        -(?:
          java|jruby|truffleruby|dalvik|dotnet|mswin\d+(?:_\d+)?|
          \w+-
          (?:aix|cygwin|darwin|freebsd|linux|macruby|mingw\w*|mswin\d*|
             netbsd\w*|openbsd|bitrig|solaris|wasi)
          (?:[-_][\w.]+)?
        )\z
      /x
      private_constant :GEM_PLATFORM_SUFFIX

      sig { params(url: T.nilable(String)).returns(T.nilable(RegistryPackage)) }
      def self.registry_package(url)
        return if url.nil?

        ecosystem, purl = registry_purl(url)
        return if purl.nil?

        name = case purl.type
        when "maven" then "#{purl.namespace}:#{purl.name}"
        # OSV keys PyPI packages by their PEP 503 normalised name.
        when "pypi" then purl.name.gsub(/[-_.]+/, "-")
        # CPANSA is keyed on the distribution name alone, without the author.
        when "cpan" then purl.name
        else purl.namespace ? "#{purl.namespace}/#{purl.name}" : purl.name
        end
        RegistryPackage.new(ecosystem:, name:, version: purl.version, purl: purl.to_s).freeze
      end

      sig { params(url: String).returns(T.nilable([String, Purl])) }
      def self.registry_purl(url)
        basename = decode(File.basename(url)).sub(ARCHIVE_EXTENSIONS, "")

        case url
        when %r{\Ahttps://files\.pythonhosted\.org/packages/(?:[^/]+/){3}(?![^/]+\.whl\z)}
          # PEP 440 canonical versions contain no hyphen, so the last one delimits.
          name, _, version = basename.rpartition("-")
          return if name.empty?

          ["PyPI", Purl.new(type: "pypi", name:, version:)]
        when %r{\Ahttps://registry\.npmjs\.org/(?:((?:@|%40)[^/]+)/)?([^/@%][^/]*)/-/}
          namespace = Regexp.last_match(1)
          name = T.must(Regexp.last_match(2))
          namespace &&= "@#{decode(namespace).delete_prefix("@")}"
          name = decode(name)
          return unless (version = version_after_prefix(basename, name))

          ["npm", Purl.new(type: "npm", namespace:, name:, version:)]
        when %r{\Ahttps://static\.crates\.io/crates/([^/]+)/}
          name = decode(T.must(Regexp.last_match(1)))
          return unless (version = version_after_prefix(basename, name))

          ["crates.io", Purl.new(type: "cargo", name:, version:)]
        when %r{\Ahttps://rubygems\.org/(?:downloads|gems)/}
          name, version = gem_name_version(basename)
          return if name.nil?

          ["RubyGems", Purl.new(type: "gem", name:, version:)]
        when %r{\Ahttps://hackage\.haskell\.org/package/([^/]+)}
          match = T.must(Regexp.last_match(1)).match(HACKAGE_PKGID)
          return if match.nil?

          ["Hackage", Purl.new(type: "hackage", name: T.must(match[1]), version: match[2])]
        when %r{\Ahttps://repo\.hex\.pm/tarballs/}
          # Hex package names are `[a-z][a-z0-9_]*` so the first hyphen delimits.
          name, sep, version = basename.partition("-")
          return if sep.empty?

          ["Hex", Purl.new(type: "hex", name:, version:)]
        when %r{/authors/id/[A-Z]/[A-Z]{2}/([A-Z][A-Z0-9-]+)/}
          author = T.must(Regexp.last_match(1))
          match = basename.match(CPAN_DISTNAME)
          return if match.nil?

          ["CPAN", Purl.new(type: "cpan", namespace: author, name: T.must(match[1]), version: match[2])]
        # Maven Central only: OSV's bare `Maven` ecosystem is Central-scoped,
        # so third-party repositories (Google, fabricmc, jfrog, ...) are skipped.
        when %r{\Ahttps://repo1?\.maven\.(?:apache\.)?org/maven2/(.+)/([^/]+)/([^/]+)/\2-\3[.-][^/]+\z},
             %r{\Ahttps://search\.maven\.org/remotecontent\?filepath=(.+)/([^/]+)/([^/]+)/\2-\3[.-][^/]+\z}
          group_id = T.must(Regexp.last_match(1)).tr("/", ".")
          artifact_id = T.must(Regexp.last_match(2))
          version = Regexp.last_match(3)
          ["Maven", Purl.new(type: "maven", namespace: group_id, name: artifact_id, version:)]
        when %r{\Ahttps://(?:cran|cloud)\.r-project\.org/src/contrib/(?:Archive/[^/]+/)?([^/_]+)_([^/]+)\.tar\.gz\z}
          ["CRAN", Purl.new(type: "cran", name: T.must(Regexp.last_match(1)), version: Regexp.last_match(2))]
        when %r{\Ahttps://(?:api|www)\.nuget\.org/(?:v3-flatcontainer|api/v2/package)/([^/]+)/([^/]+)(?:/|\z)}
          ["NuGet", Purl.new(type: "nuget", name: T.must(Regexp.last_match(1)), version: Regexp.last_match(2))]
        end
      end

      # Percent-decode a URL path segment. Unlike `decode_www_form_component`
      # this leaves `+` alone and unlike `decode_uri_component` (missing from
      # Sorbet's stdlib RBI) it never raises on malformed input.
      sig { params(component: String).returns(String) }
      def self.decode(component)
        return component unless component.include?("%")

        component.b.gsub(/%[0-9A-Fa-f]{2}/) { |m| Integer(m[1, 2], 16).chr }
                 .force_encoding(component.encoding)
      end

      sig { params(basename: String, name: String).returns(T.nilable(String)) }
      def self.version_after_prefix(basename, name)
        prefix = "#{name}-"
        return unless basename.start_with?(prefix)

        version = basename[prefix.length..]
        version.presence
      end

      # Split a `.gem` basename into name and version, discarding any trailing
      # {Gem::Platform} suffix (e.g. `nokogiri-1.16.0-arm64-darwin-22`).
      sig { params(basename: String).returns([T.nilable(String), T.nilable(String)]) }
      def self.gem_name_version(basename)
        deplatformed = basename.sub(GEM_PLATFORM_SUFFIX, "")
        name, sep, version = deplatformed.rpartition("-")
        return [nil, nil] if sep.empty? || !version.match?(/\A\d[\w.]*\z/)

        [name, version]
      end
    end
  end
end

# <<< end: vulns/identify.rb

# Driver for the whole linked slice, driven by **inputs it did not choose** — the
# ratchet's copy of `homebrew/slice-driver/probes/adversarial-inputs.rb`.
#
# This is the tier's one permanent negative (`unsafe_program`). The probe's point
# is that the unrestricted-input program *is not type-safe*: `range_status` and
# `affects_version?` reach `ArgumentError` (from `Version.new("")`) and
# `TypeError` (from `Integer#[]`) on advisory shapes a caller can supply, and two
# of those are reachable from a schema-conformant record. A checker that
# certified this program would be unsound, so the recorded target is `false` and
# it must stay `false`.
#
# One row of the upstream probe is dropped: `V.new({ "id" => 5 })` raises through
# sorbet-runtime's `T.let`, whose message carries the **caller's file path** —
# process-dependent output, and the model does not enforce sigs, so the two
# executors disagree on it by construction (N38). The `TypeError` the probe is
# about is reached by the `ranges: [1]` row regardless.

def show(label)
  puts("#{label} => #{yield.inspect}")
rescue StandardError => e
  puts("#{label} => #{e.class}: #{e.message}")
end

V = Homebrew::Vulns::Vulnerability

def adv(affected)
  { "id" => "GHSA-probe", "affected" => affected }
end

PKG = { "ecosystem" => "Homebrew", "name" => "libexample" }

def eco_range(events)
  [{ "package" => PKG, "ranges" => [{ "type" => "ECOSYSTEM", "events" => events }] }]
end

def semver_range(events)
  [{ "package" => PKG, "ranges" => [{ "type" => "SEMVER", "events" => events }] }]
end

WELL_FORMED = adv(eco_range([{ "introduced" => "1.0" }, { "fixed" => "2.0" }])).freeze

puts("== control: a well-formed advisory")
show("range_status 1.5") { V.new(WELL_FORMED).range_status("Homebrew", "libexample", "1.5") }
show("range_status 2.5") { V.new(WELL_FORMED).range_status("Homebrew", "libexample", "2.5") }

puts("== the version string is an input (from the formula)")
show("version 'v'")     { V.new(WELL_FORMED).range_status("Homebrew", "libexample", "v") }
show("version ''")      { V.new(WELL_FORMED).range_status("Homebrew", "libexample", "") }
show("version 'HEAD'")  { V.new(WELL_FORMED).range_status("Homebrew", "libexample", "HEAD") }

puts("== the advisory is an input (from the network)")
show("ranges: [1]") do
  V.new(adv([{ "package" => PKG, "ranges" => [1] }]))
   .range_status("Homebrew", "libexample", "1.5")
end
show("ranges: ['x']") do
  V.new(adv([{ "package" => PKG, "ranges" => ["x"] }]))
   .range_status("Homebrew", "libexample", "1.5")
end
show("affected: [[1, 2]]") do
  V.new(adv([[1, 2]])).range_status("Homebrew", "libexample", "1.5")
end
show("empty fixed event") do
  V.new(adv(eco_range([{ "introduced" => "1.0" }, { "fixed" => "" }])))
   .range_status("Homebrew", "libexample", "1.5")
end
show("introduced: 'v'") do
  V.new(adv(eco_range([{ "introduced" => "v" }])))
   .range_status("Homebrew", "libexample", "1.5")
end
show("events: [{}]") do
  V.new(adv(eco_range([{}]))).range_status("Homebrew", "libexample", "1.5")
end
show("events: 'x'") do
  V.new(adv([{ "package" => PKG, "ranges" => [{ "type" => "ECOSYSTEM", "events" => "x" }] }]))
   .range_status("Homebrew", "libexample", "1.5")
end
show("versions: [nil]") do
  V.new(adv([{ "package" => PKG, "versions" => [nil] }]))
   .range_status("Homebrew", "libexample", "1.5")
end
show("no id at all")           { V.new({}).range_status("Homebrew", "libexample", "1.5") }
show("affects_version? empty fixed") do
  V.new(adv(semver_range([{ "introduced" => "1.0.0" }, { "fixed" => "" }])))
   .affects_version?("1.5.0")
end
