# Generated by ratchet/scripts/build_slice_rungs.py — do not edit, regenerate.
# boot stubs: difftest/tiers/tier0/rspec_harvest.py (SORBET_REQUIRE, BLANK_STUB,
#             PATHNAME_STEM_STUB, OUTPUT_STUB) + require "forwardable"
#             + BLANK_NIL_STUB (extend/blank/{nil_class,false_class}.rb)
# library:    2 file(s) linked from vulns/identify.rb; 0 external, 0 cycles
# driver:     ratchet/slice/drivers/identify.rb
require "sorbet-runtime"
class Module
  include T::Sig
end
require "pathname"
require "uri"
require "forwardable"

class Object
  sig { returns(T::Boolean) }
  def blank?
    respond_to?(:empty?) ? !!empty? : false
  end

  sig { returns(T::Boolean) }
  def present? = !blank?

  sig { returns(T.nilable(T.self_type)) }
  def presence = present? ? self : nil
end

class NilClass
  sig { returns(TrueClass) }
  def blank? = true

  sig { returns(FalseClass) }
  def present? = false
end

class FalseClass
  sig { returns(TrueClass) }
  def blank? = true

  sig { returns(FalseClass) }
  def present? = false
end

class Pathname
  sig { returns(String) }
  def stem
    File.basename(self, extname)
  end
end

module Utils
  module Output
    module Mixin
      # See difftest/implementation-notes.md N36: upstream `odebug` returns
      # early unless debug is enabled and otherwise writes to stderr, neither of
      # which is observable here.
      # The sig is upstream's, verbatim (`utils/output.rb:32`) — see N48: a stub
      # without one is a `missing-sig` row in `--fragment` for a method that *is*
      # annotated upstream, i.e. our bug rather than the slice's.
      sig { params(title: T.any(String, Exception), sput: T.anything, always_display: T::Boolean).void }
      def odebug(title, *sput, always_display: false)
        nil
      end
    end
  end
end
# Linked by ruby/linker. Do not edit — regenerate.
# platform: generic
# entries: vulns/identify.rb
# files: 2 (2 spliced, 0 thunked)
# >>> linked: vulns/identify.rb
# typed: strict
# frozen_string_literal: true


# >>> linked: vulns/purl.rb
# typed: strict
# frozen_string_literal: true

module Homebrew
  module Vulns
    # A package URL per https://github.com/package-url/purl-spec.
    #
    # Minimal builder for the registry types Homebrew derives from formula
    # source URLs. Applies the spec's per-type name normalisation and RFC 3986
    # percent-encoding when serialised. Parsing, qualifiers and subpath are
    # intentionally omitted.
    class Purl
      sig { returns(String) }
      attr_reader :type, :name

      sig { returns(T.nilable(String)) }
      attr_reader :namespace, :version

      sig {
        params(type: String, name: String, namespace: T.nilable(String), version: T.nilable(String)).void
      }
      def initialize(type:, name:, namespace: nil, version: nil)
        raise ArgumentError, "type is required" if type.empty?
        raise ArgumentError, "name is required" if name.empty?

        @type = T.let(type.downcase.freeze, String)
        namespace = nil if namespace && namespace.empty?
        namespace, name = self.class.normalize(@type, namespace, name)
        @namespace = T.let(namespace && -namespace, T.nilable(String))
        @name = T.let(-name, String)
        version = nil if version && version.empty?
        @version = T.let(version && -version, T.nilable(String))
      end

      sig { returns(String) }
      def to_s
        purl = "pkg:#{@type}/"
        if @namespace
          purl << @namespace.split("/").reject(&:empty?).map { |s| self.class.encode(s) }.join("/")
          purl << "/"
        end
        purl << self.class.encode(@name)
        purl << "@#{self.class.encode(@version)}" if @version
        purl.freeze
      end

      sig { params(other: T.anything).returns(T::Boolean) }
      def ==(other)
        case other
        when Purl
          type == other.type && namespace == other.namespace &&
            name == other.name && version == other.version
        else false
        end
      end
      alias eql? ==

      sig { returns(Integer) }
      def hash
        [type, namespace, name, version].hash
      end

      # Percent-encode a single purl component. The spec permits the RFC 3986
      # unreserved set plus `:` unencoded; `+` for space is forbidden so
      # `URI.encode_www_form_component` is unsuitable.
      sig { params(component: String).returns(String) }
      def self.encode(component)
        component.b.gsub(/[^A-Za-z0-9\-._~:]/n) { |c| format("%%%02X", c.ord) }
      end

      # Per-type normalisation from purl-spec PURL-TYPES.rst for the types we emit.
      sig {
        params(type: String, namespace: T.nilable(String), name: String)
          .returns([T.nilable(String), String])
      }
      def self.normalize(type, namespace, name)
        case type
        when "pypi"
          [namespace, name.downcase.tr("_", "-")]
        when "hex"
          [namespace&.downcase, name.downcase]
        when "cpan"
          [namespace&.upcase, name]
        else
          [namespace, name]
        end
      end
    end
  end
end

# <<< end: vulns/purl.rb



module Homebrew
  module Vulns
    # Derives OSV.dev query keys (forge repo URL, release tag) from formula
    # source URLs. Shared between {Scanner} and the advisory-matching pipeline.
    module Identify
      TWO_SEGMENT_PATH = %r{/([^/]+/[^/]+)}
      private_constant :TWO_SEGMENT_PATH

      # GitLab supports nested subgroups (e.g. `xorg/lib/libx11`); the path is
      # bounded by `.git`, the `/-/` route marker, the legacy `/uploads/` and
      # `/wikis/` routes, or the end of the URL. Host-level `/-/` and `/api/`
      # routes are rejected via the leading negative lookahead.
      GITLAB_PATH = %r{/(?!-|api/)([^/]+(?:/[^/]+)+?)(?:\.git)?(?=/-/|/uploads/|/wikis/|/?\z)}
      private_constant :GITLAB_PATH

      FORGES = T.let(
        {
          "github.com"             => TWO_SEGMENT_PATH,
          "codeberg.org"           => TWO_SEGMENT_PATH,
          "gitlab.com"             => GITLAB_PATH,
          "gitlab.gnome.org"       => GITLAB_PATH,
          "gitlab.freedesktop.org" => GITLAB_PATH,
          "invent.kde.org"         => GITLAB_PATH,
        }.freeze,
        T::Hash[String, Regexp],
      )
      private_constant :FORGES

      TAG_PATTERNS = T.let(
        [
          %r{/archive/refs/tags/([^/]+)\.tar\.gz$},
          %r{/archive/refs/tags/([^/]+)\.zip$},
          %r{/archive/([^/]+)\.tar\.gz$},
          %r{/archive/([^/]+)\.zip$},
          %r{/releases/download/([^/]+)/},
          %r{/tarball/([^/]+)$},
        ].freeze,
        T::Array[Regexp],
      )
      private_constant :TAG_PATTERNS

      WAYBACK_PREFIX = %r{\Ahttps?://web\.archive\.org/web/\d+[a-z_*]*/}
      private_constant :WAYBACK_PREFIX

      # OSV.dev's GIT ecosystem indexes repository URLs case-sensitively but
      # normalises `github.com` paths to lowercase (GitHub itself is
      # case-insensitive). GitLab and Codeberg are case-sensitive so their
      # paths are preserved.
      LOWERCASE_PATH_HOSTS = ["github.com"].freeze
      private_constant :LOWERCASE_PATH_HOSTS

      sig { params(urls: T.nilable(String)).returns(T.nilable(String)) }
      def self.repo_url(*urls)
        urls.each do |url|
          next if url.nil?

          url = url.sub(WAYBACK_PREFIX, "")
          FORGES.each do |host, path_pattern|
            match = url.match(%r{\Ahttps?://#{Regexp.escape(host)}#{path_pattern}})
            next if match.nil?

            repo_path = T.must(match[1]).sub(/\.git$/, "")
            repo_path = repo_path.downcase if LOWERCASE_PATH_HOSTS.include?(host)
            return "https://#{host}/#{repo_path}"
          end
        end
        nil
      end

      sig { params(url: T.nilable(String)).returns(T.nilable(String)) }
      def self.tag(url)
        return if url.nil?

        TAG_PATTERNS.each do |pattern|
          match = url.match(pattern)
          return match[1] if match
        end
        nil
      end

      # `ecosystem` is the OSV.dev ecosystem identifier for `name`, or `"CPAN"`
      # for CPAN distributions (queried via CPANSA, not OSV).
      RegistryPackage = Struct.new(:ecosystem, :name, :version, :purl, keyword_init: true)

      ARCHIVE_EXTENSIONS = /\.(?:tar\.gz|tar\.bz2|tar\.xz|tgz|zip|gem|crate|tar|nupkg)\z/i
      private_constant :ARCHIVE_EXTENSIONS

      # Cabal package versions are dot-separated non-negative integers only.
      HACKAGE_PKGID = /\A(.+)-(\d+(?:\.\d+)*)\z/
      private_constant :HACKAGE_PKGID

      # Simplified from CPAN::DistnameInfo: greedy name, version is digits/
      # dots/underscores optionally `v`-prefixed. A -TRIAL suffix is stripped.
      # Does not handle the rare `_`-separated form (e.g. `libao-perl_0.03-1`);
      # no homebrew-core formula currently uses it.
      CPAN_DISTNAME = /\A(.+)-(v?\d[\d._]*)(?:-TRIAL\d*)?\z/
      private_constant :CPAN_DISTNAME

      # Recognise a `Gem::Platform` suffix by its OS token; the CPU token is
      # open-ended (riscv64, s390x, ppc64le, ...) so is matched generically.
      GEM_PLATFORM_SUFFIX = /
        -(?:
          java|jruby|truffleruby|dalvik|dotnet|mswin\d+(?:_\d+)?|
          \w+-
          (?:aix|cygwin|darwin|freebsd|linux|macruby|mingw\w*|mswin\d*|
             netbsd\w*|openbsd|bitrig|solaris|wasi)
          (?:[-_][\w.]+)?
        )\z
      /x
      private_constant :GEM_PLATFORM_SUFFIX

      sig { params(url: T.nilable(String)).returns(T.nilable(RegistryPackage)) }
      def self.registry_package(url)
        return if url.nil?

        ecosystem, purl = registry_purl(url)
        return if purl.nil?

        name = case purl.type
        when "maven" then "#{purl.namespace}:#{purl.name}"
        # OSV keys PyPI packages by their PEP 503 normalised name.
        when "pypi" then purl.name.gsub(/[-_.]+/, "-")
        # CPANSA is keyed on the distribution name alone, without the author.
        when "cpan" then purl.name
        else purl.namespace ? "#{purl.namespace}/#{purl.name}" : purl.name
        end
        RegistryPackage.new(ecosystem:, name:, version: purl.version, purl: purl.to_s).freeze
      end

      sig { params(url: String).returns(T.nilable([String, Purl])) }
      def self.registry_purl(url)
        basename = decode(File.basename(url)).sub(ARCHIVE_EXTENSIONS, "")

        case url
        when %r{\Ahttps://files\.pythonhosted\.org/packages/(?:[^/]+/){3}(?![^/]+\.whl\z)}
          # PEP 440 canonical versions contain no hyphen, so the last one delimits.
          name, _, version = basename.rpartition("-")
          return if name.empty?

          ["PyPI", Purl.new(type: "pypi", name:, version:)]
        when %r{\Ahttps://registry\.npmjs\.org/(?:((?:@|%40)[^/]+)/)?([^/@%][^/]*)/-/}
          namespace = Regexp.last_match(1)
          name = T.must(Regexp.last_match(2))
          namespace &&= "@#{decode(namespace).delete_prefix("@")}"
          name = decode(name)
          return unless (version = version_after_prefix(basename, name))

          ["npm", Purl.new(type: "npm", namespace:, name:, version:)]
        when %r{\Ahttps://static\.crates\.io/crates/([^/]+)/}
          name = decode(T.must(Regexp.last_match(1)))
          return unless (version = version_after_prefix(basename, name))

          ["crates.io", Purl.new(type: "cargo", name:, version:)]
        when %r{\Ahttps://rubygems\.org/(?:downloads|gems)/}
          name, version = gem_name_version(basename)
          return if name.nil?

          ["RubyGems", Purl.new(type: "gem", name:, version:)]
        when %r{\Ahttps://hackage\.haskell\.org/package/([^/]+)}
          match = T.must(Regexp.last_match(1)).match(HACKAGE_PKGID)
          return if match.nil?

          ["Hackage", Purl.new(type: "hackage", name: T.must(match[1]), version: match[2])]
        when %r{\Ahttps://repo\.hex\.pm/tarballs/}
          # Hex package names are `[a-z][a-z0-9_]*` so the first hyphen delimits.
          name, sep, version = basename.partition("-")
          return if sep.empty?

          ["Hex", Purl.new(type: "hex", name:, version:)]
        when %r{/authors/id/[A-Z]/[A-Z]{2}/([A-Z][A-Z0-9-]+)/}
          author = T.must(Regexp.last_match(1))
          match = basename.match(CPAN_DISTNAME)
          return if match.nil?

          ["CPAN", Purl.new(type: "cpan", namespace: author, name: T.must(match[1]), version: match[2])]
        # Maven Central only: OSV's bare `Maven` ecosystem is Central-scoped,
        # so third-party repositories (Google, fabricmc, jfrog, ...) are skipped.
        when %r{\Ahttps://repo1?\.maven\.(?:apache\.)?org/maven2/(.+)/([^/]+)/([^/]+)/\2-\3[.-][^/]+\z},
             %r{\Ahttps://search\.maven\.org/remotecontent\?filepath=(.+)/([^/]+)/([^/]+)/\2-\3[.-][^/]+\z}
          group_id = T.must(Regexp.last_match(1)).tr("/", ".")
          artifact_id = T.must(Regexp.last_match(2))
          version = Regexp.last_match(3)
          ["Maven", Purl.new(type: "maven", namespace: group_id, name: artifact_id, version:)]
        when %r{\Ahttps://(?:cran|cloud)\.r-project\.org/src/contrib/(?:Archive/[^/]+/)?([^/_]+)_([^/]+)\.tar\.gz\z}
          ["CRAN", Purl.new(type: "cran", name: T.must(Regexp.last_match(1)), version: Regexp.last_match(2))]
        when %r{\Ahttps://(?:api|www)\.nuget\.org/(?:v3-flatcontainer|api/v2/package)/([^/]+)/([^/]+)(?:/|\z)}
          ["NuGet", Purl.new(type: "nuget", name: T.must(Regexp.last_match(1)), version: Regexp.last_match(2))]
        end
      end

      # Percent-decode a URL path segment. Unlike `decode_www_form_component`
      # this leaves `+` alone and unlike `decode_uri_component` (missing from
      # Sorbet's stdlib RBI) it never raises on malformed input.
      sig { params(component: String).returns(String) }
      def self.decode(component)
        return component unless component.include?("%")

        component.b.gsub(/%[0-9A-Fa-f]{2}/) { |m| Integer(m[1, 2], 16).chr }
                 .force_encoding(component.encoding)
      end

      sig { params(basename: String, name: String).returns(T.nilable(String)) }
      def self.version_after_prefix(basename, name)
        prefix = "#{name}-"
        return unless basename.start_with?(prefix)

        version = basename[prefix.length..]
        version.presence
      end

      # Split a `.gem` basename into name and version, discarding any trailing
      # {Gem::Platform} suffix (e.g. `nokogiri-1.16.0-arm64-darwin-22`).
      sig { params(basename: String).returns([T.nilable(String), T.nilable(String)]) }
      def self.gem_name_version(basename)
        deplatformed = basename.sub(GEM_PLATFORM_SUFFIX, "")
        name, sep, version = deplatformed.rpartition("-")
        return [nil, nil] if sep.empty? || !version.match?(/\A\d[\w.]*\z/)

        [name, version]
      end
    end
  end
end

# <<< end: vulns/identify.rb

# Driver for `vulns/identify.rb` — the OSV query-key derivation: given a formula
# source URL, which forge repository is it, which release tag, and which package
# registry (with a purl) does it come from.
#
# The file is a table of regexes and a `case/when` over them, so the driver is a
# table of URLs: one per branch that the file can take, plus the near-misses that
# have to *not* match. A `Purl` and a `RegistryPackage` both carry an address in
# their default `inspect`, so every observation renders through `to_s` or a field
# (N38: process-independent output).

def show(label)
  puts("#{label} => #{yield.inspect}")
rescue StandardError => e
  puts("#{label} => #{e.class}: #{e.message}")
end

I = Homebrew::Vulns::Identify

puts("== repo_url: the forge, from any of the URLs a formula carries")
[
  "https://github.com/Example/LibExample/archive/refs/tags/v1.4.2.tar.gz",
  "https://codeberg.org/Example/LibExample/archive/v1.4.2.tar.gz",
  "https://gitlab.com/example/libexample/-/archive/1.4.2/libexample-1.4.2.tar.gz",
  "https://gitlab.gnome.org/GNOME/glib/-/archive/2.80.0/glib-2.80.0.tar.gz",
  "https://gitlab.freedesktop.org/xorg/lib/libx11/-/archive/1.8/libx11-1.8.tar.gz",
  "https://invent.kde.org/frameworks/kconfig.git",
  "https://web.archive.org/web/20200101000000/https://github.com/example/libexample/archive/v1.0.tar.gz",
  "https://gitlab.com/-/snippets/1",          # a host-level route, rejected
  "https://gitlab.com/api/v4/projects/1",     # ditto
  "https://example.test/tarballs/libexample-1.4.2.tar.gz",
].each { |u| show("  #{u}") { I.repo_url(u) } }
show("  several urls, first match wins") do
  I.repo_url(nil, "https://example.test/x.tar.gz", "https://github.com/a/b/archive/v1.tar.gz")
end
show("  no urls") { I.repo_url }

puts
puts("== tag: the release tag, by the six patterns that name one")
[
  "https://github.com/example/libexample/archive/refs/tags/v1.4.2.tar.gz",
  "https://github.com/example/libexample/archive/refs/tags/v1.4.2.zip",
  "https://github.com/example/libexample/archive/1.4.2.tar.gz",
  "https://github.com/example/libexample/archive/1.4.2.zip",
  "https://github.com/example/libexample/releases/download/v1.4.2/libexample.tar.gz",
  "https://github.com/example/libexample/tarball/v1.4.2",
  "https://example.test/libexample-1.4.2.tar.gz",
  nil,
].each { |u| show("  #{u.inspect}") { I.tag(u) } }

puts
puts("== registry_purl: the package registry, and the purl for it")
[
  "https://files.pythonhosted.org/packages/source/r/requests/requests-2.31.0.tar.gz",
  "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz",
  "https://registry.npmjs.org/@babel/core/-/core-7.24.0.tgz",
  "https://static.crates.io/crates/ripgrep/ripgrep-14.1.0.crate",
  "https://rubygems.org/downloads/nokogiri-1.16.0.gem",
  "https://rubygems.org/downloads/nokogiri-1.16.0-arm64-darwin.gem",
  "https://hackage.haskell.org/package/pandoc-3.1.11/pandoc-3.1.11.tar.gz",
  "https://repo.hex.pm/tarballs/phoenix-1.7.10.tar",
  "https://cpan.metacpan.org/authors/id/M/MS/MSHELOR/Digest-SHA-6.04.tar.gz",
  "https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.14.1/log4j-core-2.14.1.jar",
  "https://cran.r-project.org/src/contrib/jsonlite_1.8.8.tar.gz",
  "https://api.nuget.org/v3-flatcontainer/newtonsoft.json/13.0.3/newtonsoft.json.13.0.3.nupkg",
  "https://example.test/tarballs/libexample-1.4.2.tar.gz",
  "https://files.pythonhosted.org/packages/py3/r/requests/requests-2.31.0-py3-none-any.whl",
].each do |u|
  show("  #{u}") do
    reg = I.registry_purl(u)
    reg.nil? ? nil : [reg[0], reg[1].to_s]
  end
end

puts
puts("== registry_package: the OSV-facing name, per ecosystem's own rule")
[
  "https://files.pythonhosted.org/packages/source/z/zope.interface/zope.interface-6.1.tar.gz",
  "https://registry.npmjs.org/@babel/core/-/core-7.24.0.tgz",
  "https://cpan.metacpan.org/authors/id/M/MS/MSHELOR/Digest-SHA-6.04.tar.gz",
  "https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.14.1/log4j-core-2.14.1.jar",
  "https://rubygems.org/downloads/nokogiri-1.16.0.gem",
  nil,
].each do |u|
  show("  #{u.inspect}") do
    pkg = I.registry_package(u)
    pkg.nil? ? nil : [pkg.ecosystem, pkg.name, pkg.version, pkg.purl]
  end
end

puts
puts("== the helpers the table leans on")
show("decode plain")     { I.decode("lodash-4.17.21") }
show("decode percent")   { I.decode("%40babel%2Fcore") }
show("decode malformed") { I.decode("100%") }
show("version_after_prefix hit")  { I.version_after_prefix("lodash-4.17.21", "lodash") }
show("version_after_prefix miss") { I.version_after_prefix("lodash-4.17.21", "underscore") }
show("gem_name_version")          { I.gem_name_version("nokogiri-1.16.0-arm64-darwin-22") }
show("gem_name_version no ver")   { I.gem_name_version("nokogiri") }
