/-! Instance selector projection of RubyCore/Generated/CRubyNames.lean (Ruby 4.0.5).
books/Books/TypeSoundness/Conformance/Names/NativePrefix.lean kernel-checks coverage of every modeled native selector.
The checker imports only this data, never the interpreter. -/
namespace Checker

def nativeInstanceNames : List String := [
  "feed", "next_values", "peek", "peek_values", "rewind", "with_index", "with_object", "tag", "value",
  "!", "!=", "!~", "%", "&", "*", "**",
  "+", "+@", "-", "-@", "/", "<", "<<",
  "<=", "<=>", "==", "===", "=~", ">", ">=",
  ">>", "Array", "Complex", "Float", "Hash", "Integer", "Pathname",
  "Rational", "String", "[]", "[]=", "^", "__callee__", "__dir__",
  "__id__", "__method__", "__send__", "`", "abort", "abs", "abs2",
  "absolute?", "add_trailing_separator", "advise", "alias_method", "all?", "allbits?", "allocate",
  "ancestors", "angle", "any?", "anybits?", "append", "append_as_bytes", "append_features",
  "arg", "args", "arity", "ascend", "ascii_only?", "assoc", "at",
  "at_exit", "atime", "attached_object", "attr", "attr_accessor", "attr_reader", "attr_writer",
  "autoclose=", "autoclose?", "autoload", "autoload?", "b", "backtrace", "backtrace_locations",
  "basename", "begin", "between?", "binding", "binmode", "binmode?", "binread",
  "binwrite", "birthtime", "bit_length", "block_given?", "blockdev?", "bsearch", "bsearch_index",
  "byteindex", "byterindex", "bytes", "bytesize", "byteslice", "bytesplice", "call",
  "caller", "caller_locations", "capitalize", "capitalize!", "casecmp", "casecmp?", "catch",
  "cause", "ceil", "ceildiv", "center", "chain", "chardev?", "chars",
  "chdir", "children", "chmod", "chomp", "chomp!", "chop", "chop!",
  "chop_basename", "chown", "chr", "chunk", "chunk_while", "clamp", "class",
  "class_eval", "class_exec", "class_variable_defined?", "class_variable_get", "class_variable_set", "class_variables", "cleanpath",
  "cleanpath_aggressive", "cleanpath_conservative", "clear", "clone", "close", "close_on_exec=", "close_on_exec?",
  "close_read", "close_write", "closed?", "codepoints", "coerce", "collect", "collect!",
  "collect_concat", "combination", "compact", "compact!", "compare_by_identity", "compare_by_identity?", "concat",
  "conj", "conjugate", "const_added", "const_defined?", "const_get", "const_missing", "const_set",
  "const_source_location", "constants", "count", "cover?", "crypt", "ctime", "curry",
  "cycle", "deconstruct", "deconstruct_keys", "dedup", "default", "default=", "default_proc",
  "default_proc=", "define_method", "define_singleton_method", "del_trailing_separator", "delete", "delete!", "delete_at",
  "delete_if", "delete_prefix", "delete_prefix!", "delete_suffix", "delete_suffix!", "denominator", "deprecate_constant",
  "descend", "detailed_message", "detect", "difference", "dig", "digits", "directory?",
  "dirname", "display", "div", "divmod", "downcase", "downcase!", "downto",
  "drop", "drop_while", "dump", "dup", "each", "each_byte", "each_char",
  "each_child", "each_codepoint", "each_cons", "each_entry", "each_filename", "each_grapheme_cluster", "each_index",
  "each_key", "each_line", "each_pair", "each_slice", "each_value", "each_with_index", "each_with_object",
  "empty?", "encode", "encode!", "encoding", "end", "end_with?", "entries",
  "enum_for", "eof", "eof?", "eql?", "equal?", "eval", "even?",
  "except", "exception", "exclude_end?", "exec", "executable?", "executable_real?", "exist?",
  "exit", "exit!", "exit_value", "expand_path", "extend", "extend_object", "extended",
  "external_encoding", "extname", "fail", "fcntl", "fdatasync", "fdiv", "fetch",
  "fetch_values", "file?", "fileno", "fill", "filter", "filter!", "filter_map",
  "find", "find_all", "find_index", "finite?", "first", "flat_map", "flatten",
  "flatten!", "flock", "floor", "flush", "fnmatch", "fnmatch?", "force_encoding",
  "fork", "format", "freeze", "frozen?", "fsync", "ftype", "full_message",
  "gcd", "gcdlcm", "gem", "gem_original_require", "getbyte", "getc", "gets",
  "glob", "global_variables", "grapheme_clusters", "grep", "grep_v", "group_by", "grpowned?",
  "gsub", "gsub!", "has_key?", "has_trailing_separator?", "has_value?", "hash", "hex",
  "i", "id2name", "identical?", "imag", "imaginary", "include", "include?",
  "included", "included_modules", "index", "infinite?", "inherited", "initialize", "initialize_clone",
  "initialize_copy", "initialize_dup", "inject", "insert", "inspect", "instance_eval", "instance_exec",
  "instance_method", "instance_methods", "instance_of?", "instance_variable_defined?", "instance_variable_get", "instance_variable_set", "instance_variables",
  "instance_variables_to_inspect", "integer?", "intern", "internal_encoding", "intersect?", "intersection", "invert",
  "ioctl", "is_a?", "isatty", "iterator?", "itself", "join", "keep_if",
  "key", "key?", "keys", "kind_of?", "lambda", "lambda?", "last",
  "lazy", "lchmod", "lchown", "lcm", "left", "length", "lineno",
  "lineno=", "lines", "ljust", "load", "local_variables", "loop", "lstat",
  "lstrip", "lstrip!", "lutime", "magnitude", "make_link", "make_symlink", "map",
  "map!", "marshal_dump", "marshal_load", "match", "match?", "max", "max_by",
  "member?", "merge", "merge!", "message", "method", "method_added", "method_defined?",
  "method_missing", "method_removed", "method_undefined", "methods", "min", "min_by", "minmax",
  "minmax_by", "mkdir", "mkpath", "module_eval", "module_exec", "module_function", "modulo",
  "mountpoint?", "mtime", "name", "nan?", "negative?", "new", "next",
  "next!", "next_float", "nil?", "nobits?", "none?", "nonzero?", "numerator",
  "object_id", "oct", "odd?", "one?", "open", "opendir", "ord",
  "overlap?", "owned?", "p", "pack", "parameters", "parent", "partition",
  "path", "permutation", "phase", "pid", "pipe?", "plus", "polar",
  "pop", "pos", "pos=", "positive?", "pow", "pp", "pread",
  "pred", "prepend", "prepend_features", "prepend_prefix", "prepended", "prev_float", "print",
  "printf", "private", "private_call?", "private_class_method", "private_constant", "private_instance_methods", "private_method_defined?",
  "private_methods", "proc", "product", "protected", "protected_instance_methods", "protected_method_defined?", "protected_methods",
  "public", "public_class_method", "public_constant", "public_instance_method", "public_instance_methods", "public_method", "public_method_defined?",
  "public_methods", "public_send", "push", "putc", "puts", "pwrite", "quo",
  "raise", "rand", "rassoc", "rationalize", "read", "read_nonblock", "readable?",
  "readable_real?", "readbyte", "readchar", "readline", "readlines", "readlink", "readpartial",
  "real", "real?", "realdirpath", "realpath", "reason", "receiver", "rect",
  "rectangular", "reduce", "refine", "refinements", "rehash", "reject", "reject!",
  "relative?", "relative_path_from", "remainder", "remove_class_variable", "remove_const", "remove_instance_variable", "remove_method",
  "rename", "reopen", "repeated_combination", "repeated_permutation", "replace", "require", "require_relative",
  "respond_to?", "respond_to_missing?", "result", "reverse", "reverse!", "reverse_each", "rfind",
  "rindex", "rjust", "rmdir", "rmtree", "root?", "rotate", "rotate!",
  "round", "rpartition", "rstrip", "rstrip!", "ruby2_keywords", "same_paths?", "sample",
  "scan", "scrub", "scrub!", "seek", "select", "select!", "send",
  "set_backtrace", "set_encoding", "set_encoding_by_bom", "set_temporary_name", "set_trace_func", "setbyte", "setgid?",
  "setuid?", "shift", "shuffle", "shuffle!", "singleton_class", "singleton_class?", "singleton_method",
  "singleton_method_added", "singleton_method_removed", "singleton_method_undefined", "singleton_methods", "size", "size?", "sleep",
  "slice", "slice!", "slice_after", "slice_before", "slice_when", "socket?", "sort",
  "sort!", "sort_by", "sort_by!", "source_location", "spawn", "split", "split_names",
  "sprintf", "squeeze", "squeeze!", "srand", "start_with?", "stat", "state",
  "step", "sticky?", "store", "strip", "strip!", "sub", "sub!",
  "sub_ext", "subclasses", "succ", "succ!", "sum", "superclass", "swapcase",
  "swapcase!", "symlink?", "sync", "sync=", "syscall", "sysopen", "sysread",
  "sysseek", "system", "syswrite", "take", "take_while", "tally", "tap",
  "tell", "test", "then", "throw", "timeout", "timeout=", "times",
  "to_a", "to_ary", "to_c", "to_enum", "to_f", "to_h", "to_hash",
  "to_i", "to_int", "to_io", "to_path", "to_proc", "to_r", "to_s",
  "to_set", "to_str", "to_sym", "tr", "tr!", "tr_s", "tr_s!",
  "trace_var", "transform_keys", "transform_keys!", "transform_values", "transform_values!", "transpose", "trap",
  "truncate", "tty?", "undef_method", "undefined_instance_methods", "undump", "ungetbyte", "ungetc",
  "unicode_normalize", "unicode_normalize!", "unicode_normalized?", "union", "uniq", "uniq!", "unlink",
  "unpack", "unpack1", "unshift", "untrace_var", "upcase", "upcase!", "update",
  "upto", "using", "utime", "valid_encoding?", "value?", "values", "values_at",
  "wait", "wait_priority", "wait_readable", "wait_writable", "warn", "world_readable?", "world_writable?",
  "writable?", "writable_real?", "write", "write_nonblock", "yield", "yield_self", "zero?",
  "zip", "|", "~"
]

/-- Sufficient for any inherited native prefix; own calls still use their empty prefix.
This deliberately declines inherited native selector names until a narrower prefix guard. -/
def nativeInstanceFreeB (name : String) : Bool := !nativeInstanceNames.contains name

end Checker
