/-
GENERATED from the CRuby oracle (ruby 4.0.5) by
`scripts/gen_cruby_names.rb` — do not hand-edit. Regenerate when the
oracle version bumps.

Purpose (dispatch fidelity, not behavior): the L0 model implements only a
slice of each core class, but lookup must know which names EXIST in CRuby
so that (a) an unmodeled builtin that would shadow a user method on Object
gates as Unsupported instead of mis-dispatching, and (b) a genuine
lookup-total-miss can be answered with a real NoMethodError.

Modules our L0 ancestors chain omits are folded into the nearest class
below them: Kernel→Object, Comparable→String/Symbol/Integer/Float,
Numeric→Integer/Float, Enumerable→Array/Hash.
-/
namespace RubyCore

/-- Method names each bootstrap class defines directly in CRuby
    (instance_methods(false) ∪ private_instance_methods(false), modules
    folded as above). -/
def crubyMethodNames : List (String × List String) := [
  ("BasicObject", [
    "!", "!=", "==", "__id__", "__send__", "equal?", "initialize", "instance_eval",
    "instance_exec", "method_missing", "singleton_method_added", "singleton_method_removed", "singleton_method_undefined"
  ]),
  ("Object", [
    "!~", "<=>", "===", "Array", "Complex", "Float", "Hash", "Integer",
    "Pathname", "Rational", "String", "__callee__", "__dir__", "__method__", "`", "abort",
    "at_exit", "autoload", "autoload?", "binding", "block_given?", "caller", "caller_locations", "catch",
    "class", "clone", "define_method", "define_singleton_method", "display", "dup", "enum_for", "eql?",
    "eval", "exec", "exit", "exit!", "extend", "fail", "fork", "format",
    "freeze", "frozen?", "gem", "gem_original_require", "gets", "global_variables", "hash", "include",
    "initialize_clone", "initialize_copy", "initialize_dup", "inspect", "instance_of?", "instance_variable_defined?", "instance_variable_get", "instance_variable_set",
    "instance_variables", "instance_variables_to_inspect", "is_a?", "iterator?", "itself", "kind_of?", "lambda", "load",
    "local_variables", "loop", "method", "methods", "nil?", "object_id", "open", "p",
    "pp", "print", "printf", "private", "private_methods", "proc", "protected_methods", "public",
    "public_method", "public_methods", "public_send", "putc", "puts", "raise", "rand", "readline",
    "readlines", "remove_instance_variable", "require", "require_relative", "respond_to?", "respond_to_missing?", "ruby2_keywords", "select",
    "send", "set_trace_func", "singleton_class", "singleton_method", "singleton_methods", "sleep", "spawn", "sprintf",
    "srand", "syscall", "system", "tap", "test", "then", "throw", "to_enum",
    "to_s", "trace_var", "trap", "untrace_var", "using", "warn", "yield_self"
  ]),
  ("Module", [
    "<", "<=", "<=>", "==", "===", ">", ">=", "alias_method",
    "ancestors", "append_features", "attr", "attr_accessor", "attr_reader", "attr_writer", "autoload", "autoload?",
    "class_eval", "class_exec", "class_variable_defined?", "class_variable_get", "class_variable_set", "class_variables", "const_added", "const_defined?",
    "const_get", "const_missing", "const_set", "const_source_location", "constants", "define_method", "deprecate_constant", "extend_object",
    "extended", "freeze", "include", "include?", "included", "included_modules", "initialize", "initialize_clone",
    "inspect", "instance_method", "instance_methods", "method_added", "method_defined?", "method_removed", "method_undefined", "module_eval",
    "module_exec", "module_function", "name", "prepend", "prepend_features", "prepended", "private", "private_class_method",
    "private_constant", "private_instance_methods", "private_method_defined?", "protected", "protected_instance_methods", "protected_method_defined?", "public", "public_class_method",
    "public_constant", "public_instance_method", "public_instance_methods", "public_method_defined?", "refine", "refinements", "remove_class_variable", "remove_const",
    "remove_method", "ruby2_keywords", "set_temporary_name", "singleton_class?", "to_s", "undef_method", "undefined_instance_methods", "using"
  ]),
  ("Class", [
    "allocate", "attached_object", "inherited", "initialize", "new", "subclasses", "superclass"
  ]),
  ("NilClass", [
    "&", "===", "=~", "^", "inspect", "nil?", "rationalize", "to_a",
    "to_c", "to_f", "to_h", "to_i", "to_r", "to_s", "|"
  ]),
  ("TrueClass", [
    "&", "===", "^", "inspect", "to_s", "|"
  ]),
  ("FalseClass", [
    "&", "===", "^", "inspect", "to_s", "|"
  ]),
  ("Integer", [
    "%", "&", "*", "**", "+", "+@", "-", "-@",
    "/", "<", "<<", "<=", "<=>", "==", "===", ">",
    ">=", ">>", "[]", "^", "abs", "abs2", "allbits?", "angle",
    "anybits?", "arg", "between?", "bit_length", "ceil", "ceildiv", "chr", "clamp",
    "clone", "coerce", "conj", "conjugate", "denominator", "digits", "div", "divmod",
    "downto", "dup", "eql?", "even?", "fdiv", "finite?", "floor", "gcd",
    "gcdlcm", "i", "imag", "imaginary", "infinite?", "inspect", "integer?", "lcm",
    "magnitude", "modulo", "negative?", "next", "nobits?", "nonzero?", "numerator", "odd?",
    "ord", "phase", "polar", "positive?", "pow", "pred", "quo", "rationalize",
    "real", "real?", "rect", "rectangular", "remainder", "round", "singleton_method_added", "size",
    "step", "succ", "times", "to_c", "to_f", "to_i", "to_int", "to_r",
    "to_s", "truncate", "upto", "zero?", "|", "~"
  ]),
  ("Float", [
    "%", "*", "**", "+", "+@", "-", "-@", "/",
    "<", "<=", "<=>", "==", "===", ">", ">=", "abs",
    "abs2", "angle", "arg", "between?", "ceil", "clamp", "clone", "coerce",
    "conj", "conjugate", "denominator", "div", "divmod", "dup", "eql?", "fdiv",
    "finite?", "floor", "hash", "i", "imag", "imaginary", "infinite?", "inspect",
    "integer?", "magnitude", "modulo", "nan?", "negative?", "next_float", "nonzero?", "numerator",
    "phase", "polar", "positive?", "prev_float", "quo", "rationalize", "real", "real?",
    "rect", "rectangular", "remainder", "round", "singleton_method_added", "step", "to_c", "to_f",
    "to_i", "to_int", "to_r", "to_s", "truncate", "zero?"
  ]),
  ("Rational", [
    "%", "*", "**", "+", "+@", "-", "-@", "/",
    "<", "<=", "<=>", "==", ">", ">=", "abs", "abs2",
    "angle", "arg", "between?", "ceil", "clamp", "clone", "coerce", "conj",
    "conjugate", "denominator", "div", "divmod", "dup", "eql?", "fdiv", "finite?",
    "floor", "hash", "i", "imag", "imaginary", "infinite?", "inspect", "integer?",
    "magnitude", "marshal_dump", "modulo", "negative?", "nonzero?", "numerator", "phase", "polar",
    "positive?", "quo", "rationalize", "real", "real?", "rect", "rectangular", "remainder",
    "round", "singleton_method_added", "step", "to_c", "to_f", "to_i", "to_int", "to_r",
    "to_s", "truncate", "zero?"
  ]),
  ("Complex", [
    "%", "*", "**", "+", "+@", "-", "-@", "/",
    "<", "<=", "<=>", "==", ">", ">=", "abs", "abs2",
    "angle", "arg", "between?", "ceil", "clamp", "clone", "coerce", "conj",
    "conjugate", "denominator", "div", "divmod", "dup", "eql?", "fdiv", "finite?",
    "floor", "hash", "i", "imag", "imaginary", "infinite?", "inspect", "integer?",
    "magnitude", "marshal_dump", "modulo", "negative?", "nonzero?", "numerator", "phase", "polar",
    "positive?", "quo", "rationalize", "real", "real?", "rect", "rectangular", "remainder",
    "round", "singleton_method_added", "step", "to_c", "to_f", "to_i", "to_int", "to_r",
    "to_s", "truncate", "zero?"
  ]),
  ("Enumerator", [
    "+", "all?", "any?", "chain", "chunk", "chunk_while", "collect", "collect_concat",
    "compact", "count", "cycle", "detect", "drop", "drop_while", "each", "each_cons",
    "each_entry", "each_slice", "each_with_index", "each_with_object", "entries", "feed", "filter", "filter_map",
    "find", "find_all", "find_index", "first", "flat_map", "grep", "grep_v", "group_by",
    "include?", "initialize", "initialize_copy", "inject", "inspect", "lazy", "map", "max",
    "max_by", "member?", "min", "min_by", "minmax", "minmax_by", "next", "next_values",
    "none?", "one?", "partition", "peek", "peek_values", "reduce", "reject", "reverse_each",
    "rewind", "select", "size", "slice_after", "slice_before", "slice_when", "sort", "sort_by",
    "sum", "take", "take_while", "tally", "to_a", "to_h", "to_set", "uniq",
    "with_index", "with_object", "zip"
  ]),
  ("Enumerator::Generator", [
    "all?", "any?", "chain", "chunk", "chunk_while", "collect", "collect_concat", "compact",
    "count", "cycle", "detect", "drop", "drop_while", "each", "each_cons", "each_entry",
    "each_slice", "each_with_index", "each_with_object", "entries", "filter", "filter_map", "find", "find_all",
    "find_index", "first", "flat_map", "grep", "grep_v", "group_by", "include?", "initialize",
    "initialize_copy", "inject", "lazy", "map", "max", "max_by", "member?", "min",
    "min_by", "minmax", "minmax_by", "none?", "one?", "partition", "reduce", "reject",
    "reverse_each", "select", "slice_after", "slice_before", "slice_when", "sort", "sort_by", "sum",
    "take", "take_while", "tally", "to_a", "to_h", "to_set", "uniq", "zip"
  ]),
  ("Enumerator::Yielder", [
    "<<", "initialize", "to_proc", "yield"
  ]),
  ("Enumerator::Chain", [
    "+", "all?", "any?", "chain", "chunk", "chunk_while", "collect", "collect_concat",
    "compact", "count", "cycle", "detect", "drop", "drop_while", "each", "each_cons",
    "each_entry", "each_slice", "each_with_index", "each_with_object", "entries", "feed", "filter", "filter_map",
    "find", "find_all", "find_index", "first", "flat_map", "grep", "grep_v", "group_by",
    "include?", "initialize", "initialize_copy", "inject", "inspect", "lazy", "map", "max",
    "max_by", "member?", "min", "min_by", "minmax", "minmax_by", "next", "next_values",
    "none?", "one?", "partition", "peek", "peek_values", "reduce", "reject", "reverse_each",
    "rewind", "select", "size", "slice_after", "slice_before", "slice_when", "sort", "sort_by",
    "sum", "take", "take_while", "tally", "to_a", "to_h", "to_set", "uniq",
    "with_index", "with_object", "zip"
  ]),
  ("String", [
    "%", "*", "+", "+@", "-@", "<", "<<", "<=",
    "<=>", "==", "===", "=~", ">", ">=", "[]", "[]=",
    "append_as_bytes", "ascii_only?", "b", "between?", "byteindex", "byterindex", "bytes", "bytesize",
    "byteslice", "bytesplice", "capitalize", "capitalize!", "casecmp", "casecmp?", "center", "chars",
    "chomp", "chomp!", "chop", "chop!", "chr", "clamp", "clear", "codepoints",
    "concat", "count", "crypt", "dedup", "delete", "delete!", "delete_prefix", "delete_prefix!",
    "delete_suffix", "delete_suffix!", "downcase", "downcase!", "dump", "dup", "each_byte", "each_char",
    "each_codepoint", "each_grapheme_cluster", "each_line", "empty?", "encode", "encode!", "encoding", "end_with?",
    "eql?", "force_encoding", "freeze", "getbyte", "grapheme_clusters", "gsub", "gsub!", "hash",
    "hex", "include?", "index", "initialize", "initialize_copy", "insert", "inspect", "intern",
    "length", "lines", "ljust", "lstrip", "lstrip!", "match", "match?", "next",
    "next!", "oct", "ord", "partition", "prepend", "replace", "reverse", "reverse!",
    "rindex", "rjust", "rpartition", "rstrip", "rstrip!", "scan", "scrub", "scrub!",
    "setbyte", "size", "slice", "slice!", "split", "squeeze", "squeeze!", "start_with?",
    "strip", "strip!", "sub", "sub!", "succ", "succ!", "sum", "swapcase",
    "swapcase!", "to_c", "to_f", "to_i", "to_r", "to_s", "to_str", "to_sym",
    "tr", "tr!", "tr_s", "tr_s!", "undump", "unicode_normalize", "unicode_normalize!", "unicode_normalized?",
    "unpack", "unpack1", "upcase", "upcase!", "upto", "valid_encoding?"
  ]),
  ("Symbol", [
    "<", "<=", "<=>", "==", "===", "=~", ">", ">=",
    "[]", "between?", "capitalize", "casecmp", "casecmp?", "clamp", "downcase", "empty?",
    "encoding", "end_with?", "id2name", "inspect", "intern", "length", "match", "match?",
    "name", "next", "size", "slice", "start_with?", "succ", "swapcase", "to_proc",
    "to_s", "to_sym", "upcase"
  ]),
  ("Array", [
    "&", "*", "+", "-", "<<", "<=>", "==", "[]",
    "[]=", "all?", "any?", "append", "assoc", "at", "bsearch", "bsearch_index",
    "chain", "chunk", "chunk_while", "clear", "collect", "collect!", "collect_concat", "combination",
    "compact", "compact!", "concat", "count", "cycle", "deconstruct", "delete", "delete_at",
    "delete_if", "detect", "difference", "dig", "drop", "drop_while", "each", "each_cons",
    "each_entry", "each_index", "each_slice", "each_with_index", "each_with_object", "empty?", "entries", "eql?",
    "fetch", "fetch_values", "fill", "filter", "filter!", "filter_map", "find", "find_all",
    "find_index", "first", "flat_map", "flatten", "flatten!", "freeze", "grep", "grep_v",
    "group_by", "hash", "include?", "index", "initialize", "initialize_copy", "inject", "insert",
    "inspect", "intersect?", "intersection", "join", "keep_if", "last", "lazy", "length",
    "map", "map!", "max", "max_by", "member?", "min", "min_by", "minmax",
    "minmax_by", "none?", "one?", "pack", "partition", "permutation", "pop", "prepend",
    "product", "push", "rassoc", "reduce", "reject", "reject!", "repeated_combination", "repeated_permutation",
    "replace", "reverse", "reverse!", "reverse_each", "rfind", "rindex", "rotate", "rotate!",
    "sample", "select", "select!", "shift", "shuffle", "shuffle!", "size", "slice",
    "slice!", "slice_after", "slice_before", "slice_when", "sort", "sort!", "sort_by", "sort_by!",
    "sum", "take", "take_while", "tally", "to_a", "to_ary", "to_h", "to_s",
    "to_set", "transpose", "union", "uniq", "uniq!", "unshift", "values_at", "zip",
    "|"
  ]),
  ("Hash", [
    "<", "<=", "==", ">", ">=", "[]", "[]=", "all?",
    "any?", "assoc", "chain", "chunk", "chunk_while", "clear", "collect", "collect_concat",
    "compact", "compact!", "compare_by_identity", "compare_by_identity?", "count", "cycle", "deconstruct_keys", "default",
    "default=", "default_proc", "default_proc=", "delete", "delete_if", "detect", "dig", "drop",
    "drop_while", "each", "each_cons", "each_entry", "each_key", "each_pair", "each_slice", "each_value",
    "each_with_index", "each_with_object", "empty?", "entries", "eql?", "except", "fetch", "fetch_values",
    "filter", "filter!", "filter_map", "find", "find_all", "find_index", "first", "flat_map",
    "flatten", "freeze", "grep", "grep_v", "group_by", "has_key?", "has_value?", "hash",
    "include?", "initialize", "initialize_copy", "inject", "inspect", "invert", "keep_if", "key",
    "key?", "keys", "lazy", "length", "map", "max", "max_by", "member?",
    "merge", "merge!", "min", "min_by", "minmax", "minmax_by", "none?", "one?",
    "partition", "rassoc", "reduce", "rehash", "reject", "reject!", "replace", "reverse_each",
    "select", "select!", "shift", "size", "slice", "slice_after", "slice_before", "slice_when",
    "sort", "sort_by", "store", "sum", "take", "take_while", "tally", "to_a",
    "to_h", "to_hash", "to_proc", "to_s", "to_set", "transform_keys", "transform_keys!", "transform_values",
    "transform_values!", "uniq", "update", "value?", "values", "values_at", "zip"
  ]),
  ("Proc", [
    "<<", "==", "===", ">>", "[]", "arity", "binding", "call",
    "clone", "curry", "dup", "eql?", "hash", "inspect", "lambda?", "parameters",
    "ruby2_keywords", "source_location", "to_proc", "to_s", "yield"
  ]),
  ("Range", [
    "%", "==", "===", "all?", "any?", "begin", "bsearch", "chain",
    "chunk", "chunk_while", "collect", "collect_concat", "compact", "count", "cover?", "cycle",
    "detect", "drop", "drop_while", "each", "each_cons", "each_entry", "each_slice", "each_with_index",
    "each_with_object", "end", "entries", "eql?", "exclude_end?", "filter", "filter_map", "find",
    "find_all", "find_index", "first", "flat_map", "grep", "grep_v", "group_by", "hash",
    "include?", "initialize", "initialize_copy", "inject", "inspect", "last", "lazy", "map",
    "max", "max_by", "member?", "min", "min_by", "minmax", "minmax_by", "none?",
    "one?", "overlap?", "partition", "reduce", "reject", "reverse_each", "select", "size",
    "slice_after", "slice_before", "slice_when", "sort", "sort_by", "step", "sum", "take",
    "take_while", "tally", "to_a", "to_h", "to_s", "to_set", "uniq", "zip"
  ]),
  ("Random", [
    "==", "initialize_copy", "left", "marshal_dump", "marshal_load", "state"
  ]),
  ("Exception", [
    "==", "backtrace", "backtrace_locations", "cause", "detailed_message", "exception", "full_message", "initialize",
    "inspect", "message", "method_missing", "respond_to?", "respond_to_missing?", "set_backtrace", "to_s"
  ]),
  ("StandardError", [

  ]),
  ("RuntimeError", [

  ]),
  ("ArgumentError", [

  ]),
  ("TypeError", [

  ]),
  ("NameError", [
    "initialize", "local_variables", "name", "receiver"
  ]),
  ("NoMethodError", [
    "args", "initialize", "private_call?"
  ]),
  ("ZeroDivisionError", [

  ]),
  ("LocalJumpError", [
    "exit_value", "reason"
  ]),
  ("FrozenError", [
    "initialize", "receiver"
  ]),
  ("IndexError", [

  ]),
  ("KeyError", [
    "initialize", "key", "receiver"
  ]),
  ("RangeError", [

  ]),
  ("StopIteration", [
    "result"
  ]),
  ("NotImplementedError", [

  ]),
  ("ScriptError", [

  ])
]

/-- Singleton (class-side) method names each bootstrap class defines in
    CRuby (e.g. Hash.ruby2_keywords_hash, Array.[]): a send to a class
    object resolving past these must gate. -/
def crubySingletonNames : List (String × List String) := [
  ("BasicObject", [

  ]),
  ("Object", [

  ]),
  ("Module", [
    "constants", "nesting", "used_modules", "used_refinements"
  ]),
  ("Class", [
    "allocate"
  ]),
  ("NilClass", [

  ]),
  ("TrueClass", [

  ]),
  ("FalseClass", [

  ]),
  ("Integer", [
    "sqrt", "try_convert"
  ]),
  ("Float", [

  ]),
  ("Rational", [
    "convert"
  ]),
  ("Complex", [
    "convert", "polar", "rect", "rectangular"
  ]),
  ("Enumerator", [
    "produce", "product"
  ]),
  ("Enumerator::Generator", [

  ]),
  ("Enumerator::Yielder", [

  ]),
  ("Enumerator::Chain", [

  ]),
  ("String", [
    "new", "try_convert"
  ]),
  ("Symbol", [
    "all_symbols"
  ]),
  ("Array", [
    "[]", "new", "try_convert"
  ]),
  ("Hash", [
    "[]", "ruby2_keywords_hash", "ruby2_keywords_hash?", "try_convert"
  ]),
  ("Proc", [
    "new"
  ]),
  ("Range", [

  ]),
  ("Random", [
    "bytes", "left", "new_seed", "rand", "seed", "srand", "state", "urandom"
  ]),
  ("Exception", [
    "exception", "to_tty?"
  ]),
  ("StandardError", [

  ]),
  ("RuntimeError", [

  ]),
  ("ArgumentError", [

  ]),
  ("TypeError", [

  ]),
  ("NameError", [

  ]),
  ("NoMethodError", [

  ]),
  ("ZeroDivisionError", [

  ]),
  ("LocalJumpError", [

  ]),
  ("FrozenError", [

  ]),
  ("IndexError", [

  ]),
  ("KeyError", [

  ]),
  ("RangeError", [

  ]),
  ("StopIteration", [

  ]),
  ("NotImplementedError", [

  ]),
  ("ScriptError", [

  ])
]

/-- Known constants in modeled namespaces; absence is a gate, not NameError. -/
def crubyNamespaceConstants : List (String × List String) := [
  ("BasicObject", ["BasicObject"]),
  ("Object", ["ARGF", "ARGV", "ArgumentError", "Array", "BasicObject", "Binding", "CROSS_COMPILING", "Class", "ClosedQueueError", "Comparable", "Complex", "ConditionVariable", "Data", "DidYouMean", "Dir", "ENV", "EOFError", "Encoding", "EncodingError", "Enumerable", "Enumerator", "Errno", "ErrorHighlight", "Exception", "FalseClass", "Fiber", "FiberError", "File", "FileTest", "Float", "FloatDomainError", "FrozenError", "GC", "Gem", "Hash", "IO", "IOError", "IndexError", "Integer", "Interrupt", "Kernel", "KeyError", "LoadError", "LocalJumpError", "Marshal", "MatchData", "Math", "Method", "Module", "Monitor", "MonitorMixin", "Mutex", "NameError", "NilClass", "NoMatchingPatternError", "NoMatchingPatternKeyError", "NoMemoryError", "NoMethodError", "NotImplementedError", "Numeric", "Object", "ObjectSpace", "Pathname", "Proc", "Process", "Queue", "RUBY_COPYRIGHT", "RUBY_DESCRIPTION", "RUBY_ENGINE", "RUBY_ENGINE_VERSION", "RUBY_PATCHLEVEL", "RUBY_PLATFORM", "RUBY_RELEASE_DATE", "RUBY_REVISION", "RUBY_VERSION", "Ractor", "Random", "Range", "RangeError", "Rational", "RbConfig", "Refinement", "Regexp", "RegexpError", "Ruby", "RubyVM", "RuntimeError", "STDERR", "STDIN", "STDOUT", "ScriptError", "SecurityError", "Set", "Signal", "SignalException", "SizedQueue", "StandardError", "StopIteration", "String", "Struct", "Symbol", "SyntaxError", "SyntaxSuggest", "SystemCallError", "SystemExit", "SystemStackError", "TOPLEVEL_BINDING", "Thread", "ThreadError", "ThreadGroup", "Time", "TracePoint", "TrueClass", "TypeError", "UnboundMethod", "UncaughtThrowError", "UnicodeNormalize", "Warning", "ZeroDivisionError"]),
  ("Module", []),
  ("Class", []),
  ("NilClass", []),
  ("TrueClass", []),
  ("FalseClass", []),
  ("Integer", []),
  ("Float", ["DIG", "EPSILON", "INFINITY", "MANT_DIG", "MAX", "MAX_10_EXP", "MAX_EXP", "MIN", "MIN_10_EXP", "MIN_EXP", "NAN", "RADIX"]),
  ("Rational", []),
  ("Complex", ["I"]),
  ("Enumerator", ["ArithmeticSequence", "Chain", "Generator", "Lazy", "Producer", "Product", "Yielder"]),
  ("Enumerator::Generator", []),
  ("Enumerator::Yielder", []),
  ("Enumerator::Chain", []),
  ("String", []),
  ("Symbol", []),
  ("Array", []),
  ("Hash", []),
  ("Proc", []),
  ("Range", []),
  ("Random", ["Base", "Formatter"]),
  ("Exception", []),
  ("StandardError", []),
  ("RuntimeError", []),
  ("ArgumentError", []),
  ("TypeError", []),
  ("NameError", []),
  ("NoMethodError", []),
  ("ZeroDivisionError", []),
  ("LocalJumpError", []),
  ("FrozenError", []),
  ("IndexError", []),
  ("KeyError", []),
  ("RangeError", []),
  ("StopIteration", []),
  ("NotImplementedError", []),
  ("ScriptError", [])
]

/-- Constants a require may define, curated separately from the oracle's
    already-loaded constants. Preserve the L109 fidelity gate on regeneration. -/
def crubyStdlibConstants : List String := [
  "YAML", "Date", "DateTime", "OpenSSL", "Digest",
  "Tempfile", "FileUtils", "Shellwords", "StringIO", "Timeout", "Socket",
  "OptionParser", "Open3", "SecureRandom", "Etc", "Zlib", "Base64", "CSV",
  "Logger", "Delegator", "SimpleDelegator", "Singleton", "Observable"
]

/-- Toplevel constants CRuby defines (Object.constants): a constant-lookup
    miss on one of these is "unmodeled", not NameError. -/
def crubyToplevelConstants : List String := [
  "ARGF", "ARGV", "ArgumentError", "Array", "BasicObject", "Binding", "CROSS_COMPILING", "Class",
  "ClosedQueueError", "Comparable", "Complex", "ConditionVariable", "Data", "DidYouMean", "Dir", "ENV",
  "EOFError", "Encoding", "EncodingError", "Enumerable", "Enumerator", "Errno", "ErrorHighlight", "Exception",
  "FalseClass", "Fiber", "FiberError", "File", "FileTest", "Float", "FloatDomainError", "FrozenError",
  "GC", "Gem", "Hash", "IO", "IOError", "IndexError", "Integer", "Interrupt",
  "Kernel", "KeyError", "LoadError", "LocalJumpError", "Marshal", "MatchData", "Math", "Method",
  "Module", "Monitor", "MonitorMixin", "Mutex", "NameError", "NilClass", "NoMatchingPatternError", "NoMatchingPatternKeyError",
  "NoMemoryError", "NoMethodError", "NotImplementedError", "Numeric", "Object", "ObjectSpace", "Pathname", "Proc",
  "Process", "Queue", "RUBYGEMS_ACTIVATION_MONITOR", "RUBY_COPYRIGHT", "RUBY_DESCRIPTION", "RUBY_ENGINE", "RUBY_ENGINE_VERSION", "RUBY_PATCHLEVEL",
  "RUBY_PLATFORM", "RUBY_RELEASE_DATE", "RUBY_REVISION", "RUBY_VERSION", "Ractor", "Random", "Range", "RangeError",
  "Rational", "RbConfig", "Refinement", "Regexp", "RegexpError", "Ruby", "RubyVM", "RuntimeError",
  "STDERR", "STDIN", "STDOUT", "ScriptError", "SecurityError", "Set", "Signal", "SignalException",
  "SizedQueue", "StandardError", "StopIteration", "String", "Struct", "Symbol", "SyntaxError", "SyntaxSuggest",
  "SystemCallError", "SystemExit", "SystemStackError", "TOPLEVEL_BINDING", "Thread", "ThreadError", "ThreadGroup", "Time",
  "TracePoint", "TrueClass", "TypeError", "UnboundMethod", "UncaughtThrowError", "UnicodeNormalize", "Warning", "ZeroDivisionError"
]

/-- Names introduced by modeled requires; consulted only after a load attempt. -/
def crubyFeatureRoots : List (String × List String) := [
  ("forwardable", ["Forwardable", "SingleForwardable"]),
  ("json", ["JSON"]),
  ("uri", ["IPAddr", "IPSocket", "URI"]),
  ("sorbet-runtime", ["PP", "PrettyPrint", "T"])
]

def crubyFeatureMethods : List (String × List String) := [
  ("Forwardable", ["def_delegator", "def_delegators", "def_instance_delegator", "def_instance_delegators", "delegate", "instance_delegate"]),
  ("JSON", ["dump", "fast_generate", "fast_unparse", "generate", "load", "load_file", "load_file!", "parse", "parse!", "pretty_generate", "pretty_unparse", "restore", "unparse", "unsafe_load"]),
  ("JSON::Coder", ["dump", "generate", "initialize", "load", "load_file", "parse"]),
  ("JSON::Ext", []),
  ("JSON::Ext::Generator", []),
  ("JSON::Ext::Generator::GeneratorMethods", []),
  ("JSON::Ext::Generator::GeneratorMethods::Array", ["to_json"]),
  ("JSON::Ext::Generator::GeneratorMethods::FalseClass", ["to_json"]),
  ("JSON::Ext::Generator::GeneratorMethods::Float", ["to_json"]),
  ("JSON::Ext::Generator::GeneratorMethods::Hash", ["to_json"]),
  ("JSON::Ext::Generator::GeneratorMethods::Integer", ["to_json"]),
  ("JSON::Ext::Generator::GeneratorMethods::NilClass", ["to_json"]),
  ("JSON::Ext::Generator::GeneratorMethods::Object", ["to_json"]),
  ("JSON::Ext::Generator::GeneratorMethods::String", ["to_json"]),
  ("JSON::Ext::Generator::GeneratorMethods::TrueClass", ["to_json"]),
  ("JSON::Ext::Generator::State", ["[]", "[]=", "_configure", "allow_duplicate_key?", "allow_nan=", "allow_nan?", "array_nl", "array_nl=", "as_json", "as_json=", "ascii_only=", "ascii_only?", "buffer_initial_length", "buffer_initial_length=", "check_circular?", "configure", "depth", "depth=", "escape_slash", "escape_slash=", "escape_slash?", "generate", "indent", "indent=", "initialize", "initialize_copy", "max_nesting", "max_nesting=", "merge", "object_nl", "object_nl=", "script_safe", "script_safe=", "script_safe?", "space", "space=", "space_before", "space_before=", "strict", "strict=", "strict?", "to_h", "to_hash"]),
  ("JSON::Ext::Parser", ["initialize", "parse", "source"]),
  ("JSON::Ext::ParserConfig", ["initialize", "parse"]),
  ("JSON::Fragment", ["initialize", "json", "json=", "to_json"]),
  ("JSON::GeneratorError", ["detailed_message", "initialize", "invalid_object"]),
  ("JSON::JSONError", []),
  ("JSON::NestingError", []),
  ("JSON::ParserError", ["column", "line"]),
  ("JSON::ParserOptions", []),
  ("PP", []),
  ("PP::ObjectMixin", ["pretty_print", "pretty_print_cycle", "pretty_print_inspect", "pretty_print_instance_variables"]),
  ("PP::PPMethods", ["check_inspect_key", "comma_breakable", "guard_inspect", "guard_inspect_key", "object_address_group", "object_group", "pop_inspect_key", "pp", "pp_hash", "pp_hash_pair", "pp_object", "push_inspect_key", "seplist"]),
  ("PP::SingleLine", []),
  ("PrettyPrint", ["break_outmost_groups", "breakable", "current_group", "fill_breakable", "flush", "genspace", "group", "group_queue", "group_sub", "indent", "initialize", "maxwidth", "nest", "newline", "output", "text"]),
  ("PrettyPrint::Breakable", ["indent", "initialize", "obj", "output", "width"]),
  ("PrettyPrint::Group", ["break", "break?", "breakables", "depth", "first?", "initialize"]),
  ("PrettyPrint::GroupQueue", ["delete", "deq", "enq", "initialize"]),
  ("PrettyPrint::SingleLine", ["breakable", "first?", "flush", "group", "initialize", "nest", "text"]),
  ("PrettyPrint::Text", ["add", "initialize", "output", "width"]),
  ("SingleForwardable", ["def_delegator", "def_delegators", "def_single_delegator", "def_single_delegators", "delegate", "single_delegate"]),
  ("T", []),
  ("T::AbstractUtils", []),
  ("T::Array", []),
  ("T::Class", []),
  ("T::CompatibilityPatches", []),
  ("T::CompatibilityPatches::MethodExtensions", ["arity", "parameters", "source_location"]),
  ("T::Configuration", []),
  ("T::DefMods", ["abstract", "final", "overridable", "override"]),
  ("T::Enum", ["<=>", "_bind_name", "_dump", "as_json", "assert_bound!", "clone", "const_to_serialized_val", "dup", "initialize", "inspect", "serialize", "to_json", "to_s", "to_str"]),
  ("T::Enum::LegacyMigrationMode", ["==", "===", "comparison_assertion_failed"]),
  ("T::Enumerable", []),
  ("T::Enumerator", []),
  ("T::Enumerator::Chain", []),
  ("T::Enumerator::Lazy", []),
  ("T::Generic", ["[]", "has_attached_class!", "type_member", "type_template"]),
  ("T::Hash", []),
  ("T::Helpers", ["abstract!", "final!", "interface!", "mixes_in_class_methods", "requires_ancestor", "sealed!"]),
  ("T::ImmutableStruct", ["initialize", "with"]),
  ("T::InexactStruct", []),
  ("T::Module", []),
  ("T::Private", []),
  ("T::Private::Abstract", []),
  ("T::Private::Abstract::Data", []),
  ("T::Private::Abstract::Declare", []),
  ("T::Private::Abstract::Hooks", ["append_features", "extend_object", "inherited", "prepended"]),
  ("T::Private::Abstract::Validate", []),
  ("T::Private::CallerUtils", []),
  ("T::Private::Casts", []),
  ("T::Private::ClassUtils", []),
  ("T::Private::DeclState", ["active_declaration", "active_declaration=", "consume!", "previous_declaration", "previous_declaration=", "reset!", "skip_on_method_added", "skip_on_method_added=", "without_on_method_added"]),
  ("T::Private::Final", []),
  ("T::Private::Final::NoIncludeExtend", ["extended", "included"]),
  ("T::Private::Final::NoInherit", ["inherited"]),
  ("T::Private::Methods", []),
  ("T::Private::Methods::ARG_NOT_PROVIDED", []),
  ("T::Private::Methods::CallValidation", []),
  ("T::Private::Methods::DeclBuilder", ["abstract", "bind", "check_live!", "checked", "decl", "final", "finalize!", "initialize", "on_failure", "overridable", "override", "params", "returns", "type_parameters", "void"]),
  ("T::Private::Methods::DeclBuilder::BuilderError", []),
  ("T::Private::Methods::Declaration", ["bind", "bind=", "checked", "checked=", "finalized", "finalized=", "mod", "mod=", "mode", "mode=", "on_failure", "on_failure=", "override_allow_incompatible", "override_allow_incompatible=", "params", "params=", "raw", "raw=", "returns", "returns=", "type_parameters", "type_parameters="]),
  ("T::Private::Methods::DeclarationBlock", ["abstract", "abstract=", "blk_or_decl", "blk_or_decl=", "final", "final=", "loc", "loc=", "method_name", "method_name=", "mod", "mod=", "overridable", "overridable=", "override", "override="]),
  ("T::Private::Methods::MethodHooks", ["method_added"]),
  ("T::Private::Methods::Modes", []),
  ("T::Private::Methods::PROC_TYPE", []),
  ("T::Private::Methods::Signature", ["arg_count", "arg_types", "as_alias", "bind", "block_name", "block_type", "check_level", "defined_raw", "each_args_value_type", "effective_return_type", "force_type_init", "initialize", "keyrest_name", "keyrest_type", "kwarg_names", "kwarg_types", "method", "method_desc", "method_name", "method_name=", "mode", "on_failure", "override_allow_incompatible", "owner", "parameters", "req_arg_count", "req_kwarg_names", "rest_name", "rest_type", "return_type"]),
  ("T::Private::Methods::SignatureValidation", []),
  ("T::Private::Methods::SingletonMethodHooks", ["singleton_method_added"]),
  ("T::Private::MixesInClassMethods", ["included"]),
  ("T::Private::Mixins", []),
  ("T::Private::Retry", []),
  ("T::Private::Retry::RETRY", []),
  ("T::Private::RuntimeLevels", []),
  ("T::Private::Sealed", []),
  ("T::Private::Sealed::NoIncludeExtend", ["extended", "included", "sealed_subclasses"]),
  ("T::Private::Sealed::NoInherit", ["inherited", "sealed_subclasses"]),
  ("T::Private::Types", []),
  ("T::Private::Types::NotTyped", ["build_type", "name", "subtype_of_single?", "valid?"]),
  ("T::Private::Types::SimplePairUnion", ["initialize", "recursively_valid?", "types", "unwrap_nilable", "valid?"]),
  ("T::Private::Types::SimplePairUnion::DuplicateType", []),
  ("T::Private::Types::StringHolder", ["build_type", "initialize", "name", "string", "subtype_of_single?", "valid?"]),
  ("T::Private::Types::TypeAlias", ["aliased_type", "build_type", "checked", "effective_aliased_type", "initialize", "name", "recursively_valid?", "valid?"]),
  ("T::Private::Types::Void", ["build_type", "name", "subtype_of_single?", "valid?"]),
  ("T::Private::Types::Void::Private", []),
  ("T::Private::Types::Void::VOID", []),
  ("T::Props", []),
  ("T::Props::ClassMethods", ["const", "decorator", "decorator_class", "extended", "included", "inherited", "plugin", "plugins", "prepended", "prop", "props", "reload_decorator!", "validate_prop_value"]),
  ("T::Props::Constructor", []),
  ("T::Props::Constructor::DecoratorMethods", ["construct_props_without_defaults"]),
  ("T::Props::CustomType", ["deserialize", "instance?", "serialize", "valid?"]),
  ("T::Props::Decorator", ["add_prop_definition", "all_props", "convert_type_to_class", "decorated_class", "define_foreign_method", "define_getter_and_setter", "elaborate_override", "elaborate_override_entry", "foreign_prop_get", "get", "handle_foreign_option", "handle_redaction_option", "initialize", "method_defined_on_ancestor?", "model_inherited", "plugin", "prop_defined", "prop_get", "prop_get_if_set", "prop_get_logic", "prop_nilable?", "prop_rules", "prop_set", "prop_validate_definition!", "props", "set", "smart_coerce", "valid_rule_key?", "validate_foreign_option", "validate_overrides", "validate_prop_name", "validate_prop_value"]),
  ("T::Props::Decorator::NoRulesError", []),
  ("T::Props::Error", []),
  ("T::Props::GeneratedCodeValidation", []),
  ("T::Props::GeneratedCodeValidation::ValidationError", []),
  ("T::Props::HasLazilySpecializedMethods", []),
  ("T::Props::HasLazilySpecializedMethods::DecoratorMethods", ["eagerly_define_lazy_methods!", "eagerly_define_lazy_vm_methods!", "enqueue_lazy_method_definition!", "enqueue_lazy_vm_method_definition!", "eval_lazily_defined_method!", "eval_lazily_defined_vm_method!", "lazily_defined_methods", "lazily_defined_vm_methods"]),
  ("T::Props::HasLazilySpecializedMethods::SourceEvaluationDisabled", ["initialize"]),
  ("T::Props::ImmutableProp", []),
  ("T::Props::InvalidValueError", []),
  ("T::Props::Optional", []),
  ("T::Props::Optional::DecoratorMethods", ["add_prop_definition", "compute_derived_rules", "get_default", "has_default?", "prop_optional?", "prop_validate_definition!", "props_with_defaults", "props_without_defaults", "valid_rule_key?"]),
  ("T::Props::Plugin", []),
  ("T::Props::Plugin::ClassMethods", ["included"]),
  ("T::Props::Plugin::Private", []),
  ("T::Props::PrettyPrintable", ["inspect", "pretty_inspect", "pretty_print"]),
  ("T::Props::PrettyPrintable::DecoratorMethods", ["inspect_class_with_decoration", "pretty_print_extra", "valid_rule_key?"]),
  ("T::Props::Private", []),
  ("T::Props::Private::ApplyComplexDefault", ["default"]),
  ("T::Props::Private::ApplyDefault", ["bound_setter_proc", "default", "initialize", "set_default"]),
  ("T::Props::Private::ApplyDefaultFactory", ["default", "initialize", "set_default"]),
  ("T::Props::Private::ApplyEmptyArrayDefault", ["default", "set_default"]),
  ("T::Props::Private::ApplyEmptyHashDefault", ["default", "set_default"]),
  ("T::Props::Private::ApplyFixedDefault", ["initialize", "set_default"]),
  ("T::Props::Private::ApplyPrimitiveDefault", ["default"]),
  ("T::Props::Private::DeserializerGenerator", []),
  ("T::Props::Private::Parse", ["parse", "require_parser", "s"]),
  ("T::Props::Private::SerdeTransform", []),
  ("T::Props::Private::SerdeTransform::Mode", []),
  ("T::Props::Private::SerializerGenerator", []),
  ("T::Props::Private::SetterFactory", []),
  ("T::Props::Serializable", ["__t_props_generated_deserialize", "__t_props_generated_serialize", "deserialize", "recursive_stringify_keys", "required_prop_missing_from_deserialize", "required_prop_missing_from_serialize", "serialize", "with", "with_existing_hash"]),
  ("T::Props::Serializable::ClassMethods", ["from_hash", "from_hash!", "prop_by_serialized_forms"]),
  ("T::Props::Serializable::DecoratorMethods", ["add_prop_definition", "extra_props", "from_hash", "generate_deserialize_source", "generate_serialize_source", "get_id", "message_with_generated_source_context", "pretty_print_extra", "prop_by_serialized_forms", "prop_dont_store?", "prop_serialized_form", "prop_validate_definition!", "raise_nil_deserialize_error", "required_props", "serialized_form_prop", "valid_rule_key?"]),
  ("T::Props::TypeValidation", []),
  ("T::Props::TypeValidation::DecoratorMethods", ["find_invalid_subtype", "prop_validate_definition!", "type_error_message", "valid_rule_key?", "validate_type"]),
  ("T::Props::TypeValidation::UnderspecifiedType", []),
  ("T::Props::Utils", []),
  ("T::Props::WeakConstructor", ["initialize"]),
  ("T::Props::WeakConstructor::DecoratorMethods", ["construct_props_with_defaults", "construct_props_without_defaults"]),
  ("T::Range", []),
  ("T::Set", []),
  ("T::Sig", ["sig"]),
  ("T::Sig::WithoutRuntime", []),
  ("T::Struct", []),
  ("T::Syntax", []),
  ("T::Types", []),
  ("T::Types::Anything", ["build_type", "initialize", "name", "subtype_of_single?", "valid?"]),
  ("T::Types::Anything::Private", []),
  ("T::Types::AttachedClassType", ["build_type", "initialize", "name", "subtype_of_single?", "valid?"]),
  ("T::Types::AttachedClassType::Private", []),
  ("T::Types::Base", ["==", "build_type", "describe_obj", "eql?", "error_message", "error_message_for_obj", "error_message_for_obj_recursive", "hash", "name", "recursively_valid?", "subtype_of?", "subtype_of_single?", "to_s", "valid?", "validate!"]),
  ("T::Types::ClassOf", ["[]", "build_type", "describe_obj", "initialize", "name", "subtype_of_single?", "type", "valid?"]),
  ("T::Types::Enum", ["build_type", "describe_obj", "initialize", "name", "subtype_of_single?", "valid?", "values"]),
  ("T::Types::FixedArray", ["build_type", "describe_obj", "initialize", "name", "recursively_valid?", "subtype_of_single?", "types", "valid?"]),
  ("T::Types::FixedHash", ["build_type", "describe_obj", "initialize", "name", "recursively_valid?", "serialize_hash", "subtype_of_single?", "types", "valid?"]),
  ("T::Types::Intersection", ["build_type", "initialize", "name", "recursively_valid?", "subtype_of_single?", "types", "valid?"]),
  ("T::Types::NoReturn", ["build_type", "initialize", "name", "subtype_of_single?", "valid?"]),
  ("T::Types::NoReturn::Private", []),
  ("T::Types::Proc", ["arg_types", "build_type", "initialize", "name", "returns", "subtype_of_single?", "valid?"]),
  ("T::Types::SelfType", ["build_type", "initialize", "name", "subtype_of_single?", "valid?"]),
  ("T::Types::SelfType::Private", []),
  ("T::Types::Simple", ["build_type", "error_message", "initialize", "name", "raw_type", "recursively_valid?", "subtype_of_single?", "to_nilable", "valid?"]),
  ("T::Types::Simple::Private", []),
  ("T::Types::Simple::Private::Pool", []),
  ("T::Types::TEnum", ["build_type", "initialize", "name", "subtype_of_single?", "val", "valid?"]),
  ("T::Types::TypeMember", []),
  ("T::Types::TypeParameter", ["build_type", "initialize", "name", "subtype_of_single?", "valid?"]),
  ("T::Types::TypeParameter::Private", []),
  ("T::Types::TypeTemplate", []),
  ("T::Types::TypeVariable", ["build_type", "initialize", "name", "subtype_of_single?", "valid?", "variance"]),
  ("T::Types::TypedArray", ["name", "new", "recursively_valid?", "underlying_class", "valid?"]),
  ("T::Types::TypedArray::Private", []),
  ("T::Types::TypedArray::Private::Pool", []),
  ("T::Types::TypedArray::Untyped", ["freeze", "initialize", "valid?"]),
  ("T::Types::TypedArray::Untyped::Private", []),
  ("T::Types::TypedClass", ["build_type", "initialize", "name", "subtype_of_single?", "type", "underlying_class", "valid?"]),
  ("T::Types::TypedClass::Anything", ["freeze", "initialize"]),
  ("T::Types::TypedClass::Anything::Private", []),
  ("T::Types::TypedClass::Private", []),
  ("T::Types::TypedClass::Private::Pool", []),
  ("T::Types::TypedClass::Untyped", ["freeze", "initialize"]),
  ("T::Types::TypedClass::Untyped::Private", []),
  ("T::Types::TypedEnumerable", ["build_type", "describe_obj", "initialize", "name", "recursively_valid?", "subtype_of_single?", "type", "type_from_instance", "type_from_instances", "underlying_class", "valid?"]),
  ("T::Types::TypedEnumerable::Untyped", ["initialize", "valid?"]),
  ("T::Types::TypedEnumerator", ["name", "new", "recursively_valid?", "underlying_class", "valid?"]),
  ("T::Types::TypedEnumerator::Untyped", ["initialize", "valid?"]),
  ("T::Types::TypedEnumeratorChain", ["name", "new", "recursively_valid?", "underlying_class", "valid?"]),
  ("T::Types::TypedEnumeratorChain::Untyped", ["initialize", "valid?"]),
  ("T::Types::TypedEnumeratorLazy", ["name", "new", "recursively_valid?", "underlying_class", "valid?"]),
  ("T::Types::TypedEnumeratorLazy::Untyped", ["initialize", "valid?"]),
  ("T::Types::TypedHash", ["initialize", "keys", "name", "new", "recursively_valid?", "type", "underlying_class", "valid?", "values"]),
  ("T::Types::TypedHash::Untyped", ["freeze", "initialize", "valid?"]),
  ("T::Types::TypedHash::Untyped::Private", []),
  ("T::Types::TypedModule", ["build_type", "initialize", "name", "subtype_of_single?", "type", "underlying_class", "valid?"]),
  ("T::Types::TypedModule::Anything", ["freeze", "initialize"]),
  ("T::Types::TypedModule::Anything::Private", []),
  ("T::Types::TypedModule::Private", []),
  ("T::Types::TypedModule::Private::Pool", []),
  ("T::Types::TypedModule::Untyped", ["freeze", "initialize"]),
  ("T::Types::TypedModule::Untyped::Private", []),
  ("T::Types::TypedRange", ["name", "new", "recursively_valid?", "underlying_class", "valid?"]),
  ("T::Types::TypedRange::Untyped", ["initialize", "valid?"]),
  ("T::Types::TypedSet", ["name", "new", "recursively_valid?", "underlying_class", "valid?"]),
  ("T::Types::TypedSet::Untyped", ["initialize", "valid?"]),
  ("T::Types::Union", ["build_type", "initialize", "name", "recursively_valid?", "subtype_of_single?", "type_shortcuts", "types", "unwrap_nilable", "valid?"]),
  ("T::Types::Union::Private", []),
  ("T::Types::Union::Private::Pool", []),
  ("T::Types::Untyped", ["build_type", "initialize", "name", "subtype_of_single?", "valid?"]),
  ("T::Types::Untyped::Private", []),
  ("T::Utils", []),
  ("T::Utils::Nilable", []),
  ("T::Utils::Nilable::TypeInfo", ["is_union_type", "is_union_type=", "non_nilable_type", "non_nilable_type="]),
  ("T::Utils::Private", []),
  ("URI", []),
  ("URI::BadURIError", []),
  ("URI::Error", []),
  ("URI::FTP", ["check_typecode", "initialize", "merge", "path", "set_path", "set_typecode", "to_s", "typecode", "typecode="]),
  ("URI::File", ["check_password", "check_user", "check_userinfo", "set_host", "set_password", "set_port", "set_user", "set_userinfo"]),
  ("URI::Generic", ["+", "-", "==", "absolute", "absolute?", "authority", "check_host", "check_opaque", "check_password", "check_path", "check_port", "check_registry", "check_scheme", "check_user", "check_userinfo", "coerce", "component", "component_ary", "decoded_password", "decoded_user", "default_port", "eql?", "escape_userpass", "find_proxy", "fragment", "fragment=", "hash", "hierarchical?", "host", "host=", "hostname", "hostname=", "initialize", "inspect", "merge", "merge!", "merge_path", "normalize", "normalize!", "opaque", "opaque=", "parser", "password", "password=", "path", "path=", "port", "port=", "query", "query=", "registry", "registry=", "relative?", "replace!", "route_from", "route_from0", "route_from_path", "route_to", "scheme", "scheme=", "select", "set_authority", "set_host", "set_opaque", "set_password", "set_path", "set_port", "set_registry", "set_scheme", "set_user", "set_userinfo", "split_path", "split_userinfo", "to_s", "to_str", "user", "user=", "userinfo", "userinfo="]),
  ("URI::HTTP", ["authority", "check_host", "origin", "request_uri"]),
  ("URI::HTTPS", []),
  ("URI::InvalidComponentError", []),
  ("URI::InvalidURIError", []),
  ("URI::LDAP", ["attributes", "attributes=", "build_path_query", "dn", "dn=", "extensions", "extensions=", "filter", "filter=", "hierarchical?", "initialize", "parse_dn", "parse_query", "scope", "scope=", "set_attributes", "set_dn", "set_extensions", "set_filter", "set_scope"]),
  ("URI::LDAPS", []),
  ("URI::MailTo", ["check_headers", "check_to", "headers", "headers=", "initialize", "set_headers", "set_to", "to", "to=", "to_mailtext", "to_rfc822text", "to_s"]),
  ("URI::RFC2396_Parser", ["convert_to_uri", "escape", "extract", "initialize", "initialize_pattern", "initialize_regexp", "inspect", "join", "make_regexp", "parse", "pattern", "regexp", "split", "unescape"]),
  ("URI::RFC2396_REGEXP", []),
  ("URI::RFC2396_REGEXP::PATTERN", []),
  ("URI::RFC3986_Parser", ["convert_to_uri", "default_regexp", "escape", "extract", "initialize", "inspect", "join", "make_regexp", "parse", "regexp", "split", "unescape"]),
  ("URI::Util", ["make_components_hash"]),
  ("URI::WS", ["request_uri"]),
  ("URI::WSS", [])
]

def crubyFeatureSingletonMethods : List (String × List String) := [
  ("Forwardable", ["_delegator_method", "debug", "debug="]),
  ("JSON", ["[]", "_dump_default_options", "_load_default_options", "_unsafe_load_default_options", "const_missing", "create_id", "create_id=", "deprecated_singleton_attr_accessor", "deprecation_warning", "dump", "dump_default_options", "dump_default_options=", "fast_generate", "fast_unparse", "generate", "generator", "generator=", "load", "load_default_options", "load_default_options=", "load_file", "load_file!", "on_mixed_keys_hash", "parse", "parse!", "parser", "parser=", "pretty_generate", "pretty_unparse", "restore", "state", "state=", "unparse", "unsafe_load", "unsafe_load_default_options", "unsafe_load_default_options="]),
  ("JSON::Coder", []),
  ("JSON::Ext", []),
  ("JSON::Ext::Generator", []),
  ("JSON::Ext::Generator::GeneratorMethods", []),
  ("JSON::Ext::Generator::GeneratorMethods::Array", []),
  ("JSON::Ext::Generator::GeneratorMethods::FalseClass", []),
  ("JSON::Ext::Generator::GeneratorMethods::Float", []),
  ("JSON::Ext::Generator::GeneratorMethods::Hash", []),
  ("JSON::Ext::Generator::GeneratorMethods::Integer", []),
  ("JSON::Ext::Generator::GeneratorMethods::NilClass", []),
  ("JSON::Ext::Generator::GeneratorMethods::Object", []),
  ("JSON::Ext::Generator::GeneratorMethods::String", []),
  ("JSON::Ext::Generator::GeneratorMethods::TrueClass", []),
  ("JSON::Ext::Generator::State", ["from_state", "generate"]),
  ("JSON::Ext::Parser", ["parse"]),
  ("JSON::Ext::ParserConfig", []),
  ("JSON::Fragment", ["[]", "inspect", "keyword_init?", "members", "new"]),
  ("JSON::GeneratorError", []),
  ("JSON::JSONError", []),
  ("JSON::NestingError", []),
  ("JSON::ParserError", []),
  ("JSON::ParserOptions", ["array_class_proc", "create_additions_proc", "create_additions_warning", "object_class_proc", "prepare"]),
  ("PP", ["mcall", "pp", "sharing_detection", "sharing_detection=", "singleline_pp", "width_for"]),
  ("PP::ObjectMixin", []),
  ("PP::PPMethods", []),
  ("PP::SingleLine", []),
  ("PrettyPrint", ["format", "singleline_format"]),
  ("PrettyPrint::Breakable", []),
  ("PrettyPrint::Group", []),
  ("PrettyPrint::GroupQueue", []),
  ("PrettyPrint::SingleLine", []),
  ("PrettyPrint::Text", []),
  ("SingleForwardable", []),
  ("T", ["absurd", "all", "any", "anything", "assert_type!", "attached_class", "bind", "cast", "class_of", "deprecated_enum", "let", "must", "must_because", "nilable", "noreturn", "proc", "reveal_type", "self_type", "type_alias", "type_parameter", "unsafe", "untyped"]),
  ("T::AbstractUtils", ["abstract_method?", "abstract_methods_for", "abstract_module?", "declared_abstract_methods_for"]),
  ("T::Array", ["[]"]),
  ("T::Class", ["[]"]),
  ("T::CompatibilityPatches", []),
  ("T::CompatibilityPatches::MethodExtensions", []),
  ("T::Configuration", ["call_validation_error_handler", "call_validation_error_handler=", "call_validation_error_handler_default", "default_checked_level=", "disable_legacy_t_enum_migration_mode", "enable_checking_for_sigs_marked_checked_tests", "enable_final_checks_on_hooks", "enable_legacy_t_enum_migration_mode", "exclude_value_in_type_errors", "include_value_in_type_errors", "include_value_in_type_errors?", "inline_type_error_handler", "inline_type_error_handler=", "inline_type_error_handler_default", "legacy_t_enum_migration_mode?", "log_info_handler", "log_info_handler=", "log_info_handler_default", "module_name_mangler", "module_name_mangler=", "normalize_sensitivity_and_pii_handler", "normalize_sensitivity_and_pii_handler=", "redaction_handler", "redaction_handler=", "reset_final_checks_on_hooks", "scalar_types", "scalar_types=", "sealed_violation_whitelist", "sealed_violation_whitelist=", "sig_builder_error_handler", "sig_builder_error_handler=", "sig_builder_error_handler_default", "sig_validation_error_handler", "sig_validation_error_handler=", "sig_validation_error_handler_default", "soft_assert_handler", "soft_assert_handler=", "soft_assert_handler_default", "validate_lambda_given!", "without_ruby_warnings"]),
  ("T::DefMods", []),
  ("T::Enum", ["_load", "_register_instance", "deserialize", "each_value", "enums", "from_serialized", "fully_initialized?", "has_serialized?", "inherited", "serialize", "started_initializing?", "try_deserialize", "values"]),
  ("T::Enum::LegacyMigrationMode", []),
  ("T::Enumerable", ["[]"]),
  ("T::Enumerator", ["[]"]),
  ("T::Enumerator::Chain", ["[]"]),
  ("T::Enumerator::Lazy", ["[]"]),
  ("T::Generic", []),
  ("T::Hash", ["[]"]),
  ("T::Helpers", []),
  ("T::ImmutableStruct", ["inherited", "prop"]),
  ("T::InexactStruct", []),
  ("T::Module", ["[]"]),
  ("T::Private", []),
  ("T::Private::Abstract", []),
  ("T::Private::Abstract::Data", ["get", "key?", "set", "set_default"]),
  ("T::Private::Abstract::Declare", ["declare_abstract"]),
  ("T::Private::Abstract::Hooks", []),
  ("T::Private::Abstract::Validate", ["describe_method", "validate_abstract_module", "validate_interface", "validate_interface_all_abstract", "validate_interface_all_public", "validate_subclass"]),
  ("T::Private::CallerUtils", ["find_caller"]),
  ("T::Private::Casts", ["cast", "cast_recursive"]),
  ("T::Private::ClassUtils", ["def_with_visibility", "replace_method", "visibility_method_name"]),
  ("T::Private::DeclState", ["current", "current="]),
  ("T::Private::Final", ["declare", "final_module?", "mark_as_final_module"]),
  ("T::Private::Final::NoIncludeExtend", []),
  ("T::Private::Final::NoInherit", []),
  ("T::Private::Methods", ["_check_final_ancestors", "_hook_impl", "_on_method_added", "_unwrap_alias", "add_module_with_final_method", "all_checked_tests_sigs", "build_sig", "declare_abstract", "declare_final", "declare_overridable", "declare_override", "declare_sig", "ensure_valid_declare_dsl!", "finalize_proc", "has_sig_block_for_key", "has_sig_block_for_method", "install_hooks", "maybe_run_sig_block_for_key", "maybe_run_sig_block_for_method", "method_owner_and_name_to_key", "method_to_key", "run_all_sig_blocks", "run_builder", "run_sig", "run_sig_block_for_key", "run_sig_block_for_method", "set_final_checks_on_hooks", "signature_for_key", "signature_for_method", "start_proc", "unwrap_method"]),
  ("T::Private::Methods::ARG_NOT_PROVIDED", []),
  ("T::Private::Methods::CallValidation", ["create_abstract_wrapper", "create_validator_method", "create_validator_method_fast", "create_validator_method_fast0", "create_validator_method_fast1", "create_validator_method_fast2", "create_validator_method_fast3", "create_validator_method_fast4", "create_validator_method_kwargs", "create_validator_method_kwargs0", "create_validator_method_medium", "create_validator_method_medium0", "create_validator_method_medium1", "create_validator_method_medium2", "create_validator_method_medium3", "create_validator_method_medium4", "create_validator_method_optional_args", "create_validator_method_optional_args0_1", "create_validator_method_optional_args0_2", "create_validator_method_optional_args0_3", "create_validator_method_optional_args0_4", "create_validator_method_optional_args1_2", "create_validator_method_optional_args1_3", "create_validator_method_optional_args1_4", "create_validator_method_optional_args2_3", "create_validator_method_optional_args2_4", "create_validator_method_optional_args3_4", "create_validator_method_skip_return_fast", "create_validator_method_skip_return_fast0", "create_validator_method_skip_return_fast1", "create_validator_method_skip_return_fast2", "create_validator_method_skip_return_fast3", "create_validator_method_skip_return_fast4", "create_validator_method_skip_return_medium", "create_validator_method_skip_return_medium0", "create_validator_method_skip_return_medium1", "create_validator_method_skip_return_medium2", "create_validator_method_skip_return_medium3", "create_validator_method_skip_return_medium4", "create_validator_method_with_block", "create_validator_method_with_block0", "create_validator_method_with_block1", "create_validator_method_with_block2", "create_validator_method_with_block3", "create_validator_method_with_block4", "create_validator_procedure_fast", "create_validator_procedure_fast0", "create_validator_procedure_fast1", "create_validator_procedure_fast2", "create_validator_procedure_fast3", "create_validator_procedure_fast4", "create_validator_procedure_medium", "create_validator_procedure_medium0", "create_validator_procedure_medium1", "create_validator_procedure_medium2", "create_validator_procedure_medium3", "create_validator_procedure_medium4", "create_validator_slow", "create_validator_slow_skip_block_type", "disable_fast_path", "is_allowed_to_have_fast_path", "report_error", "safe_method_owner_to_s", "validate_call", "validate_call_skip_block_type", "wrap_method_if_needed"]),
  ("T::Private::Methods::DeclBuilder", []),
  ("T::Private::Methods::DeclBuilder::BuilderError", []),
  ("T::Private::Methods::Declaration", ["[]", "inspect", "keyword_init?", "members", "new"]),
  ("T::Private::Methods::DeclarationBlock", ["[]", "inspect", "keyword_init?", "members", "new"]),
  ("T::Private::Methods::MethodHooks", []),
  ("T::Private::Methods::Modes", ["abstract", "overridable", "overridable_override", "override", "standard", "untyped"]),
  ("T::Private::Methods::PROC_TYPE", []),
  ("T::Private::Methods::Signature", ["method_desc", "new_untyped"]),
  ("T::Private::Methods::SignatureValidation", ["base_override_loc_str", "check_level_active?", "method_visibility", "pretty_mode", "validate", "validate_non_override_mode", "validate_override_mode", "validate_override_shape", "validate_override_types", "validate_override_visibility", "visibility_strength"]),
  ("T::Private::Methods::SingletonMethodHooks", []),
  ("T::Private::MixesInClassMethods", []),
  ("T::Private::Mixins", ["declare_mixes_in_class_methods"]),
  ("T::Private::Retry", []),
  ("T::Private::Retry::RETRY", []),
  ("T::Private::RuntimeLevels", ["_toggle_checking_tests", "check_tests?", "default_checked_level", "default_checked_level=", "enable_checking_in_tests", "set_default_checked_level_from_environment", "set_enable_checking_in_tests_from_environment"]),
  ("T::Private::Sealed", ["declare", "sealed_module?", "validate_inheritance"]),
  ("T::Private::Sealed::NoIncludeExtend", []),
  ("T::Private::Sealed::NoInherit", []),
  ("T::Private::Types", []),
  ("T::Private::Types::NotTyped", []),
  ("T::Private::Types::SimplePairUnion", []),
  ("T::Private::Types::SimplePairUnion::DuplicateType", []),
  ("T::Private::Types::StringHolder", []),
  ("T::Private::Types::TypeAlias", []),
  ("T::Private::Types::Void", []),
  ("T::Private::Types::Void::Private", []),
  ("T::Private::Types::Void::VOID", []),
  ("T::Props", []),
  ("T::Props::ClassMethods", []),
  ("T::Props::Constructor", []),
  ("T::Props::Constructor::DecoratorMethods", []),
  ("T::Props::CustomType", ["checked_serialize", "included", "scalar_type?", "valid_serialization?"]),
  ("T::Props::Decorator", []),
  ("T::Props::Decorator::NoRulesError", []),
  ("T::Props::Error", []),
  ("T::Props::GeneratedCodeValidation", ["assert_equal", "self_class_decorator", "validate_deserialize", "validate_deserialize_handle_nil", "validate_deserialize_hash_read", "validate_deserialize_ivar_set", "validate_lack_of_side_effects", "validate_serialize", "validate_serialize_clause", "whitelisted_methods_for_deserialize", "whitelisted_methods_for_serialize"]),
  ("T::Props::GeneratedCodeValidation::ValidationError", []),
  ("T::Props::HasLazilySpecializedMethods", ["disable_lazy_evaluation!", "lazy_evaluation_enabled?"]),
  ("T::Props::HasLazilySpecializedMethods::DecoratorMethods", []),
  ("T::Props::HasLazilySpecializedMethods::SourceEvaluationDisabled", []),
  ("T::Props::ImmutableProp", []),
  ("T::Props::InvalidValueError", []),
  ("T::Props::Optional", []),
  ("T::Props::Optional::DecoratorMethods", []),
  ("T::Props::Plugin", []),
  ("T::Props::Plugin::ClassMethods", []),
  ("T::Props::Plugin::Private", ["apply_class_methods", "apply_decorator_methods"]),
  ("T::Props::PrettyPrintable", []),
  ("T::Props::PrettyPrintable::DecoratorMethods", []),
  ("T::Props::Private", []),
  ("T::Props::Private::ApplyComplexDefault", []),
  ("T::Props::Private::ApplyDefault", ["for", "new"]),
  ("T::Props::Private::ApplyDefaultFactory", []),
  ("T::Props::Private::ApplyEmptyArrayDefault", []),
  ("T::Props::Private::ApplyEmptyHashDefault", []),
  ("T::Props::Private::ApplyFixedDefault", ["new"]),
  ("T::Props::Private::ApplyPrimitiveDefault", []),
  ("T::Props::Private::DeserializerGenerator", ["generate", "generate_nil_handler"]),
  ("T::Props::Private::Parse", []),
  ("T::Props::Private::SerdeTransform", ["generate", "handle_custom_type", "handle_serializable_subtype", "module_name"]),
  ("T::Props::Private::SerdeTransform::Mode", []),
  ("T::Props::Private::SerializerGenerator", ["generate"]),
  ("T::Props::Private::SetterFactory", ["build_setter_proc", "nilable_proc", "non_nil_proc", "raise_pretty_error", "simple_nilable_proc", "simple_non_nil_proc"]),
  ("T::Props::Serializable", []),
  ("T::Props::Serializable::ClassMethods", []),
  ("T::Props::Serializable::DecoratorMethods", []),
  ("T::Props::TypeValidation", []),
  ("T::Props::TypeValidation::DecoratorMethods", []),
  ("T::Props::TypeValidation::UnderspecifiedType", []),
  ("T::Props::Utils", ["deep_clone", "deep_clone_freeze", "deep_clone_object", "merge_serialized_optional_rule", "need_nil_read_check?", "need_nil_write_check?", "optional_prop?", "required_prop?"]),
  ("T::Props::WeakConstructor", []),
  ("T::Props::WeakConstructor::DecoratorMethods", []),
  ("T::Range", ["[]"]),
  ("T::Set", ["[]"]),
  ("T::Sig", ["extended", "included"]),
  ("T::Sig::WithoutRuntime", ["sig"]),
  ("T::Struct", ["inherited"]),
  ("T::Syntax", ["extended", "included"]),
  ("T::Types", []),
  ("T::Types::Anything", []),
  ("T::Types::Anything::Private", []),
  ("T::Types::AttachedClassType", []),
  ("T::Types::AttachedClassType::Private", []),
  ("T::Types::Base", ["method_added"]),
  ("T::Types::ClassOf", []),
  ("T::Types::Enum", []),
  ("T::Types::FixedArray", []),
  ("T::Types::FixedHash", []),
  ("T::Types::Intersection", []),
  ("T::Types::NoReturn", []),
  ("T::Types::NoReturn::Private", []),
  ("T::Types::Proc", []),
  ("T::Types::SelfType", []),
  ("T::Types::SelfType::Private", []),
  ("T::Types::Simple", []),
  ("T::Types::Simple::Private", []),
  ("T::Types::Simple::Private::Pool", ["type_for_module"]),
  ("T::Types::TEnum", []),
  ("T::Types::TypeMember", []),
  ("T::Types::TypeParameter", ["make"]),
  ("T::Types::TypeParameter::Private", ["cached_entry", "set_entry_for"]),
  ("T::Types::TypeTemplate", []),
  ("T::Types::TypeVariable", []),
  ("T::Types::TypedArray", []),
  ("T::Types::TypedArray::Private", []),
  ("T::Types::TypedArray::Private::Pool", ["type_for_module"]),
  ("T::Types::TypedArray::Untyped", []),
  ("T::Types::TypedArray::Untyped::Private", []),
  ("T::Types::TypedClass", []),
  ("T::Types::TypedClass::Anything", []),
  ("T::Types::TypedClass::Anything::Private", []),
  ("T::Types::TypedClass::Private", []),
  ("T::Types::TypedClass::Private::Pool", ["type_for_module"]),
  ("T::Types::TypedClass::Untyped", []),
  ("T::Types::TypedClass::Untyped::Private", []),
  ("T::Types::TypedEnumerable", []),
  ("T::Types::TypedEnumerable::Untyped", []),
  ("T::Types::TypedEnumerator", []),
  ("T::Types::TypedEnumerator::Untyped", []),
  ("T::Types::TypedEnumeratorChain", []),
  ("T::Types::TypedEnumeratorChain::Untyped", []),
  ("T::Types::TypedEnumeratorLazy", []),
  ("T::Types::TypedEnumeratorLazy::Untyped", []),
  ("T::Types::TypedHash", []),
  ("T::Types::TypedHash::Untyped", []),
  ("T::Types::TypedHash::Untyped::Private", []),
  ("T::Types::TypedModule", []),
  ("T::Types::TypedModule::Anything", []),
  ("T::Types::TypedModule::Anything::Private", []),
  ("T::Types::TypedModule::Private", []),
  ("T::Types::TypedModule::Private::Pool", ["type_for_module"]),
  ("T::Types::TypedModule::Untyped", []),
  ("T::Types::TypedModule::Untyped::Private", []),
  ("T::Types::TypedRange", []),
  ("T::Types::TypedRange::Untyped", []),
  ("T::Types::TypedSet", []),
  ("T::Types::TypedSet::Untyped", []),
  ("T::Types::Union", []),
  ("T::Types::Union::Private", []),
  ("T::Types::Union::Private::Pool", ["union_of_types"]),
  ("T::Types::Untyped", []),
  ("T::Types::Untyped::Private", []),
  ("T::Utils", ["arity", "check_type_recursive!", "coerce", "lift_enum", "methods_excluding_object", "resolve_alias", "run_all_sig_blocks", "signature_for_instance_method", "signature_for_method", "string_truncate_middle", "unwrap_nilable", "wrap_method_with_call_validation_if_needed"]),
  ("T::Utils::Nilable", ["get_type_info", "get_underlying_type", "get_underlying_type_object", "is_union_with_nilclass"]),
  ("T::Utils::Nilable::TypeInfo", ["[]", "inspect", "keyword_init?", "members", "new"]),
  ("T::Utils::Private", ["coerce_and_check_module_types"]),
  ("URI", ["_decode_uri_component", "_encode_uri_component", "const_missing", "decode_uri_component", "decode_www_form", "decode_www_form_component", "encode_uri_component", "encode_www_form", "encode_www_form_component", "extract", "for", "get_encoding", "join", "parse", "parser=", "regexp", "register_scheme", "scheme_list", "split"]),
  ("URI::BadURIError", []),
  ("URI::Error", []),
  ("URI::FTP", ["build", "new2"]),
  ("URI::File", ["build"]),
  ("URI::Generic", ["build", "build2", "component", "default_port", "use_proxy?", "use_registry"]),
  ("URI::HTTP", ["build"]),
  ("URI::HTTPS", []),
  ("URI::InvalidComponentError", []),
  ("URI::InvalidURIError", []),
  ("URI::LDAP", ["build"]),
  ("URI::LDAPS", []),
  ("URI::MailTo", ["build"]),
  ("URI::RFC2396_Parser", []),
  ("URI::RFC2396_REGEXP", []),
  ("URI::RFC2396_REGEXP::PATTERN", []),
  ("URI::RFC3986_Parser", []),
  ("URI::Util", ["make_components_hash"]),
  ("URI::WS", ["build"]),
  ("URI::WSS", [])
]

def crubyFeatureConstants : List (String × List String) := [
  ("Forwardable", ["FORWARDABLE_VERSION", "VERSION"]),
  ("JSON", ["Coder", "Ext", "Fragment", "GeneratorError", "GenericObject", "Infinity", "JSONError", "JSON_LOADED", "MinusInfinity", "NaN", "NestingError", "Parser", "ParserError", "ParserOptions", "State", "VERSION"]),
  ("JSON::Coder", []),
  ("JSON::Ext", ["Generator", "Parser", "ParserConfig"]),
  ("JSON::Ext::Generator", ["GeneratorMethods", "State"]),
  ("JSON::Ext::Generator::GeneratorMethods", ["Array", "FalseClass", "Float", "Hash", "Integer", "NilClass", "Object", "String", "TrueClass"]),
  ("JSON::Ext::Generator::GeneratorMethods::Array", []),
  ("JSON::Ext::Generator::GeneratorMethods::FalseClass", []),
  ("JSON::Ext::Generator::GeneratorMethods::Float", []),
  ("JSON::Ext::Generator::GeneratorMethods::Hash", []),
  ("JSON::Ext::Generator::GeneratorMethods::Integer", []),
  ("JSON::Ext::Generator::GeneratorMethods::NilClass", []),
  ("JSON::Ext::Generator::GeneratorMethods::Object", []),
  ("JSON::Ext::Generator::GeneratorMethods::String", []),
  ("JSON::Ext::Generator::GeneratorMethods::TrueClass", []),
  ("JSON::Ext::Generator::State", []),
  ("JSON::Ext::Parser", ["Config"]),
  ("JSON::Ext::ParserConfig", []),
  ("JSON::Fragment", []),
  ("JSON::GeneratorError", []),
  ("JSON::JSONError", []),
  ("JSON::NestingError", []),
  ("JSON::ParserError", []),
  ("JSON::ParserOptions", []),
  ("PP", ["ObjectMixin", "PPMethods", "SingleLine", "VERSION"]),
  ("PP::ObjectMixin", []),
  ("PP::PPMethods", []),
  ("PP::SingleLine", []),
  ("PrettyPrint", ["Breakable", "Group", "GroupQueue", "SingleLine", "Text", "VERSION"]),
  ("PrettyPrint::Breakable", []),
  ("PrettyPrint::Group", []),
  ("PrettyPrint::GroupQueue", []),
  ("PrettyPrint::SingleLine", []),
  ("PrettyPrint::Text", []),
  ("SingleForwardable", []),
  ("T", ["AbstractUtils", "Array", "Boolean", "Class", "CompatibilityPatches", "Configuration", "DefMods", "Enum", "Enumerable", "Enumerator", "Generic", "Hash", "Helpers", "ImmutableStruct", "InexactStruct", "Module", "Private", "Props", "Range", "Set", "Sig", "Struct", "Syntax", "Types", "Utils"]),
  ("T::AbstractUtils", ["Methods"]),
  ("T::Array", []),
  ("T::Class", []),
  ("T::CompatibilityPatches", ["MethodExtensions"]),
  ("T::CompatibilityPatches::MethodExtensions", []),
  ("T::Configuration", []),
  ("T::DefMods", []),
  ("T::Enum", ["LegacyMigrationMode"]),
  ("T::Enum::LegacyMigrationMode", []),
  ("T::Enumerable", []),
  ("T::Enumerator", ["Chain", "Lazy"]),
  ("T::Enumerator::Chain", []),
  ("T::Enumerator::Lazy", []),
  ("T::Generic", []),
  ("T::Hash", []),
  ("T::Helpers", ["Private"]),
  ("T::ImmutableStruct", []),
  ("T::InexactStruct", []),
  ("T::Module", []),
  ("T::Private", ["Abstract", "CallerUtils", "Casts", "ClassUtils", "DeclState", "Final", "IS_TYPECHECKING", "Methods", "MixesInClassMethods", "Mixins", "Retry", "RuntimeLevels", "Sealed", "Types"]),
  ("T::Private::Abstract", ["Data", "Declare", "Hooks", "Validate"]),
  ("T::Private::Abstract::Data", []),
  ("T::Private::Abstract::Declare", ["Abstract", "AbstractUtils"]),
  ("T::Private::Abstract::Hooks", []),
  ("T::Private::Abstract::Validate", ["Abstract", "AbstractUtils", "Methods", "SignatureValidation"]),
  ("T::Private::CallerUtils", []),
  ("T::Private::Casts", []),
  ("T::Private::ClassUtils", []),
  ("T::Private::DeclState", []),
  ("T::Private::Final", ["NoIncludeExtend", "NoInherit"]),
  ("T::Private::Final::NoIncludeExtend", []),
  ("T::Private::Final::NoInherit", []),
  ("T::Private::Methods", ["ARG_NOT_PROVIDED", "CallValidation", "DeclBuilder", "Declaration", "DeclarationBlock", "MethodHooks", "Modes", "PROC_TYPE", "Signature", "SignatureValidation", "SingletonMethodHooks", "TOP_SELF"]),
  ("T::Private::Methods::ARG_NOT_PROVIDED", []),
  ("T::Private::Methods::CallValidation", ["CallValidation", "Modes"]),
  ("T::Private::Methods::DeclBuilder", ["BuilderError", "FROZEN_ARRAY", "FROZEN_HASH"]),
  ("T::Private::Methods::DeclBuilder::BuilderError", []),
  ("T::Private::Methods::Declaration", []),
  ("T::Private::Methods::DeclarationBlock", []),
  ("T::Private::Methods::MethodHooks", []),
  ("T::Private::Methods::Modes", ["MODES", "NON_OVERRIDE_MODES", "OVERRIDABLE_MODES", "OVERRIDE_MODES"]),
  ("T::Private::Methods::PROC_TYPE", []),
  ("T::Private::Methods::Signature", ["EMPTY_HASH", "EMPTY_LIST", "UNNAMED_REQUIRED_PARAMETERS"]),
  ("T::Private::Methods::SignatureValidation", ["Methods", "Modes"]),
  ("T::Private::Methods::SingletonMethodHooks", []),
  ("T::Private::MixesInClassMethods", []),
  ("T::Private::Mixins", []),
  ("T::Private::Retry", ["RETRY"]),
  ("T::Private::Retry::RETRY", []),
  ("T::Private::RuntimeLevels", ["LEVELS"]),
  ("T::Private::Sealed", ["NoIncludeExtend", "NoInherit"]),
  ("T::Private::Sealed::NoIncludeExtend", []),
  ("T::Private::Sealed::NoInherit", []),
  ("T::Private::Types", ["NotTyped", "SimplePairUnion", "StringHolder", "TypeAlias", "Void"]),
  ("T::Private::Types::NotTyped", ["ERROR_MESSAGE", "INSTANCE"]),
  ("T::Private::Types::SimplePairUnion", ["DuplicateType"]),
  ("T::Private::Types::SimplePairUnion::DuplicateType", []),
  ("T::Private::Types::StringHolder", []),
  ("T::Private::Types::TypeAlias", []),
  ("T::Private::Types::Void", ["ERROR_MESSAGE", "Private", "VOID"]),
  ("T::Private::Types::Void::Private", ["INSTANCE"]),
  ("T::Private::Types::Void::VOID", []),
  ("T::Props", ["ClassMethods", "Constructor", "CustomType", "Decorator", "Error", "GeneratedCodeValidation", "HasLazilySpecializedMethods", "ImmutableProp", "InvalidValueError", "Optional", "Plugin", "PrettyPrintable", "Private", "Serializable", "TypeValidation", "Utils", "WeakConstructor"]),
  ("T::Props::ClassMethods", []),
  ("T::Props::Constructor", ["DecoratorMethods"]),
  ("T::Props::Constructor::DecoratorMethods", []),
  ("T::Props::CustomType", []),
  ("T::Props::Decorator", ["BANNED_METHOD_NAMES", "DecoratedInstance", "NoRulesError", "OVERRIDE_EMPTY", "OVERRIDE_READER", "OVERRIDE_TRUE", "OVERRIDE_WRITER", "OverrideRules", "PropType", "PropTypeOrClass", "Rules", "SAFE_ACCESSOR_KEY_NAME", "SAFE_NAME"]),
  ("T::Props::Decorator::NoRulesError", []),
  ("T::Props::Error", []),
  ("T::Props::GeneratedCodeValidation", ["ValidationError"]),
  ("T::Props::GeneratedCodeValidation::ValidationError", []),
  ("T::Props::HasLazilySpecializedMethods", ["DecoratorMethods", "SourceEvaluationDisabled"]),
  ("T::Props::HasLazilySpecializedMethods::DecoratorMethods", []),
  ("T::Props::HasLazilySpecializedMethods::SourceEvaluationDisabled", []),
  ("T::Props::ImmutableProp", []),
  ("T::Props::InvalidValueError", []),
  ("T::Props::Optional", ["DecoratorMethods"]),
  ("T::Props::Optional::DecoratorMethods", []),
  ("T::Props::Plugin", ["ClassMethods", "Private"]),
  ("T::Props::Plugin::ClassMethods", []),
  ("T::Props::Plugin::Private", []),
  ("T::Props::PrettyPrintable", ["DecoratorMethods"]),
  ("T::Props::PrettyPrintable::DecoratorMethods", []),
  ("T::Props::Private", ["ApplyComplexDefault", "ApplyDefault", "ApplyDefaultFactory", "ApplyEmptyArrayDefault", "ApplyEmptyHashDefault", "ApplyFixedDefault", "ApplyPrimitiveDefault", "DeserializerGenerator", "Parse", "SerdeTransform", "SerializerGenerator", "SetterFactory"]),
  ("T::Props::Private::ApplyComplexDefault", []),
  ("T::Props::Private::ApplyDefault", ["NO_CLONE_TYPES"]),
  ("T::Props::Private::ApplyDefaultFactory", []),
  ("T::Props::Private::ApplyEmptyArrayDefault", []),
  ("T::Props::Private::ApplyEmptyHashDefault", []),
  ("T::Props::Private::ApplyFixedDefault", []),
  ("T::Props::Private::ApplyPrimitiveDefault", []),
  ("T::Props::Private::DeserializerGenerator", ["CAN_USE_SYMBOL_NAME"]),
  ("T::Props::Private::Parse", []),
  ("T::Props::Private::SerdeTransform", ["Mode"]),
  ("T::Props::Private::SerdeTransform::Mode", ["DESERIALIZE", "SERIALIZE"]),
  ("T::Props::Private::SerializerGenerator", ["CAN_USE_SYMBOL_NAME"]),
  ("T::Props::Private::SetterFactory", ["BoundSetterProc", "SetterProc", "ValidateProc", "ValueValidationProc"]),
  ("T::Props::Serializable", ["ClassMethods", "DecoratorMethods"]),
  ("T::Props::Serializable::ClassMethods", []),
  ("T::Props::Serializable::DecoratorMethods", []),
  ("T::Props::TypeValidation", ["BANNED_TYPES", "DecoratorMethods", "UnderspecifiedType"]),
  ("T::Props::TypeValidation::DecoratorMethods", []),
  ("T::Props::TypeValidation::UnderspecifiedType", []),
  ("T::Props::Utils", []),
  ("T::Props::WeakConstructor", ["DecoratorMethods"]),
  ("T::Props::WeakConstructor::DecoratorMethods", []),
  ("T::Range", []),
  ("T::Set", []),
  ("T::Sig", ["WithoutRuntime"]),
  ("T::Sig::WithoutRuntime", []),
  ("T::Struct", []),
  ("T::Syntax", []),
  ("T::Types", ["Anything", "AttachedClassType", "Base", "ClassOf", "Enum", "FixedArray", "FixedHash", "Intersection", "NoReturn", "Proc", "SelfType", "Simple", "TEnum", "TypeMember", "TypeParameter", "TypeTemplate", "TypeVariable", "TypedArray", "TypedClass", "TypedEnumerable", "TypedEnumerator", "TypedEnumeratorChain", "TypedEnumeratorLazy", "TypedHash", "TypedModule", "TypedRange", "TypedSet", "Union", "Untyped"]),
  ("T::Types::Anything", ["Private"]),
  ("T::Types::Anything::Private", ["INSTANCE"]),
  ("T::Types::AttachedClassType", ["Private"]),
  ("T::Types::AttachedClassType::Private", ["INSTANCE"]),
  ("T::Types::Base", []),
  ("T::Types::ClassOf", []),
  ("T::Types::Enum", []),
  ("T::Types::FixedArray", []),
  ("T::Types::FixedHash", []),
  ("T::Types::Intersection", []),
  ("T::Types::NoReturn", ["Private"]),
  ("T::Types::NoReturn::Private", ["INSTANCE"]),
  ("T::Types::Proc", []),
  ("T::Types::SelfType", ["Private"]),
  ("T::Types::SelfType::Private", ["INSTANCE"]),
  ("T::Types::Simple", ["Private"]),
  ("T::Types::Simple::Private", ["Pool"]),
  ("T::Types::Simple::Private::Pool", ["CACHE_FROZEN_OBJECTS"]),
  ("T::Types::TEnum", []),
  ("T::Types::TypeMember", []),
  ("T::Types::TypeParameter", ["Private"]),
  ("T::Types::TypeParameter::Private", []),
  ("T::Types::TypeTemplate", []),
  ("T::Types::TypeVariable", ["VALID_VARIANCES"]),
  ("T::Types::TypedArray", ["Private", "Untyped"]),
  ("T::Types::TypedArray::Private", ["Pool"]),
  ("T::Types::TypedArray::Private::Pool", ["CACHE_FROZEN_OBJECTS"]),
  ("T::Types::TypedArray::Untyped", ["Private"]),
  ("T::Types::TypedArray::Untyped::Private", ["INSTANCE"]),
  ("T::Types::TypedClass", ["Anything", "Private", "Untyped"]),
  ("T::Types::TypedClass::Anything", ["Private"]),
  ("T::Types::TypedClass::Anything::Private", ["INSTANCE"]),
  ("T::Types::TypedClass::Private", ["Pool"]),
  ("T::Types::TypedClass::Private::Pool", ["CACHE_FROZEN_OBJECTS"]),
  ("T::Types::TypedClass::Untyped", ["Private"]),
  ("T::Types::TypedClass::Untyped::Private", ["INSTANCE"]),
  ("T::Types::TypedEnumerable", ["Untyped"]),
  ("T::Types::TypedEnumerable::Untyped", []),
  ("T::Types::TypedEnumerator", ["Untyped"]),
  ("T::Types::TypedEnumerator::Untyped", []),
  ("T::Types::TypedEnumeratorChain", ["Untyped"]),
  ("T::Types::TypedEnumeratorChain::Untyped", []),
  ("T::Types::TypedEnumeratorLazy", ["Untyped"]),
  ("T::Types::TypedEnumeratorLazy::Untyped", []),
  ("T::Types::TypedHash", ["Untyped"]),
  ("T::Types::TypedHash::Untyped", ["Private"]),
  ("T::Types::TypedHash::Untyped::Private", ["INSTANCE"]),
  ("T::Types::TypedModule", ["Anything", "Private", "Untyped"]),
  ("T::Types::TypedModule::Anything", ["Private"]),
  ("T::Types::TypedModule::Anything::Private", ["INSTANCE"]),
  ("T::Types::TypedModule::Private", ["Pool"]),
  ("T::Types::TypedModule::Private::Pool", ["CACHE_FROZEN_OBJECTS"]),
  ("T::Types::TypedModule::Untyped", ["Private"]),
  ("T::Types::TypedModule::Untyped::Private", ["INSTANCE"]),
  ("T::Types::TypedRange", ["Untyped"]),
  ("T::Types::TypedRange::Untyped", []),
  ("T::Types::TypedSet", ["Untyped"]),
  ("T::Types::TypedSet::Untyped", []),
  ("T::Types::Union", ["Private"]),
  ("T::Types::Union::Private", ["Pool"]),
  ("T::Types::Union::Private::Pool", []),
  ("T::Types::Untyped", ["Private"]),
  ("T::Types::Untyped::Private", ["INSTANCE"]),
  ("T::Utils", ["Nilable", "Private"]),
  ("T::Utils::Nilable", ["NIL_TYPE", "TypeInfo"]),
  ("T::Utils::Nilable::TypeInfo", []),
  ("T::Utils::Private", []),
  ("URI", ["ABS_PATH", "BadURIError", "DEFAULT_PARSER", "Error", "FRAGMENT", "FTP", "File", "Generic", "HOST", "HTTP", "HTTPS", "InvalidComponentError", "InvalidURIError", "LDAP", "LDAPS", "MailTo", "OPAQUE", "PARSER", "PORT", "Parser", "QUERY", "REL_PATH", "RFC2396_PARSER", "RFC2396_Parser", "RFC2396_REGEXP", "RFC3986_PARSER", "RFC3986_Parser", "SCHEME", "TBLDECWWWCOMP_", "TBLENCURICOMP_", "TBLENCWWWCOMP_", "USERINFO", "Util", "VERSION", "VERSION_CODE", "WEB_ENCODINGS_", "WS", "WSS"]),
  ("URI::BadURIError", []),
  ("URI::Error", []),
  ("URI::FTP", ["COMPONENT", "DEFAULT_PORT", "TYPECODE", "TYPECODE_PREFIX"]),
  ("URI::File", ["COMPONENT", "DEFAULT_PORT"]),
  ("URI::Generic", ["COMPONENT", "DEFAULT_PORT", "USE_REGISTRY"]),
  ("URI::HTTP", ["COMPONENT", "DEFAULT_PORT"]),
  ("URI::HTTPS", ["DEFAULT_PORT"]),
  ("URI::InvalidComponentError", []),
  ("URI::InvalidURIError", []),
  ("URI::LDAP", ["COMPONENT", "DEFAULT_PORT", "SCOPE", "SCOPE_BASE", "SCOPE_ONE", "SCOPE_SUB"]),
  ("URI::LDAPS", ["DEFAULT_PORT"]),
  ("URI::MailTo", ["COMPONENT", "DEFAULT_PORT", "EMAIL_REGEXP", "HEADER_REGEXP"]),
  ("URI::RFC2396_Parser", ["TO_S"]),
  ("URI::RFC2396_REGEXP", ["PATTERN"]),
  ("URI::RFC2396_REGEXP::PATTERN", ["ABS_PATH", "ABS_URI", "ALNUM", "ALPHA", "DOMLABEL", "ESCAPED", "FRAGMENT", "HEX", "HIER_PART", "HOST", "HOSTNAME", "HOSTPORT", "IPV4ADDR", "IPV6ADDR", "IPV6REF", "NET_PATH", "OPAQUE_PART", "PATH_SEGMENTS", "PORT", "QUERY", "REG_NAME", "REL_PATH", "REL_SEGMENT", "REL_URI", "RESERVED", "SCHEME", "TOPLABEL", "UNRESERVED", "URIC", "URIC_NO_SLASH", "URI_REF", "USERINFO", "X_ABS_URI", "X_REL_URI"]),
  ("URI::RFC3986_Parser", ["FRAGMENT", "HOST", "RFC3986_URI", "RFC3986_relative_ref", "SCHEME", "SEG", "SEG_NC", "USERINFO"]),
  ("URI::Util", []),
  ("URI::WS", ["COMPONENT", "DEFAULT_PORT"]),
  ("URI::WSS", ["DEFAULT_PORT"])
]

def crubyClassDefines (className mname : String) : Bool :=
  match crubyMethodNames.find? (·.1 == className) with
  | some (_, names) => names.contains mname
  | none => false

def crubySingletonDefines (className mname : String) : Bool :=
  match crubySingletonNames.find? (·.1 == className) with
  | some (_, names) => names.contains mname
  | none => false

end RubyCore
