#!/usr/bin/env bash
# Build this package's executables for `wasm32-wasip1`, to be run in a browser
# with no server behind them.
#
#   wasm/build.sh                 # everything
#   wasm/build.sh validate-one    # one target
#
# ── What this is and is not ──────────────────────────────────────────────────
#
# It is *not* a port of the Lean compiler to wasm, which is what every prior
# attempt has meant by "Lean in the browser" and which costs a patched fork and
# a ~100 MB artifact. Nothing here runs `lean`; it compiles the C that `lake`
# and `lean -c` already emit. Three facts make that cheap:
#
#   1. `lake build` leaves this package's generated C in `.lake/build/ir/`.
#   2. The toolchain ships no C for `Init`/`Std` -- but it ships their `.lean`
#      sources and `.olean`s, and the native `lean -c` regenerates that C from
#      them in about 80 seconds for all 1,077 modules. No bootstrap.
#   3. The runtime is 26 `.cpp` files, already written for a target with no
#      libuv, no OpenSSL, no threads and no process spawning -- that is what
#      `LEAN_EMSCRIPTEN` selects. `wasm/patch-runtime.py` is the five-edit
#      remainder.
#
# GMP is not needed and not built: undefining `LEAN_USE_GMP` selects the
# runtime's own `mpn.cpp` bignums, which are plain C++.
#
# ── Why WASI rather than emscripten ──────────────────────────────────────────
#
# These executables are stdin -> stdout filters. Emscripten's pthread build
# needs `SharedArrayBuffer`, which needs COOP/COEP response headers, which
# GitHub Pages cannot send. `wasm32-wasip1` is single-threaded and needs no
# headers; in the browser it runs under a WASI shim with stdin and stdout
# wired to strings.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG="$(dirname "$HERE")"                      # ruby-lean/
CACHE="${RUBYLEAN_WASM_CACHE:-$HOME/.cache/ruby-lean-wasm}"
TARGETS="${*:-}"

LEAN_VERSION="$(sed 's|.*:||' "$PKG/lean-toolchain")"          # e.g. v4.32.2
TOOLCHAIN="$HOME/.elan/toolchains/leanprover--lean4---${LEAN_VERSION//./---}"
# elan spells the directory with the version dotted, not dashed:
TOOLCHAIN="$HOME/.elan/toolchains/leanprover--lean4---$LEAN_VERSION"
WASI_SDK="${WASI_SDK:-$HOME/wasm-tools/wasi-sdk-34.0-arm64-macos}"

LEAN_SRC="$CACHE/lean4-${LEAN_VERSION#v}/src"
B="$CACHE/build"
OUT="$HERE/out"

CC="$WASI_SDK/bin/clang"
CXX="$WASI_SDK/bin/clang++"
AR="$WASI_SDK/bin/llvm-ar"
SYSROOT="$WASI_SDK/share/wasi-sysroot"
JOBS="$(sysctl -n hw.ncpu 2>/dev/null || nproc)"

# Standard wasm exception handling, not the legacy encoding clang still defaults
# to -- wasmtime 48 and current browsers want `try_table`.
EH=(-fwasm-exceptions -mllvm -wasm-use-legacy-eh=false)
# What WASI provides only under emulation. All are link-time shims in the SDK.
EMU=(-D_WASI_EMULATED_MMAN -D_WASI_EMULATED_SIGNAL
     -D_WASI_EMULATED_PROCESS_CLOCKS -D_WASI_EMULATED_GETPID)
EMULIBS=(-lwasi-emulated-mman -lwasi-emulated-signal
         -lwasi-emulated-process-clocks -lwasi-emulated-getpid)
# The stack the shim reports to `runtime/stackinfo.cpp` must be the stack we
# actually link with, or the overflow guard measures a stack that is not there.
STACK_SIZE=8388608

say() { printf '\033[1m==>\033[0m %s\n' "$*"; }

# ── 0. preconditions ─────────────────────────────────────────────────────────
[ -x "$CXX" ] || { echo "no wasi-sdk at $WASI_SDK (set \$WASI_SDK)"; exit 1; }
[ -d "$TOOLCHAIN" ] || { echo "no Lean toolchain at $TOOLCHAIN"; exit 1; }
[ -d "$PKG/.lake/build/ir" ] || { echo "run \`lake build\` in $PKG first"; exit 1; }
mkdir -p "$B"/{rt,leanobj,projobj,leanc/c,leanc/err} "$OUT"

# ── 1. Lean source, for the runtime only ─────────────────────────────────────
if [ ! -d "$LEAN_SRC/runtime" ]; then
  say "fetching Lean $LEAN_VERSION sources (runtime C++ only; ~75 MB)"
  mkdir -p "$CACHE"
  curl -fsSL -o "$CACHE/lean4-src.tar.gz" \
    "https://github.com/leanprover/lean4/archive/refs/tags/$LEAN_VERSION.tar.gz"
  tar xzf "$CACHE/lean4-src.tar.gz" -C "$CACHE"
fi
say "patching the runtime for WASI"
python3 "$HERE/patch-runtime.py" "$LEAN_SRC"

# ── 2. the headers cmake would have generated ────────────────────────────────
# Checked in under wasm/gen/ rather than substituted here: there are four
# values and all four are fixed for this build.
GEN="$HERE/gen"

# ── 3. Init/Std C, regenerated by the native lean ────────────────────────────
MODS="$B/leanc/modules.txt"
if [ ! -s "$MODS" ]; then
  (cd "$TOOLCHAIN/src/lean" && { echo Init; echo Std;
     find Init Std -name '*.lean' | sed 's/\.lean$//'; } | sort -u) > "$MODS"
fi
NMODS=$(wc -l < "$MODS" | tr -d ' ')
if [ "$(ls "$B/leanc/c" | wc -l | tr -d ' ')" -lt "$NMODS" ]; then
  say "regenerating C for $NMODS Init/Std modules with the native lean"
  export TOOLCHAIN B
  # shellcheck disable=SC2016
  xargs -P "$JOBS" -I{} bash -c '
    out="$B/leanc/c/$(echo "{}" | tr / .).c"
    [ -s "$out" ] && exit 0
    cd "$TOOLCHAIN/src/lean" &&
    LEAN_PATH="$TOOLCHAIN/lib/lean" "$TOOLCHAIN/bin/lean" -c "$out" "{}.lean" \
      || { echo "FAIL {}"; exit 1; }' < "$MODS"
fi

# ── 4. compile ───────────────────────────────────────────────────────────────
# -DNDEBUG matches how `leanc` compiles a release build. Without it the
# runtime keeps its internal `assert`s, which is worth a run when something
# looks wrong but is not the configuration the native binaries are built in.
cflags=(-O2 -DNDEBUG "${EH[@]}" "${EMU[@]}" -I"$HERE/shim" -I"$LEAN_SRC/include" -I"$GEN")
cxxflags=(-std=c++20 -DLEAN_EMSCRIPTEN "${cflags[@]}" -I"$LEAN_SRC")

# Each stage drives `xargs -P` over a generated one-file-at-a-time wrapper.
# Wrappers rather than an inline `sh -c`, for two reasons: macOS ships bash 3.2
# (no `wait -n`, no `mapfile`) and BSD xargs refuses a long `-I` template
# ("command line cannot be assembled, too long").
mkcc() {  # mkcc <path> <compiler> <flags...>
  local out="$1" cc="$2"; shift 2
  { printf '#!/bin/sh\n# generated by wasm/build.sh\nexec "%s"' "$cc"
    printf ' "%s"' "$@"
    printf ' -c "$1" -o "$2"\n'; } > "$out"
  chmod +x "$out"
}
mkcc "$B/cc.sh"  "$CC"  "${cflags[@]}"
mkcc "$B/cxx.sh" "$CXX" "${cxxflags[@]}"

cat > "$B/one-rt.sh" <<EOF
#!/bin/sh
# generated by wasm/build.sh -- one runtime translation unit
o="$B/rt/\$1.o"
[ "\$o" -nt "$LEAN_SRC/runtime/\$1.cpp" ] && exit 0
cd "$LEAN_SRC" || exit 1
exec "$B/cxx.sh" "runtime/\$1.cpp" "\$o"
EOF
cat > "$B/one-lean.sh" <<EOF
#!/bin/sh
# generated by wasm/build.sh -- one generated-C module
o="$B/\$2/\$(basename "\$1" .c | tr / .).o"
[ "\$o" -nt "\$1" ] && exit 0
exec "$B/cc.sh" "\$1" "\$o"
EOF
cat > "$B/one-proj.sh" <<EOF
#!/bin/sh
# generated by wasm/build.sh -- one module of this package
rel=\$(echo "\$1" | sed "s|^$PKG/.lake/build/ir/||")
o="$B/projobj/\$(echo "\${rel%.c}" | tr / .).o"
[ "\$o" -nt "\$1" ] && exit 0
exec "$B/cc.sh" "\$1" "\$o"
EOF
chmod +x "$B"/one-rt.sh "$B"/one-lean.sh "$B"/one-proj.sh

say "compiling the Lean runtime (26 translation units)"
for f in debug thread mpz utf8 object apply exception interrupt memory stackinfo \
         compact init_module io hash byteslice platform alloc allocprof \
         sharecommon object_ref mpn mutex libuv openssl; do echo "$f"; done \
  | xargs -P "$JOBS" -n 1 "$B/one-rt.sh"
# `process.cpp` and `stack_overflow.cpp` are replaced, not compiled; the shim
# says why. `uv_shim.c` is the synchronous-filesystem half of libuv.
"$B/cc.sh" "$HERE/shim/uv_shim.c" "$B/rt/uv_shim.o"
"$CXX" "${cxxflags[@]}" -c "$HERE/shim/wasi_stubs.cpp" -o "$B/rt/wasi_stubs.o"
"$AR" crs "$B/libleanrt.a" "$B"/rt/*.o

say "compiling Init/Std ($NMODS modules)"
ls "$B"/leanc/c/*.c | xargs -P "$JOBS" -n 1 -I F "$B/one-lean.sh" F leanobj
"$AR" crs "$B/libleanstd.a" "$B"/leanobj/*.o

NPROJ=$(find "$PKG/.lake/build/ir" -name '*.c' | wc -l | tr -d ' ')
say "compiling this package ($NPROJ modules)"
find "$PKG/.lake/build/ir" -name '*.c' | xargs -P "$JOBS" -n 1 "$B/one-proj.sh"

# ── 5. link ──────────────────────────────────────────────────────────────────
# The `eh` sysroot variant is not selected by -fwasm-exceptions on its own.
link() {
  local target="$1"; shift
  say "linking $target"
  "$CXX" -O2 "${EH[@]}" -o "$OUT/$target.wasm" "$@" \
    -L"$B" -lleanstd -lleanrt \
    -L"$SYSROOT/lib/wasm32-wasip1/eh" -lc++abi -lunwind \
    "${EMULIBS[@]}" -Wl,-z,stack-size=$STACK_SIZE
  printf '    %s  %.2f MB\n' "$OUT/$target.wasm" \
    "$(echo "$(stat -f%z "$OUT/$target.wasm" 2>/dev/null || stat -c%s "$OUT/$target.wasm") / 1048576" | bc -l)"
}

TARGETS="${*:-}"
want() { [ -z "$TARGETS" ] || [[ " $TARGETS " == *" $1 "* ]]; }

# `validate-one` is the trusted one: `validateD`, the Bool the safety theorem is
# stated about. Its closure is Ratchet/ and the vendored Json/ and nothing else.
if want validate-one; then
  link validate-one "$B"/projobj/MainValidateOne.o "$B"/projobj/Json.o \
       "$B"/projobj/Json.*.o "$B"/projobj/Ratchet.*.o "$B"/rt/wasi_stubs.o
fi

# `rubycore` is the model: the stepper's `--trace`, and the static queries.
if want rubycore; then
  link rubycore "$B"/projobj/Main.o "$B"/projobj/Json.o "$B"/projobj/Json.*.o \
       "$B"/projobj/RubyCore.*.o "$B"/rt/wasi_stubs.o
fi

say "done -- artifacts in wasm/out/"
