import Denote.Clink.Registry

/-!
# `Denote/Adequacy.lean` — adequacy over the *authoring surface*, and why it is no longer the plan

**Adequacy**: every syntactic derivation is semantically true. Over the certified judgment
that is `registry_sound`, it is **proved**, and it was proved when the registry had one rule
in it (`Denote/Clink/Spec.lean`). Over `Ratchet.Judge` — the authoring surface, 83
constructors, 35 of them with no proof — it is `AdequacyTarget` below, and this file exists
to say exactly what that statement is now worth.

## What this file used to be, and what went wrong with it

It used to hold `AdequacyHyps`: the conjunction of all 83 derived obligations, generated by
folding over the constructor list, together with the plan *`AdequacyHyps → AdequacyTarget` is
the terminal clink — the mutual induction, whose every case is one projection out of the
hypothesis.* Three things were wrong with that plan, and they were the same thing:

1. **It could only be taken at 83/83.** "An induction with 80 cases filled in proves nothing
   — there is no partial credit in a `Judge.rec` application", as the old docstring correctly
   said. So the only theorem tying the 48 proved obligations to anything was unavailable, and
   stayed unavailable for the whole life of the ladder.
2. **Meanwhile the rules were already in the judgment.** `Judge.if'` types every conditional
   in the corpus and has no semantic proof; under the old arrangement that was a line in a
   report. A certificate checked against `Judge` was checked against it.
3. **Seven of the 35 turned out false as stated** (§F19/§F23/§F24). An arrangement in which a
   rule is admitted first and justified later cannot notice that, because there is no step at
   which anything is checked.

The reshape inverts the dependency: the judgment is *generated from* the proved rules, so
adequacy is a one-line consequence at every size and the unproved rules are simply outside.
`AdequacyHyps` and the fold that built it are deleted — what replaced them is
`Denote/Clink/Spec.lean`'s `Closed`/`JudgeC` pair, where the same 48 proofs are the `sem`
fields of 48 clinks and the conjunction is `Closed clinks semFam`, proved by
`closed_semFam` in one line for any registry.

## What `AdequacyTarget` is still good for

One thing, and it is worth keeping a name for: it is the statement that would let the checker
target `Judge` instead of `JudgeC`. Today `Ratchet/Validate.lean` and `Ratchet/Deriv.lean`
still do target `Judge`, which is why the coverage column in `lake exe semladder` matters —
it bounds what can be certified *soundly*. Closing the gap has two routes and they are not
equivalent:

* **Grow the registry** (write the 35 `Sem.*` proofs, one at a time, each joining `JudgeC` on
  the next build). Monotone, no cliff, and each step is independently useful. This is the plan.
* **Prove `AdequacyTarget`** (one 83-case mutual induction). Equivalent in strength to the
  first once the registry is complete, strictly weaker as a *process*, and it is the thing
  that failed. Recorded here so nobody rediscovers it as an idea.

And a fact worth keeping in view: `AdequacyTarget` is currently **false-or-unprovable in a
way nobody has measured**, because at least seven of the 35 rules have obligations known to
be false as stated. So it is not merely undone; a rule list containing a false rule cannot
have an adequacy theorem at all. That is the sharpest argument for generating the judgment
from the proofs rather than the other way round.
-/

set_option autoImplicit false

namespace Ratchet.Denote

/-- **Adequacy of the authoring surface.** Eight implications, one per member of
`Ratchet/Judge.lean`'s mutual family.

Not proved, and — unlike everything else in this package that is not proved — not *owed*.
See the module docstring: the reachable form of this statement is `registry_sound`, which is
proved, and the route to covering all of `Judge` is to grow the registry rather than to prove
this. Kept as a named `Prop` because `HANDOFF.md`'s working rule says to write a layer's
target down before proving anything under it, and because the checker targeting `Judge`
rather than `JudgeC` is *exactly* the assumption this states. -/
def AdequacyTarget : Prop :=
  (∀ κ Γ I e τ κ' Γ' I', Judge κ Γ I e τ κ' Γ' I' → SemJudge κ Γ I e τ κ' Γ' I') ∧
  (∀ κ Γ I es τs Γ' I', JudgeAll κ Γ I es τs Γ' I' → SemJudgeAll κ Γ I es τs Γ' I') ∧
  (∀ κ Γ I es kws Γ' I', JudgeKw κ Γ I es kws Γ' I' → SemJudgeKw κ Γ I es kws Γ' I') ∧
  (∀ κ Γ I ps kr vr Γ' I',
      JudgePairs κ Γ I ps kr vr Γ' I' → SemJudgePairs κ Γ I ps kr vr Γ' I') ∧
  (∀ κ Γ I es τ κ' Γ' I', JudgeSeq κ Γ I es τ κ' Γ' I' → SemJudgeSeq κ Γ I es τ κ' Γ' I') ∧
  (∀ κ Γ I rs τ, JudgeRescues κ Γ I rs τ → SemJudgeRescues κ Γ I rs τ) ∧
  (∀ κ cs, JudgeConsts κ cs → SemJudgeConsts κ cs) ∧
  (∀ κ pfx nst, JudgeNested κ pfx nst → SemJudgeNested κ pfx nst)

/-- **`AdequacyTarget` is what the certified judgment already gives, on the nose, for the
rules it has.** One direction of the comparison is a theorem (this one); the other is
`AdequacyTarget` itself. Stating it makes the relationship checkable rather than argued:
`JudgeC clinks` is a sub-judgment of `Judge` (`registry_syn`) whose derivations are
semantically true (`registry_sound`), and `AdequacyTarget` is the claim that the inclusion
can be reversed. -/
theorem registry_target_fragment {κ Γ I e τ κ' Γ' I'}
    (h : (JudgeC clinks).judge κ Γ I e τ κ' Γ' I') :
    Judge κ Γ I e τ κ' Γ' I' ∧ SemJudge κ Γ I e τ κ' Γ' I' :=
  ⟨registry_syn h, registry_sound h⟩

/-- And the converse direction, named: if the authoring surface were adequate, the checker
could target it. This is the *only* consumer `AdequacyTarget` has, and writing it down is how
the assumption `Ratchet/Validate.lean` currently runs on becomes visible. -/
theorem semJudge_of_judge_of_adequate (h : AdequacyTarget) {κ Γ I e τ κ' Γ' I'}
    (hj : Judge κ Γ I e τ κ' Γ' I') : SemJudge κ Γ I e τ κ' Γ' I' :=
  h.1 κ Γ I e τ κ' Γ' I' hj

#print axioms registry_target_fragment
#print axioms semJudge_of_judge_of_adequate

end Ratchet.Denote
