# typed: true
# Generated by ratchet/scripts/build_slice_rungs.py — do not edit, regenerate.
# boot stubs: difftest/tiers/tier0/rspec_harvest.py (SORBET_REQUIRE, BLANK_STUB,
#             PATHNAME_STEM_STUB, OUTPUT_STUB) + require "forwardable"
#             + BLANK_NIL_STUB (extend/blank/{nil_class,false_class}.rb)
# library:    1 file(s) linked from vulns/cvss.rb; 0 external, 0 cycles
# driver:     ratchet/slice/drivers/cvss.rb
require "sorbet-runtime"
class Module
  include T::Sig
end
require "pathname"
require "uri"
require "forwardable"

class Object
  sig { returns(T::Boolean) }
  def blank?
    respond_to?(:empty?) ? !!empty? : false
  end

  sig { returns(T::Boolean) }
  def present? = !blank?

  sig { returns(T.nilable(T.self_type)) }
  def presence = present? ? self : nil
end

class NilClass
  sig { returns(TrueClass) }
  def blank? = true

  sig { returns(FalseClass) }
  def present? = false
end

class FalseClass
  sig { returns(TrueClass) }
  def blank? = true

  sig { returns(FalseClass) }
  def present? = false
end

class Pathname
  sig { returns(String) }
  def stem
    File.basename(self, extname)
  end
end

module Utils
  module Output
    module Mixin
      # See difftest/implementation-notes.md N36: upstream `odebug` returns
      # early unless debug is enabled and otherwise writes to stderr, neither of
      # which is observable here.
      # The sig is upstream's, verbatim (`utils/output.rb:32`) — see N48: a stub
      # without one is a `missing-sig` row in `--fragment` for a method that *is*
      # annotated upstream, i.e. our bug rather than the slice's.
      sig { params(title: T.any(String, Exception), sput: T.anything, always_display: T::Boolean).void }
      def odebug(title, *sput, always_display: false)
        nil
      end
    end
  end
end
# Linked by ruby/linker. Do not edit — regenerate.
# platform: generic
# entries: vulns/cvss.rb
# files: 1 (1 spliced, 0 thunked)
# >>> linked: vulns/cvss.rb
# typed: strict
# frozen_string_literal: true

module Homebrew
  module Vulns
    # CVSS v3.0/v3.1 base score and qualitative severity rating.
    # See https://www.first.org/cvss/v3-1/specification-document.
    # v2 and v4.0 vectors return `nil` so callers fall through to the next
    # available severity source.
    module CVSS
      AV = T.let({ "N" => 0.85, "A" => 0.62, "L" => 0.55, "P" => 0.2 }.freeze, T::Hash[String, Float])
      AC = T.let({ "L" => 0.77, "H" => 0.44 }.freeze, T::Hash[String, Float])
      UI = T.let({ "N" => 0.85, "R" => 0.62 }.freeze, T::Hash[String, Float])
      CIA = T.let({ "N" => 0.0, "L" => 0.22, "H" => 0.56 }.freeze, T::Hash[String, Float])
      PR_UNCHANGED = T.let({ "N" => 0.85, "L" => 0.62, "H" => 0.27 }.freeze, T::Hash[String, Float])
      PR_CHANGED = T.let({ "N" => 0.85, "L" => 0.68, "H" => 0.50 }.freeze, T::Hash[String, Float])
      private_constant :AV, :AC, :UI, :CIA, :PR_UNCHANGED, :PR_CHANGED

      BASE_METRICS = %w[AV AC PR UI S C I A].freeze
      private_constant :BASE_METRICS

      sig { params(vector: String).returns(T.nilable(Float)) }
      def self.base_score(vector)
        metrics = parse(vector)
        return if metrics.nil?

        scope_changed = metrics.fetch("S") == "C"
        pr_table = scope_changed ? PR_CHANGED : PR_UNCHANGED

        av  = AV.fetch(metrics.fetch("AV"))
        ac  = AC.fetch(metrics.fetch("AC"))
        pr  = pr_table.fetch(metrics.fetch("PR"))
        ui  = UI.fetch(metrics.fetch("UI"))
        c   = CIA.fetch(metrics.fetch("C"))
        i   = CIA.fetch(metrics.fetch("I"))
        a   = CIA.fetch(metrics.fetch("A"))

        iss = 1 - ((1 - c) * (1 - i) * (1 - a))
        impact = if scope_changed
          (7.52 * (iss - 0.029)) - (3.25 * ((iss - 0.02)**15))
        else
          6.42 * iss
        end
        return 0.0 if impact <= 0

        exploitability = 8.22 * av * ac * pr * ui
        raw = impact + exploitability
        raw *= 1.08 if scope_changed
        round_up([raw, 10.0].min)
      end

      sig { params(vector: String).returns(T.nilable(Symbol)) }
      def self.severity(vector)
        score = base_score(vector)
        return if score.nil?

        if score >= 9.0 then :critical
        elsif score >= 7.0 then :high
        elsif score >= 4.0 then :medium
        elsif score > 0.0 then :low
        end
      end

      SUPPORTED_PREFIXES = %w[CVSS:3.0 CVSS:3.1].freeze
      private_constant :SUPPORTED_PREFIXES

      sig { params(vector: String).returns(T.nilable(T::Hash[String, String])) }
      private_class_method def self.parse(vector)
        parts = vector.split("/")
        return unless SUPPORTED_PREFIXES.include?(parts.shift)

        metrics = parts.to_h do |part|
          pair = part.split(":", 2)
          [pair[0] || "", pair[1] || ""]
        end
        return unless BASE_METRICS.all? { |m| metrics.key?(m) }
        return unless valid_values?(metrics)

        metrics
      end

      sig { params(metrics: T::Hash[String, String]).returns(T::Boolean) }
      private_class_method def self.valid_values?(metrics)
        AV.key?(metrics.fetch("AV")) &&
          AC.key?(metrics.fetch("AC")) &&
          PR_UNCHANGED.key?(metrics.fetch("PR")) &&
          UI.key?(metrics.fetch("UI")) &&
          %w[U C].include?(metrics.fetch("S")) &&
          CIA.key?(metrics.fetch("C")) &&
          CIA.key?(metrics.fetch("I")) &&
          CIA.key?(metrics.fetch("A"))
      end

      # CVSS v3.x "Roundup" (spec Appendix A).
      sig { params(value: Float).returns(Float) }
      private_class_method def self.round_up(value)
        int = (value * 100_000).round
        return int / 100_000.0 if (int % 10_000).zero?

        ((int / 10_000) + 1) / 10.0
      end
    end
  end
end

# <<< end: vulns/cvss.rb

# Driver for `vulns/cvss.rb` — CVSS v3.x base score and qualitative severity,
# exercised the way `Vulnerability#extract_severity` exercises it: one vector
# string in, a `[score, severity]` pair out.
#
# The vectors are the FIRST specification's own worked examples plus the
# boundary cases of the four severity bands, so the arithmetic (Float, `**`,
# the Roundup of Appendix A) is pinned at values a reader can check against the
# spec rather than against our own output.

def show(label)
  puts("#{label} => #{yield.inspect}")
rescue StandardError => e
  puts("#{label} => #{e.class}: #{e.message}")
end

C = Homebrew::Vulns::CVSS

puts("== base_score / severity, over real vectors")
[
  # the spec's CVE-2015-8252 example: 9.8 CRITICAL
  "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
  # scope changed — the 1.08 multiplier and the changed privileges table
  "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
  "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:L/I:L/A:N",
  # every band boundary
  "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
  "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:L/I:L/A:N",
  "CVSS:3.1/AV:P/AC:H/PR:H/UI:R/S:U/C:L/I:N/A:N",
  # zero impact short-circuits before exploitability is even computed
  "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N",
  # 3.0 is accepted on the same table as 3.1
  "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
].each { |v| show("  #{v}") { [C.base_score(v), C.severity(v)] } }

puts
puts("== unsupported and malformed vectors answer nil, not a raise")
# The contract the caller depends on: `extract_severity` walks several severity
# entries and needs `nil` to mean "try the next one".
[
  "CVSS:2.0/AV:N/AC:L/Au:N/C:P/I:P/A:P",          # v2 — out of scope by design
  "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H",
  "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H",     # a base metric missing
  "CVSS:3.1/AV:X/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", # a value outside the table
  "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:X/C:H/I:H/A:H", # scope is neither U nor C
  "AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",          # no prefix
  "garbage",
  "",
].each { |v| show("  #{v.empty? ? '(empty)' : v}") { [C.base_score(v), C.severity(v)] } }

puts
puts("== the score is monotone in each metric it should be monotone in")
def score(av:, ac: "L", pr: "N", ui: "N", s: "U", c: "H", i: "H", a: "H")
  Homebrew::Vulns::CVSS.base_score("CVSS:3.1/AV:#{av}/AC:#{ac}/PR:#{pr}/UI:#{ui}/S:#{s}/C:#{c}/I:#{i}/A:#{a}")
end

show("attack vector N > A > L > P") { ["N", "A", "L", "P"].map { |av| score(av:) } }
show("privileges N > L > H")       { ["N", "L", "H"].map { |pr| score(av: "N", pr:) } }
show("confidentiality H > L > N")  { ["H", "L", "N"].map { |c| score(av: "N", c:, i: "N", a: "N") } }

puts
puts("== Roundup (spec Appendix A) never rounds a score down")
show("severity bands are ordered") do
  scores = ["N", "A", "L", "P"].map { |av| score(av:) }
  scores == scores.sort.reverse
end
