/-
GENERATED by `scripts/gen_prelude.rb` from `prelude/prelude.rb` — do not edit.

The **prelude**: the part of Ruby's core library that is modeled *in RubyCore
itself* rather than as Lean primitives (L62). Phase 1 of the boot runs this
program from H₀ with `preludeMode := true` (so its `def`s are marked
`fromPrelude`); phase 2 runs the program under test on the resulting heap
(`Machine.initOn`).

Carried as the desugared RubyCore **JSON**, decoded by the ordinary
`Decode.program`: there is exactly one AST encoding in the system, so the
prelude cannot drift from the export format the difftest harness validates.
-/
import RubyCore.Syntax

namespace RubyCore
namespace Prelude

/-- The desugared prelude, as exported RubyCore JSON (`Export::VERSION` 4). -/
def json : String := String.join [
  "{\"v\":4,\"ast\":[\"module\",\"Comparable\",[\"seq\",[\"def\",\"<\",[[\"preq\",\"other\"]],[\"se",
  "q\",[\"vasgn\",\"local\",\"c\",[\"send\",[\"self\"],\"<=>\",[[\"var\",\"local\",\"other\"]],null",
  "]],[\"if\",[\"send\",[\"var\",\"local\",\"c\"],\"nil?\",[],null],[\"return\",[\"send\",null,\"__",
  "unsupported__\",[[\"str\",\"Comparable#< with a nil <=>\"]],null]],null],[\"send\",[\"var\",\"lo",
  "cal\",\"c\"],\"<\",[[\"int\",0]],null]]],[\"def\",\"<=\",[[\"preq\",\"other\"]],[\"seq\",[\"vasg",
  "n\",\"local\",\"c\",[\"send\",[\"self\"],\"<=>\",[[\"var\",\"local\",\"other\"]],null]],[\"if\",",
  "[\"send\",[\"var\",\"local\",\"c\"],\"nil?\",[],null],[\"return\",[\"send\",null,\"__unsupported",
  "__\",[[\"str\",\"Comparable#<= with a nil <=>\"]],null]],null],[\"send\",[\"var\",\"local\",\"c\"",
  "],\"<=\",[[\"int\",0]],null]]],[\"def\",\">\",[[\"preq\",\"other\"]],[\"seq\",[\"vasgn\",\"local",
  "\",\"c\",[\"send\",[\"self\"],\"<=>\",[[\"var\",\"local\",\"other\"]],null]],[\"if\",[\"send\",[",
  "\"var\",\"local\",\"c\"],\"nil?\",[],null],[\"return\",[\"send\",null,\"__unsupported__\",[[\"st",
  "r\",\"Comparable#> with a nil <=>\"]],null]],null],[\"send\",[\"var\",\"local\",\"c\"],\">\",[[\"",
  "int\",0]],null]]],[\"def\",\">=\",[[\"preq\",\"other\"]],[\"seq\",[\"vasgn\",\"local\",\"c\",[\"",
  "send\",[\"self\"],\"<=>\",[[\"var\",\"local\",\"other\"]],null]],[\"if\",[\"send\",[\"var\",\"lo",
  "cal\",\"c\"],\"nil?\",[],null],[\"return\",[\"send\",null,\"__unsupported__\",[[\"str\",\"Compar",
  "able#>= with a nil <=>\"]],null]],null],[\"send\",[\"var\",\"local\",\"c\"],\">=\",[[\"int\",0]]",
  ",null]]],[\"def\",\"between?\",[[\"preq\",\"min\"],[\"preq\",\"max\"]],[\"if\",[\"send\",[\"self",
  "\"],\"<\",[[\"var\",\"local\",\"min\"]],null],[\"false\"],[\"send\",[\"send\",[\"self\"],\">\",[",
  "[\"var\",\"local\",\"max\"]],null],\"!\",[],null]]],[\"def\",\"clamp\",[[\"preq\",\"min\"],[\"pr",
  "eq\",\"max\"]],[\"if\",[\"send\",[\"self\"],\"<\",[[\"var\",\"local\",\"min\"]],null],[\"var\",\"",
  "local\",\"min\"],[\"if\",[\"send\",[\"self\"],\">\",[[\"var\",\"local\",\"max\"]],null],[\"var\"",
  ",\"local\",\"max\"],[\"self\"]]]]]]}"
]

/-- The decoded prelude program. `Except` rather than a silent fallback: a
    prelude that fails to decode is a build-time bug, and `Main` exits 1 on it
    rather than running with a missing core library. -/
def program : Except String Expr :=
  match Lean.Json.parse json with
  | .error e => .error s!"prelude JSON parse: {e}"
  | .ok j => Decode.program j

end Prelude
end RubyCore
