#!/usr/bin/env ruby
# frozen_string_literal: true

# Regenerate RubyCore/Prelude.lean from prelude/prelude.rb:
#
#   "$(brew --prefix ruby)/bin/ruby" scripts/gen_prelude.rb > RubyCore/Prelude.lean
#
# The prelude is the **core library written in Ruby** (L62): a program the model
# loads before the program under test, so Enumerable/Comparable/Range/… come
# from RubyCore code the difftest harness already validates rather than from new
# Lean primitives. This script desugars it with the harness desugarer and embeds
# the resulting RubyCore JSON as a Lean string literal; the model decodes it with
# the *real* decoder (`Decode.program`) at boot, so no second AST encoding exists
# that could drift from the export format.
#
# Fails loudly (non-zero exit, nothing on stdout) if the prelude is out of the
# desugar fragment — a prelude that silently half-loads would be a coverage hole.

lib = File.expand_path("../../harness/desugar-dt/lib", __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require "desugar"
require "export"

src_path = File.expand_path("../prelude/prelude.rb", __dir__)
src = File.read(src_path)

begin
  core, = Desugar.program(src)
rescue Desugar::Unsupported => e
  warn "prelude is out of the desugar fragment: #{e.message}"
  exit 1
end

json = Export.json(core)

# Escape for a Lean string literal, cutting into ~96-char chunks at character
# boundaries (never inside an escape sequence) so the generated file stays
# readable and diffable.
CHUNK = 96
chunks = []
cur = +""
json.each_char do |ch|
  esc = case ch
        when "\\" then "\\\\"
        when '"' then '\\"'
        when "\n" then "\\n"
        else ch
        end
  cur << esc
  if cur.length >= CHUNK
    chunks << cur
    cur = +""
  end
end
chunks << cur unless cur.empty?

puts <<~HEADER
  /-
  GENERATED by `scripts/gen_prelude.rb` from `prelude/prelude.rb` — do not edit.

  The **prelude**: the part of Ruby's core library that is modeled *in RubyCore
  itself* rather than as Lean primitives (L62). Phase 1 of the boot runs this
  program from H₀ with `preludeMode := true` (so its `def`s are marked
  `fromPrelude`); phase 2 runs the program under test on the resulting heap
  (`Machine.initOn`).

  Carried as the desugared RubyCore **JSON**, decoded by the ordinary
  `Decode.program`: there is exactly one AST encoding in the system, so the
  prelude cannot drift from the export format the difftest harness validates.
  -/
  import RubyCore.Syntax

  namespace RubyCore
  namespace Prelude

  /-- The desugared prelude, as exported RubyCore JSON (`Export::VERSION` 4). -/
  def json : String := String.join [
HEADER

chunks.each_with_index do |c, i|
  puts %(  "#{c}"#{i == chunks.length - 1 ? "" : ","})
end

puts <<~FOOTER
  ]

  /-- The decoded prelude program. `Except` rather than a silent fallback: a
      prelude that fails to decode is a build-time bug, and `Main` exits 1 on it
      rather than running with a missing core library. -/
  def program : Except String Expr :=
    match Lean.Json.parse json with
    | .error e => .error s!"prelude JSON parse: {e}"
    | .ok j => Decode.program j

  end Prelude
  end RubyCore
FOOTER
