#!/usr/bin/env ruby
# frozen_string_literal: true

# Core boot and optional features share the real desugar/export/decoder path.
# Run with: ruby scripts/gen_prelude.rb > RubyCore/PreludeJson.lean
# then:     lake exe genprelude > RubyCore/Prelude.lean   (or just `make gen`)
lib = File.expand_path("../../desugar/lib", __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require "desugar"
require "export"

sources = [["core", File.expand_path("../prelude/prelude.rb", __dir__)]]
sources += Dir[File.expand_path("../prelude/features/*.rb", __dir__)].sort.map { |p| [File.basename(p, ".rb"), p] }
programs = sources.map do |name, path|
  begin
    core, = Desugar.program(File.read(path))
    [name, Export.json(core, literal_namespace: "prelude:#{name}")]
  rescue Desugar::Unsupported => e
    abort "prelude #{name} is out of the desugar fragment: #{e.message}"
  end
end

# Chunk only between characters, never inside a Lean escape.
def emit_json(name, json)
  chunks = []
  current = +""
  json.each_char do |ch|
    current << case ch
               when "\\" then "\\\\"
               when '"' then '\\"'
               when "\n" then "\\n"
               else ch
               end
    if current.length >= 96
      chunks << current
      current = +""
    end
  end
  chunks << current unless current.empty?
  puts "def #{name} : String := String.join ["
  chunks.each_with_index { |c, i| puts %(  "#{c}"#{i == chunks.length - 1 ? "" : ","}) }
  puts "]\n"
end

puts <<~LEAN
  /-
  GENERATED by scripts/gen_prelude.rb from prelude/prelude.rb and
  prelude/features/*.rb. Do not edit.

  The prelude as the desugarer exports it: JSON, decoded by the ordinary
  Decode.program. Nothing in the model imports this file. `lake exe genprelude`
  reads it and writes RubyCore/Prelude.lean, the same programs as Lean terms,
  which is what the model boots from.
  -/
  import RubyCore.Syntax

  namespace RubyCore.PreludeJson
LEAN
emit_json("json", programs[0][1])
programs.drop(1).each_with_index { |(_, json), i| emit_json("featureJson#{i}", json) }
puts <<~LEAN
  private def decode (text : String) : Except String Expr := do
    let j ← Json.parse text
    Decode.program j

  def program : Except String Expr := decode json

  def features : Except String (List (String × Expr)) := do
LEAN
programs.drop(1).each_with_index { |(_, _), i| puts "  let p#{i} ← decode featureJson#{i}" }
puts "  return [" + programs.drop(1).each_with_index.map { |(name, _), i| "(#{name.inspect}, p#{i})" }.join(", ") + "]"
puts "\nend RubyCore.PreludeJson"
