#!/usr/bin/env ruby
# frozen_string_literal: true

# L294: the Unicode character predicates used by CRuby's symbol.c.
# Generate the table for the pinned oracle; --verify cross-checks every Unicode
# scalar against native Module#const_defined? and String#inspect (no constants installed).
require 'rbconfig'
abort 'requires CRuby' unless RUBY_ENGINE == 'ruby'
verify = ARGV.delete('--verify')
abort 'usage: gen_unicode.rb [--verify]' unless ARGV.empty?
probe = Module.new
start = /\A[[:upper:]\p{Lt}]\z/u
ranges = []
nonprint = []
printable = /\A[[:print:]]\z/u
count = 0
(0..0x10ffff).each do |cp|
  next if (0xd800..0xdfff).cover?(cp)
  char = cp.chr(Encoding::UTF_8)
  allowed = start.match?(char)
  prints = printable.match?(char)
  if verify
    native = begin
      probe.const_defined?(char, false)
      true
    rescue NameError
      false
    end
    abort "start-character mismatch: U+#{cp.to_s(16)}" unless native == allowed
    native_prints = [34, 92].include?(cp) || char.inspect == '"' + char + '"'
    abort "printable mismatch: U+#{cp.to_s(16)}" unless native_prints == prints
  end
  if cp >= 128 && !prints
    if !nonprint.empty? && nonprint[-1][1] == cp - 1
      nonprint[-1][1] = cp
    else
      nonprint << [cp, cp]
    end
  end
  next unless allowed
  count += 1
  if !ranges.empty? && ranges[-1][1] == cp - 1
    ranges[-1][1] = cp
  else
    ranges << [cp, cp]
  end
end
warn "verified printability and constant starts for all 1,112,064 Unicode scalars; #{count} allowed starts" if verify
puts <<~LEAN
  /- Generated by scripts/gen_unicode.rb from CRuby #{RUBY_VERSION},
     Unicode #{RbConfig::CONFIG['UNICODE_VERSION']}. Do not edit by hand.
     L294: symbol.c rb_sym_constant_char_p accepts uppercase or titlecase starts;
     subsequent UTF-8 scalars use is_identchar (all non-ASCII scalars qualify).
     Printability comes from the matching regexp property, verified against
     native String#inspect, including the U+0085 exception in string.c. -/
  namespace RubyCore

  private def constantStartRanges : Array (Nat × Nat) := #[
LEAN
puts ranges.map { |lo, hi| "  (#{lo}, #{hi})" }.join(",\n")
puts <<~LEAN
  ]

  def constantStart (c : Char) : Bool :=
    if c.toNat < 128 then c.isUpper else
    constantStartRanges.any fun (lo, hi) => lo ≤ c.toNat && c.toNat ≤ hi

  def validConstantName (name : String) : Bool :=
    match name.toList with
    | [] => false
    | c :: rest => constantStart c &&
        rest.all (fun c => c.toNat ≥ 128 || c.isAlphanum || c == '_')

  private def nonprintRanges : Array (Nat × Nat) := #[
LEAN
puts nonprint.map { |lo, hi| "  (#{lo}, #{hi})" }.join(",\n")
puts <<~LEAN
  ]

  def unicodePrintable (c : Char) : Bool :=
    if c.toNat < 128 then 32 ≤ c.toNat && c.toNat < 127 else
    !nonprintRanges.any (fun (lo, hi) => lo ≤ c.toNat && c.toNat ≤ hi)

  end RubyCore
LEAN
