#!/usr/bin/env ruby
# frozen_string_literal: true

# The require/require_relative library fixture (issue #7 / M1 "require over the
# VFS"). Every `.rb` under prelude/vfs/ is both:
#   * mounted into the symbolic filesystem as a regular file (its bytes), so
#     File.read and resolution see exactly what `require_relative` runs, and
#   * desugared once here into a RubyCore `Expr` body, so the model never parses
#     Ruby at run time (the desugarer is the untrusted front end, as for the
#     prelude features).
#
# Because both come from the same source file in one `make gen`, the bytes and
# the body cannot drift apart. The VFS path of a file is its path under
# prelude/vfs/, so prelude/vfs/lib/greeting.rb lives at /lib/greeting.rb.
#
# Two steps, exactly like the prelude (PreludeJson → Prelude): this writes the
# JSON (VfsFixtureJson.lean); then `lake exe genvfs` decodes it with the model's
# own decoder and writes RubyCore/Generated/VfsFixture.lean as RubyCore *terms*,
# which is what Boot imports and the kernel can evaluate. A body defined as
# "decode this string" would be opaque (Json.parse does not reduce), so nothing
# could be proved about the booted heap.
#
# Run with: ruby scripts/gen_vfs.rb > RubyCore/Generated/VfsFixtureJson.lean
# then:     lake exe genvfs > RubyCore/Generated/VfsFixture.lean   (or `make gen`).
lib = File.expand_path("../../desugar/lib", __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require "desugar"
require "export"

root = File.expand_path("../prelude/vfs", __dir__)
paths = Dir[File.join(root, "**", "*.rb")].sort
files = paths.map do |path|
  vpath = path.delete_prefix(root) # e.g. "/lib/greeting.rb"
  src = File.read(path)
  begin
    core, = Desugar.program(src)
  rescue Desugar::Unsupported => e
    abort "vfs fixture #{vpath} is out of the desugar fragment: #{e.message}"
  end
  [vpath, src, Export.json(core, literal_namespace: "vfs:#{vpath}")]
end

# Chunk a string into Lean string-literal pieces, escaping as we go and never
# splitting inside an escape (copied from scripts/gen_prelude.rb).
def emit_string(name, text)
  chunks = []
  current = +""
  text.each_char do |ch|
    current << case ch
               when "\\" then "\\\\"
               when '"' then '\\"'
               when "\n" then "\\n"
               else ch
               end
    if current.length >= 96
      chunks << current
      current = +""
    end
  end
  chunks << current unless current.empty?
  puts "def #{name} : String := String.join ["
  if chunks.empty?
    puts %(  "")
  else
    chunks.each_with_index { |c, i| puts %(  "#{c}"#{i == chunks.length - 1 ? "" : ","}) }
  end
  puts "]\n"
end

puts <<~LEAN
  /-
  GENERATED by scripts/gen_vfs.rb from prelude/vfs/**/*.rb. Do not edit; run
  `make gen`.

  The require/require_relative library fixture as the desugarer exports it: JSON,
  plus the raw bytes and pre-split path components. `lake exe genvfs` reads this
  and writes RubyCore/Generated/VfsFixture.lean, the bodies as RubyCore terms,
  which Boot imports. Nothing in the model imports this file.
  -/
  import RubyCore.Syntax

  namespace RubyCore.VfsFixtureJson
LEAN

files.each_with_index { |(_, _, json), i| emit_string("bodyJson#{i}", json) }

puts "private def decode (text : String) : Except String Expr := do"
puts "  let j ← Json.parse text"
puts "  Decode.program j"
puts ""
puts "/-- The desugared bodies, in the fixture's sorted order — the same order as"
puts "    `rawFiles`, so boot can pair them by position. Consumed by `genvfs`. -/"
puts "def bodies : Except String (List Expr) := do"
files.each_index { |i| puts "  let b#{i} ← decode bodyJson#{i}" }
puts "  return [" + files.each_index.map { |i| "b#{i}" }.join(", ") + "]"
puts ""
puts "/-- Each file as `(canonical path, path components, bytes)`, in the same order"
puts "    as `bodies`. The components are split here (not at boot) because"
puts "    `String.splitOn` does not reduce in the kernel, and the booted heap must."
puts "    The files are mounted into the VFS so `File.read` matches what runs. -/"
files.each_with_index { |(_, src, _), i| emit_string("rawBytes#{i}", src) }
def comps_literal(vpath)
  "[" + vpath.split("/").reject(&:empty?).map(&:inspect).join(", ") + "]"
end
puts "def rawFiles : List (String × List String × String) :="
puts "  [" + files.each_with_index.map { |(vpath, _, _), i|
    "(#{vpath.inspect}, #{comps_literal(vpath)}, rawBytes#{i})" }.join(",\n   ") + "]"
puts ""
puts "end RubyCore.VfsFixtureJson"
