#!/usr/bin/env ruby
# frozen_string_literal: true

# L293: generate CRuby's Unicode printability table. --verify cross-checks every
# Unicode scalar against native String#inspect using the pinned oracle.
require 'rbconfig'
abort 'requires CRuby' unless RUBY_ENGINE == 'ruby'
verify = ARGV.delete('--verify')
abort 'usage: gen_unicode.rb [--verify]' unless ARGV.empty?
nonprint = []
printable = /\A[[:print:]]\z/u
(0..0x10ffff).each do |cp|
  next if (0xd800..0xdfff).cover?(cp)
  char = cp.chr(Encoding::UTF_8)
  prints = printable.match?(char)
  if verify
    native_prints = [34, 92].include?(cp) || char.inspect == '"' + char + '"'
    abort "printable mismatch: U+#{cp.to_s(16)}" unless native_prints == prints
  end
  next if cp < 128 || prints
  if !nonprint.empty? && nonprint[-1][1] == cp - 1
    nonprint[-1][1] = cp
  else
    nonprint << [cp, cp]
  end
end
warn 'verified printability for all 1,112,064 Unicode scalars' if verify
puts <<~LEAN
  /- Generated by scripts/gen_unicode.rb from CRuby #{RUBY_VERSION},
     Unicode #{RbConfig::CONFIG['UNICODE_VERSION']}. Do not edit by hand.
     L293: printability comes from the matching regexp property, verified against
     native String#inspect, including the U+0085 exception in string.c. -/
  namespace RubyCore

  private def nonprintRanges : Array (Nat × Nat) := #[
LEAN
puts nonprint.map { |lo, hi| "  (#{lo}, #{hi})" }.join(",\n")
puts <<~LEAN
  ]

  def unicodePrintable (c : Char) : Bool :=
    if c.toNat < 128 then 32 ≤ c.toNat && c.toNat < 127 else
    !nonprintRanges.any (fun (lo, hi) => lo ≤ c.toNat && c.toNat ≤ hi)

  end RubyCore
LEAN
